### ISSUE TITLE
[Substance] Showing JColorChooser dialog crashes JVM

### ISSUE THREAD

**Issue by ssoloff** [kirill-grouchnikov/radiance#102]
### Version of Radiance (current development is 1.5-SNAPSHOT)

1.0.2

### Sub-project (Neon, Trident, Substance, Flamingo, ...)

Substance

### Version of Java (current minimum is 8)

Oracle Java SE 1.8.0_191

```
$ $JAVA_HOME/bin/java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

### Version of OS

Fedora 28 x86_64 (GNOME 3.28.2)

```
$ uname -a
Linux localhost.localdomain 4.18.16-200.fc28.x86_64 #1 SMP Sat Oct 20 23:53:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

Calling `JColorChooser#showDialog()` with a Substance L&F active crashes the JVM.

#### Reproduction steps

1. Load a Substance L&F (I tried both Graphite and Raven).
1. Call `JColorChooser#showDialog()`.

#### Expected behavior

The color chooser dialog should be displayed.

#### Actual behavior

The JVM crashes (see [log](https://github.com/kirill-grouchnikov/radiance/files/2592182/hs_err_pid2477.log)).

#### Additional information

I created an [MCVE](https://github.com/ssoloff/substance-color-chooser-crash-test) to demonstrate this issue.  The actual code to trigger the crash is pretty straightforward:

```java
public static void main(final String[] args) throws Exception {
    SwingUtilities.invokeAndWait(() -> {
        try {
            // commenting out the next line will prevent the JVM crash
            UIManager.setLookAndFeel("org.pushingpixels.substance.api.skin.SubstanceGraphiteLookAndFeel");
            JColorChooser.showDialog(null, "Choose Color", Color.BLACK);
        } catch (final Exception e) {
            e.printStackTrace();
        }
    });
}
```

As the comment suggests, using the default L&F (Nimbus in my case), produces the expected behavior.

##### Substance 1.5-SNAPSHOT

The same actual behavior occurs when I use Substance 1.5-SNAPSHOT.

##### OpenJDK JRE on Linux

If I build and run the MCVE using OpenJDK JRE 1.8.0_181, the JVM does not crash, and the color chooser dialog is displayed.  However, the resulting dialog appears to be frozen and does not respond to any user input:

![substance-color-chooser-dialog-openjdk](https://user-images.githubusercontent.com/4826349/48665119-25252800-ea77-11e8-9a50-38914c263f3a.png)

##### Oracle JRE on Windows

When running the Oracle-JDK-built MCVE artifact on a Windows x86_64 box with Oracle JRE 1.8.0_191, the color chooser dialog is shown and behaves as expected.

#### Final thoughts

I realize there may be a legitimate Linux-specific JVM bug that needs to be fixed here because the JVM should never crash.  However, my guess is it would be easier for the Radiance team to report this bug as it seems to be triggered by something Substance is doing.

If there is a Substance-specific change that could be deployed (or some workaround I could employ from application code) to mask the JVM issue, it would be greatly appreciated.

**Comment by brunchboy** [comment]
I’m just an interloper who is a grateful (and somewhat awed) user of the Radiance project, but I cannot resist weighing in to say this is one of the best issues I have ever seen opened, with reams of quality research, information, and motivation to back it up. I am also glad I don’t have to be the one responding to it, though! 😉 And as far as I know the Radiance team is just @kirill-grouchnikov

**Comment by kirill-grouchnikov** [comment]
The crash is in here:

Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libawt_xawt.so+0x3fc39]  ReadRegionsInList.constprop.5+0x4e9
C  [libawt_xawt.so+0x401e6]  ReadAreaToImage+0x86
C  [libawt_xawt.so+0x37c60]  Java_sun_awt_X11_XRobotPeer_getRGBPixelsImpl+0x120
j  sun.awt.X11.XRobotPeer.getRGBPixelsImpl(Lsun/awt/X11GraphicsConfig;IIII[I)V+0
j  sun.awt.X11.XRobotPeer.getRGBPixels(Ljava/awt/Rectangle;)[I+33
j  java.awt.Robot.createScreenCapture(Ljava/awt/Rectangle;)Ljava/awt/image/BufferedImage;+50
j  org.pushingpixels.substance.internal.contrib.randelshofer.quaqua.colorchooser.Quaqua15ColorPicker.<init>()V+70

I think it's about time to remove the color capture part of the long-ago contributed color chooser. It's crashing in native code here (which seems like a JVM problem), and only working half the time on my Mac machine.

**Comment by kirill-grouchnikov** [comment]
The workaround is to call `SubstanceCortex.GlobalScope.setUseDefaultColorChooser()`

**Comment by ssoloff** [comment]
Thanks, @kirill-grouchnikov!  That works perfectly in the application that originally motivated this issue.

The workaround resolves this issue for my team.  However, I'm not sure if you want to leave it open to track anything for you on the implementation side.  Please feel free to close it, if you wish.
