### ISSUE TITLE
Support for drag and drop tabs

### ISSUE THREAD

**Issue by tropicaldev** [kirill-grouchnikov/radiance#105]
Support for drag and drop tabs

I'm missing that flexibility...how complicated would be to implement it radiance?

Maybe just a question of re-indexing tabs and repaiting...just guessing, of course is not that simple.

It was a very usefull option to have...

**Comment by kirill-grouchnikov** [comment]
What do you mean by "it was a very useful option to have"? I don't recollect having ever implemented this functionality in Substance.

**Comment by tropicaldev** [comment]
no you havent :)

Sorry for my english, what i wanted to say was "it was very usefull to have this option"

Because some apps allow to do it  i found myself (and guess many others) trying to do the same in other apps that don't 

Like many things  "there is no need until you try it once"

**Comment by kirill-grouchnikov** [comment]
My current view on it is that I want to move away from adding new behavioral functionality to core Swing widgets at the Substance layer. There were quite a few of those in earlier iterations of Substance, and some of that has been removed in the last couple of years.

Apart from browsers that let you rearrange tabs (or even extract tabs to a separate top-level window), I don't recall other scenarios where this would be useful. Not saying that such scenarios don't exist though.

I will say that it's quite unlikely that I will be adding this to Substance / Radiance in the near future. So closing this for now.

**Comment by tropicaldev** [comment]
I understand your options but i disagree with

"don't recall other scenarios where this would be useful"

Everything that allows you to organize i think it's a good scenario.

I'm thinking of giving it a try...not thinking of "special effects"...yet :)
if you could point me out some direction and what i should need to do, it would be great

**Comment by tropicaldev** [comment]
At the level of ui delegate would apply to all instances but will force to merge changes with future versions of radiance

So maybe a container would be the best option
