### ISSUE TITLE
Tab modified effect shows only if mouse is over the tab

### ISSUE THREAD

**Issue by tropicaldev** [kirill-grouchnikov/radiance#107]
Tab modified effect shows only if mouse is over the tab

tested with 
- radiance version 1.0.2
- jre 1.6 and 1.8

**Comment by tropicaldev** [comment]
how can the tab that changed get the attention needed if the affect does not appear on the tab?

**Comment by kirill-grouchnikov** [comment]
Then the app would probably need to figure out a more centralized way to notify the user of such changes. To be honest, I consider `JTabbedPane` (together with `JDesktopPane`) as something that has not aged well with time. Modern apps would probably find themselves doing their own containers for working with multiple "documents". As such, I don't plan to spend much time on either of these two going forward.

**Comment by tropicaldev** [comment]
Ok, 

but maybe im missing something...the intended behaviour is blinking only on rollover/active?

On "active" the effect is not needed because the tab is active...dont see the purpose
On "rollover" does not help alot...

The effect is most necessary when the tab is non-active...completely the oposit

the property SubstanceSynapse.CONTENTS_MODIFIED has no use then...it was very usefull with JTabbedPanes
