### ISSUE TITLE
Option to show border on all tabs

### ISSUE THREAD

**Issue by tropicaldev** [kirill-grouchnikov/radiance#108]
Radiance shows only borders on select tab

Is there an option to show on all tabs?

**Comment by kirill-grouchnikov** [comment]
This is the intended look - to remove a lot of visual noise "traditionally" present in Swing components, such as tabbed panes, scroll bars, toolbars etc. There is no option to turn that noise back on.

**Comment by tropicaldev** [comment]
I understand and i like it

Not sure if visually will work fine with every app...borders allows to restrict the look to
