### ISSUE TITLE
[Substance] Choppy Frame Resizing

### ISSUE THREAD

**Issue by michaelbull** [kirill-grouchnikov/radiance#12]
### Version of Radiance

1.0.00-dev

### Sub-project (Trident, Substance, Flamingo, ...)

Substance

### Version of Java

```openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
```

### Version of OS

Fedora, 4.16.7-300.fc28.x86_64

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

Frame resizing is not smooth even on a blank application, see: https://gfycat.com/BlissfulHardArrowworm

**Comment by kirill-grouchnikov** [comment]
There's a long-standing Swing bug in which resizing a decorated frame is not smooth. Do you see the same issue under Metal look-and-feel? 

You can try using System.setProperty("sun.awt.noerasebackground", "true") but I'm not sure how far along that can take you.

**Comment by michaelbull** [comment]
>You can try using System.setProperty("sun.awt.noerasebackground", "true") but I'm not sure how far along that can take you.

Yeah, I already had this set during the video capture

>Do you see the same issue under Metal look-and-feel?

No, I don't

>There's a long-standing Swing bug in which resizing a decorated frame is not smooth.

That's unfortunate, I guess this can be closed then if it isn't a Substance-specific issue.

**Comment by kirill-grouchnikov** [comment]
In my experience, the level of choppiness is roughly similar between Substance and Metal on resizing decorated frames on Windows and Mac. Not sure how much different it is on Linux variants.
