### ISSUE TITLE
[flamingo] ribbon demo apps div issues

### ISSUE THREAD

**Issue by extremeCrazyCoder** [kirill-grouchnikov/radiance#123]
I have found another 3

### Version of Radiance (current development is 2.0-SNAPSHOT)
91d093411c2592a68ec031b34e8443867f91a450

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Flamingo

### Version of Java (current minimum is 8)
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)

### Version of OS
Ubuntu 18.04

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
1) SmallCheckRibbon:
Exception
in thread "AWT-EventQueue-0" java.lang.NullPointerException
at org.pushingpixels.demo.flamingo.ribbon.BasicCheckRibbon$1.onColorPreviewActivated(BasicCheckRibbon.java:778)
at org.pushingpixels.demo.flamingo.ribbon.BasicCheckRibbon$2.onCommandPreviewActivated(BasicCheckRibbon.java:803)
at org.pushingpixels.flamingo.api.common.JCommandButton$1.stateChanged(JCommandButton.java:434)
	at java.desktop/javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:352)
	at org.pushingpixels.flamingo.api.common.model.ActionRepeatableButtonModel.setRollover(ActionRepeatableButtonModel.java:178)
	at org.pushingpixels.flamingo.internal.ui.common.BasicCommandButtonListener.syncMouseMovement(BasicCommandButtonListener.java:172)
	at org.pushingpixels.flamingo.internal.ui.common.BasicCommandButtonListener.mouseEntered(BasicCommandButtonListener.java:149)
	at java.desktop/java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:307)
	at java.desktop/java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:307)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6598)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6354)
	at java.desktop/java.awt.Container.processEvent(Container.java:2261)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)

How to reproduce:
- run app
- click on Styles3 at PageLayout -> QuickStyles
- hover over one of the colours

2. Small Check Ribbon / Basic Check Ribbon:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.pushingpixels.flamingo.internal.ui.ribbon.appmenu.JRibbonApplicationMenuButton.<init>(JRibbonApplicationMenuButton.java:120)
	at org.pushingpixels.flamingo.internal.ui.ribbon.BasicRibbonUI.lambda$installListeners$1(BasicRibbonUI.java:140)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8685)
	at org.pushingpixels.flamingo.api.ribbon.JRibbon.setApplicationMenuCommand(JRibbon.java:762)
	at org.pushingpixels.demo.flamingo.ribbon.BasicCheckRibbon.lambda$getControlPanel$87(BasicCheckRibbon.java:2095)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)

How to reproduce:
- run app
- change the visibility of App menu (can be found on the right side)

3. Small Check Ribbon / Basic Check Ribbon:
trailing text is cropped inside the Wrapped tab
![grafik](https://user-images.githubusercontent.com/25514433/51264629-404cdf00-19b7-11e9-8aab-815c360cf1b4.png)

I have seen similar issues before. This seems to happen on linux PCs. Windows displays these elemnts normal (maybe another standard font?). Increasing the width solves this problem.
As it seems to me you are using fixed size values for the dimensions (set by the "setValues" mehtod). Is there a way to choose the size of the UI elements depending on the content?

thanks for looking at this issue in advance

**Comment by kirill-grouchnikov** [comment]
Thanks for these. SmallCheckRibbon has outlived its usefulness and will be removed shortly.

Will look into the app menu visibility issue. 

As for the cut off label, that's certainly not expected. The bounds for the label is set in BasicRibbonComponentUI lines 308-318. It should definitely respect the preferred size of the JLabel itself as it reports, so there should be no cutting off. Does it happen under specific fonts? What does it mean "Increasing the width solves the problem"? Does it mean that it comes on and off depending on how wide the overall ribbon frame is?

**Comment by kirill-grouchnikov** [comment]
As for setValues, if you're referring to RibbonSpinnerNumberContentModel.Builder.setValues, those are for the content of the spinner itself and not how wide the spinner presentation ends up being.

**Comment by extremeCrazyCoder** [comment]
according to SmallCheckRibbon
I already thought, that you could remove this, because it is just a part of BasicCheckRibbon.

When it should respect the actual size you can ignore my comment about increasing the witdh, because this is just for fixed size labels
I meant that manually setting the width of the label normaly resolves this problem.

ok thanks for the information about setValues. I have just seen 4 integers and thought that they are the dimensions of the object (I am currently trying to understand this API, because of this I find all those Issues)

**Comment by kirill-grouchnikov** [comment]
Ribbon*ContentModel classes are thin wrappers around the core Swing models, so there's nothing new there. The plan for the next few weeks is to provide proper documentation for Flamingo - from the simple commands all the way to the entire ribbon API surface.

**Comment by kirill-grouchnikov** [comment]
Does the label cut off happen only on this specific version of Java / Ubuntu? I don't have access to that environment unfortunately.

**Comment by extremeCrazyCoder** [comment]
as far as I remember this happens also with other Java / Ubuntu versions (tested with other applications)
If I should test something (run specific code) for debbuging reasons please let me know.

as of the documentation: I have seen that you have done it very well inside the classes. I don't know if this is possible, but maybe you could automatically generate the documentation from that information

**Comment by kirill-grouchnikov** [comment]
Do you see similar label cutoffs in the main Substance demo? It is in org.pushingpixels.demo.substance.main.Check class in the substance-demo module.

**Comment by extremeCrazyCoder** [comment]
I have to correct my previous statement

with the following setup the labels are correct (I have found an old VM):
Ubuntu 16.04
openjdk version 1.8.0_191 (build 1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12)
![grafik](https://user-images.githubusercontent.com/25514433/51271257-59f62280-19c7-11e9-9e8c-19bd3a1df04a.png)


with my original setup this issue also happens in the substance demo:
![grafik](https://user-images.githubusercontent.com/25514433/51271455-e9033a80-19c7-11e9-8cfc-60e8d1801a2a.png)

**Comment by extremeCrazyCoder** [comment]
Maybe this helps here are some more screenshots:
![grafik](https://user-images.githubusercontent.com/25514433/51271557-28318b80-19c8-11e9-8a86-019edecc5674.png)

![grafik](https://user-images.githubusercontent.com/25514433/51271579-354e7a80-19c8-11e9-81d7-3d3856c00ead.png)

![grafik](https://user-images.githubusercontent.com/25514433/51271599-439c9680-19c8-11e9-82f2-5fd1cb789314.png)

![grafik](https://user-images.githubusercontent.com/25514433/51271612-4b5c3b00-19c8-11e9-84ad-71383f1fc426.png)

it seems that this happens just if the font has not been set manually

**Comment by kirill-grouchnikov** [comment]
Looks like it's a deeper issue then which applies to JLabels and JButtons, at least, under the default font set used on GNOME desktops. The font itself is computed in DefaultGnomeFontPolicy.getFontSet. Then it is set as the global Substance font policy.

It is likely that the usage of reflection in DefaultGnomeFontPolicy.getFontSet might fail on OpenJDK builds if they don't have the sun.font.FontManager class. But that should still get to line 135 that falls back on sans / dialog.

Probably something has changed in OpenJDK builds from 8 til 10. I do not do any testing on OpenJDK, only on the official builds from Oracle. 

The decision on whether to do clipping or not is done in SubstanceLabelUI line 126 where it calls SwingUtilities.layoutCompoundLabel to "decide" where each part of the label goes (text, icon). 

The core bug here appears to be that under some fonts on some variants of OpenJDK there is a mismatch between what is done in BasicLabelUI.getPreferredSize (which eventually calls SwingUtilities.layoutCompoundLabel) and SubstanceLabelUI.paint (which calls the same SwingUtilities.layoutCompoundLabel)

**Comment by extremeCrazyCoder** [comment]
I don't know if I should open a new Issue, but I found also a but with the progress bars (maybe related)
![grafik](https://user-images.githubusercontent.com/25514433/51272312-1bae3280-19ca-11e9-9343-5e13b1927dbc.png)

I have just downloaded https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html and it seems, that this produces the same issues (I will do some more testing with other versions)

**Comment by extremeCrazyCoder** [comment]
ok I will open a seperate Issue as soon as I have got enough information

**Comment by extremeCrazyCoder** [comment]
vendor / java.runtime.version : result
oracle jdk / 11.0.2+7-LTS: Same Issue as above
open jdk / 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12: Same Issue as above
oracle jdk / 1.8.0_202-b08: no issues
open jdk / 10.0.2+13-Ubuntu-1ubuntu0.18.04.4: Same Issue as above

I have read the text you wrote (and done some reading of the source code you referenced)
I think you already said that, but just to check that I understood:
you are using
`g.getFontMetrics()`
that equals
`g.getFontMetrics(g.getFont())`

and the internal implementation of Java (for getting the preffered size) uses
`label.getFontMetrics(label.getFont())`
the internal implementation of paint inside BasicLabelUI uses SwingUtils2.getFontMetrics that uses
`label.getFontMetrics(g.getFont())`

so it seems that what you wrote is the problem.

the only other thing that could cause problems is if the font of g and the font of the label are not the same, Could it be possible that this happens, and if so how could I test this?

**Comment by kirill-grouchnikov** [comment]
SmallCheckRibbon removed to address #1 
Crash on hiding application menu #2 addressed

https://github.com/kirill-grouchnikov/radiance/issues/124 is tracking #3
