### ISSUE TITLE
[Substance] Different FontMetrics used during preferred size and rendering

### ISSUE THREAD

**Issue by kirill-grouchnikov** [kirill-grouchnikov/radiance#124]
Splitting from https://github.com/kirill-grouchnikov/radiance/issues/123

There are at least four places in Substance that use `SwingUtilities.layoutCompoundLabel` to determine text rendering metrics, including whether to elide the text - UI delegates for buttons, toggle buttons, labels and radio buttons (and, by extension, check boxes). The `FontMetrics` object passed in each place is taken from the current `Graphics` which at that point has already been configured with `NeonCortex.installDesktopHints`.

However, none of these UI delegates do the matching desktop hints "inclusion" in the `getPreferredSize` implementation. 

The end result is that, for some platforms, the mismatch leads to `getPreferredSize` returning the width that is by a pixel or two smaller than it would be with the inclusion of desktop hints. And that means that in those scenarios, some of the texts for labels, buttons, radio buttons and check boxes get cut off and display ellipses instead.

Doesn't look like there's a public API to tweak the `FontMetrics` object returned from `JComponent.getFontMetrics` call. My current thinking is to use a static, offscreen image that would be used to match the logic in `update` / `paint` pass. There's going to be a new helper method (or two) similar to `BasicGraphicsUtils.getPreferredButtonSize` that would replace the `JComponent.getFontMetrics` call with setting the current component font on that offscreen image, installing the desktop hints and using the font metrics from the image's `Graphics` to pass on to `SwingUtilities.layoutCompoundLabel`.

If anything, this should be part of the core Swing UI delegates (basic) to match the desktop hints installed as part of those UI delegates during the painting phase.

**Comment by kirill-grouchnikov** [comment]
Also replace all usage of `JComponent.getFontMetrics` in Substance and Flamingo to respect the desktop hints.

**Comment by kirill-grouchnikov** [comment]
Just submitted the very first pass for aligning font metrics usage - just for `JLabel`. This needs to be made more general to work on buttons, check boxes and radio buttons. And then to do the same everywhere as detailed above.

**Comment by extremeCrazyCoder** [comment]
Tests using oracle jdk / 11.0.2+7-LTS:
at 0de45fc9fc50a643fc029cf81b092e0f96279740:
![grafik](https://user-images.githubusercontent.com/25514433/51336546-1235d080-1a85-11e9-9c03-fb5a43dd5d96.png)
Console output:
 CREATING LAF 
 LAF CREATED 67
 SETTING LAF 
 LAF SET 32
App 848

at 91d093411c2592a68ec031b34e8443867f91a450:
![grafik](https://user-images.githubusercontent.com/25514433/51336710-88d2ce00-1a85-11e9-8e06-61af311a8350.png)
Console output:
 CREATING LAF 
 LAF CREATED 63
 SETTING LAF 
 LAF SET 40
App 995


Tests using other java versions:
open jdk / 10.0.2+13-Ubuntu-1ubuntu0.18.04.4: not working
open jdk / 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12: not working
oracle jdk / 11.0.2+7-LTS: not working
oracle jdk / 1.8.0_202-b08: not working

Oracle jdk 1.8:
![grafik](https://user-images.githubusercontent.com/25514433/51337679-0e577d80-1a88-11e9-88bf-10e9125a9ec6.png)


The interesting part is that Oracle jdk 1.8 (were it was previously working) does also this cropping, but in an other way than all the other versions.
Maybe you are creating the offscreen image the wrong way?
what is the meaning of the values seen on the command line? They seem to be randomly choosen (running the same application with same java mutliple times gives other values)

**Comment by kirill-grouchnikov** [comment]
There's another round of fixes coming up tonight.

The values in terminal come from lines 460-469. They are for tracing startup performance of Substance.

**Comment by extremeCrazyCoder** [comment]
ok then I will wait and test after that
I didn't know if this schould be already fixed or not, because you just wrote, that you will need to make the code more generic (I interpreted that this code should work for JLabels).

ok thanks for the information. This values are useless for this Issue

**Comment by kirill-grouchnikov** [comment]
This is ready for testing now

**Comment by kirill-grouchnikov** [comment]
Thanks for verifiying!
