### ISSUE TITLE
[Substance] Incorrect offsets for rotated / vertical text rendering

### ISSUE THREAD

**Issue by extremeCrazyCoder** [kirill-grouchnikov/radiance#125]
Split from #123 

![grafik](https://user-images.githubusercontent.com/25514433/51272312-1bae3280-19ca-11e9-9343-5e13b1927dbc.png)

the Font placement for the Progress Bars is wrong

System:
Ubuntu 18.04

Tested Java Versions:
open jdk / 10.0.2+13-Ubuntu-1ubuntu0.18.04.4: not working
open jdk / 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12: not working
oracle jdk / 11.0.2+7-LTS: not working
oracle jdk / 1.8.0_202-b08: working

as @kirill-grouchnikov mentioned there had been a similar issue before: kirill-grouchnikov/substance#30

**Comment by kirill-grouchnikov** [comment]
The comment on https://bugs.openjdk.java.net/browse/JDK-8193588 might be relevant:

> That actually points to a workaround that can be used by the application :
> Instead of :
> `graphics.drawString("Test", 0, 100);`
> use :
> `graphics.translate(0, 100);`
> `graphics.drawString("Test", 0, 0);`
> `graphics.translate(0, -100);`

Can you try going to `SubstanceTextUtilities` line 157 and replace it with:

`int dx = textRect.x;`
`int dy = textRect.y + g2d.getFontMetrics().getAscent()`
`g2d.translate(dx, dy);`
`BasicGraphicsUtils.drawStringUnderlineCharAt(g2d, text, mnemonicIndex, 0, 0);`
`g2d.translate(-dx, -dy);`

to see if this has any effect on the affected configurations?

**Comment by extremeCrazyCoder** [comment]
I can't see any changes
![grafik](https://user-images.githubusercontent.com/25514433/51346524-2b974680-1a9e-11e9-93b0-5cc9ba185857.png)

I have done some debugging and know now why this doesn't change anything:
changes for debbuging:
added 
        `System.out.println("Text: " + text + " /dx: " + dx + " /dy: " + dy);`
to SubstanceTextUtilities.java

changed line 134 of demo.substance.main.check.ProgressBarPanel to:
        `indeterminateEnVer.setString("In fast progress");`

terminal shows following:
```
Text: In fast progress /dx: 0 /dy: 0
Text: In fast progress /dx: 0 /dy: 0
Text: In progress /dx: 78 /dy: 18
Text: In progress /dx: 78 /dy: 18
Text: In fast progress /dx: 0 /dy: 0
Text: In fast progress /dx: 0 /dy: 0
Text: In progress /dx: 78 /dy: 18
Text: In progress /dx: 78 /dy: 18
```

so there is no translation performed for the Vertical bars

**Comment by kirill-grouchnikov** [comment]
That doesn't seem right. `dy` should not be zero as it should account for the font metrics ascent (how many "pixels" of font to account for above the baseline).

**Comment by kirill-grouchnikov** [comment]
Makes me wonder if that's the bug behind this issue in OpenJDK - `Graphics2D` returning an incorrectly configured `FontMetrics` after the call to `.transform`. Can you replace the body of that method with this:

```java
        if ((text == null) || (text.length() == 0)) {
            return;
        }

        Graphics2D g2d = (Graphics2D) g.create();

        g2d.setFont(font);
        g2d.setColor(color);
        int dx = textRect.x;
        int dy = textRect.y + g2d.getFontMetrics().getAscent();

        // fix for issue 420 - call clip() instead of setClip() to
        // respect the currently set clip shape
        if (clip != null) {
            g2d.clip(clip);
        }
        if (transform != null) {
            g2d.transform(transform);
        }
        BasicGraphicsUtils.drawStringUnderlineCharAt(g2d, text, mnemonicIndex, dx, dy);
        g2d.dispose();
```

Essentially the attempted "fix" is to compute the font ascent / dy before applying the transform on the `Graphics2D` object.

**Comment by extremeCrazyCoder** [comment]
you seem to be right I added the debugging before and after the transform and it returns diffrent values:

```
first: Text: In progress /rx: 78 /ry: 4 /fontAscent: 14 /font: Ubuntu /fontMaxAscent: 14 /fontMaxDescent: 14 /fontID: 1915151311
second: Text: In progress /rx: 78 /ry: 4 /fontAscent: 14 /font: Ubuntu /fontMaxAscent: 14 /fontMaxDescent: 14 /fontID: 1915151311
first: Text: In progress /rx: 78 /ry: 4 /fontAscent: 14 /font: Ubuntu /fontMaxAscent: 14 /fontMaxDescent: 14 /fontID: 1915151311
second: Text: In progress /rx: 78 /ry: 4 /fontAscent: 14 /font: Ubuntu /fontMaxAscent: 14 /fontMaxDescent: 14 /fontID: 1915151311
first: Text: In fast progress /rx: 0 /ry: 0 /fontAscent: 14 /font: Ubuntu /fontMaxAscent: 14 /fontMaxDescent: 14 /fontID: 1915151311
second: Text: In fast progress /rx: 0 /ry: 0 /fontAscent: 0 /font: Ubuntu /fontMaxAscent: 0 /fontMaxDescent: 0 /fontID: 1915151311
first: Text: In fast progress /rx: 0 /ry: 0 /fontAscent: 14 /font: Ubuntu /fontMaxAscent: 14 /fontMaxDescent: 14 /fontID: 1915151311
second: Text: In fast progress /rx: 0 /ry: 0 /fontAscent: 0 /font: Ubuntu /fontMaxAscent: 0 /fontMaxDescent: 0 /fontID: 1915151311
```

now I will try it with your code:
![grafik](https://user-images.githubusercontent.com/25514433/51349058-9b103480-1aa4-11e9-8372-226c29b3c11a.png)
It works. Strange bug...

**Comment by kirill-grouchnikov** [comment]
Thanks for confirming. I'll push this fix tonight.

**Comment by extremeCrazyCoder** [comment]
as I have just tested:
this Issue is also present under Win 10 using jdk-11.0.2_windows-x64_bin.zip (from https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html)

fix works with this setup too
