### ISSUE TITLE
[Flamingo] The circular MainMenu of the Ribbon form

### ISSUE THREAD

**Issue by fangyuzhong2016** [kirill-grouchnikov/radiance#135]
### The circular MainMenu of the Ribbon form
 Hello, I read this open source java UI framework, very good, but I have a question:
When I'm doing a Ribbon form, the window's application main menu, I want to use the round menu, but now it looks like a Microsoft Office menu, it's square,
So how do I set up this circular menu? Or does the current framework not support round menus? thank you very much!

![image](https://user-images.githubusercontent.com/16973729/51880345-eafacf80-23b1-11e9-9819-bfa6be6cc32a.png)

![image](https://user-images.githubusercontent.com/16973729/51880354-f221dd80-23b1-11e9-945d-4205f6cd01fd.png)

![image](https://user-images.githubusercontent.com/16973729/51880362-fd750900-23b1-11e9-9721-f39530da1baf.png)

**Comment by kirill-grouchnikov** [comment]
There is no support for circular application menu. It has been removed last year in favor of a more streamlined layout.
