### ISSUE TITLE
[Substance] JTabbedPane titles cut off when vertical

### ISSUE THREAD

**Issue by michaelbull** [kirill-grouchnikov/radiance#14]
### Version of Radiance

1.0.00-dev

### Sub-project (Trident, Substance, Flamingo, ...)

Substance

### Version of Java

8

### Version of OS

Fedora 26

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

[This picture](https://i.imgur.com/E59EjJZ.png) demonstrates the issue - the text is being pushed off way too far to the right and doesn't get drawn inside the bounds of the tab's titlebox.

The code used:

```java
final class SideBar extends JToolBar {
    private static final long serialVersionUID = -7274637780672751510L;

    static final int WIDTH = 200;
    private static final Dimension SIZE = new Dimension(WIDTH, 0);

    private final JTabbedPane tabbedPane = new JTabbedPane();

    void init() {
        setFloatable(false);
        setPreferredSize(SIZE);
        setSize(SIZE);

        JPanel panel1 = new JPanel();
        panel1.add(new JLabel("one"));
        JPanel panel2 = new JPanel();
        panel2.add(new JLabel("two"));

        tabbedPane.setTabPlacement(JTabbedPane.RIGHT);
        tabbedPane.addTab("Title 1", panel1);
        tabbedPane.addTab("Title 2", panel2);
        add(tabbedPane);
    }
}
```

**Comment by kirill-grouchnikov** [comment]
See the last couple of comments on https://github.com/kirill-grouchnikov/substance/issues/30

Does this happen under the latest builds of Java 8, 9 or 10 on that environment?

**Comment by redskoller** [comment]
The same issue occurs under openjdk 11.0.2, windows. Under openjdk 11.0.2 osx everything works fine.
Any ideas to solve the problem under windows?

**Comment by kirill-grouchnikov** [comment]
If this is happening under the latest 3.0-SNAPSHOT build of Substance - but only on that specific combination of OS and JDK version, I'm not sure what I can do on my side.
