### ISSUE TITLE
[Trident] Revisit the "mental model" around timeline creation and configuration

### ISSUE THREAD

**Issue by gregory-ledenev** [kirill-grouchnikov/radiance#143]
### Version of OS

I’ve done a bit of investigation and testing and it seems that Timelines should NOT be reused until they need to be replayed or looped. Otherwise, list of properties to interpolate seems never gets cleared. So any call of addPropertyToInterpolate() just adds another property to the list even if the timeline already finished playing and even if interpolation of this property is already in the timeline. This effectively introduces memory leaks. What worse, any play() call seems goes through that growing list all the times when called.

The solution for this issue would be either:
- make Timeline immutable after calling the play()
- keep it mutable for a reason (if any) but let the play() to throw an exception so the users will be aware of actual behavior - rePlay().

**Comment by kirill-grouchnikov** [comment]
This is not how timelines are reused. A timeline is configured to work on the specific main object with specific properties to interpolate. When a timeline finishes playing, it *does not* clear the list of properties to interpolate. That is by design.

The very first example in https://github.com/kirill-grouchnikov/radiance/blob/master/docs/trident/TimelineLifecycle.md shows the intended reusal of a timeline - to play it forward or in reverse where it keeps on changing the same property of the same main object. Calling _play()_ is not a one-time thing that resets everything when it's done. 

There's a bit of undefined behavior with calling _addPropertyToInterpolate_ while the timeline is playing. Maybe that should only be allowed when the timeline is in _IDLE_ state.

**Comment by gregory-ledenev** [comment]
It is not clear that Timeline is a disposable resource that should NOT be reused until explicitly needed for replay, looping whatever. No clear mention in the docs. Timeline itself does not guide the users to use it properly. Moreover it does the opposite: there's no jerking when it is reused. I do understand it looks like a concatenation of a bugs that produces required result :(. I've tried to use it that way until tried it with two properties that immediately produced weird results. If those issues are undiscovered by the users - it produces leaking app with degrading performance if there lots of property changes.

I'm talking about common scenario, no fancy animation just straightforward change of one property (99.99% of use cases). So if reuse is reserved for advanced technics (yes, it does) it should prevent the users to go to those territory unless they realize and need this. 

The easiest way to achieve it - make timeline immutable by default. And state it clear in the documentation...

**Comment by kirill-grouchnikov** [comment]
This is an interesting idea that is worth exploring. Should a `Timeline` object be configured once and then become immutable just before playing it (forward / reverse / loop)? That is the intended usage of it, indeed.

The idea is that a timeline is configured to animate a configured property (or multiple properties) between two values, one time or on an ongoing basis. Reconfiguring the timeline after it's been used would be a weird mental model. 

Probably the most "Java" thing to do here is to introduce a `Timeline.Builder` pattern where you configure the various aspects of the timeline. Then, calling `build()` returns a semi-immutable timeline. You can't add properties, change duration or ease. But you can add callbacks to be notified on timeline events.

Such a change would be a breaking API change, and it's too late for the 2.0 timeframe. I'm going to mark this for the next release and update the title of this bug accordingly.

**Comment by gregory-ledenev** [comment]
Glad you see the problem and agree with my findings :). Though, going "builder" way is probably an over-complication. By default Timeline should be simply immutable. Introducing a constructor Timeline(boolean mutable) would be enough. 

Moreover, it will allow to discover wrong use of Timeline's. If you care about somewhat working apps that reuse Timeline's - you may print an error for any alteration attempts for the start.  Something like:

"Timeline is immutable. Future versions of Trident may throw an exception in this case". 

I've seen several similar messages printed by iOS SDK and by Java 11. So it is a good way to let the users know they do something wrong without breaking whatever kinda works for them for now.

P.S. probably it would be good to slightly change the API to allow fluid calls like (not a big deal though):

`new Timeline().interpolateProperty("current", 1, 100).play();`

**Comment by kirill-grouchnikov** [comment]
I think you want to take Trident API in a direction that I don't agree with. "Wrong use" is subjective. You expect a certain thing based on, perhaps, your experience with other animation libraries. That might not be the thing that Trident actually gives you.

**Comment by gregory-ledenev** [comment]
Everything on the Earth is subjective. Maybe I'm really do not understand the purpose of that framework after your past comments. Sorry, but now my impression is as follows:

1. Is it (Trident) trying to be "does everything" research project? **YES**
2. Does it allow doing very basic common animation without jerking? **NO** 
3. Does it allow to eliminate jerking by writing complex code? **NO**
4. Does it promote writing small, clean and well maintainable code? **Unexpected, but NO**
5. Does it assume that modern UI is built around components? **Unexpected, but NO**
6. Does it ready for real world use? **Unfortunately, NO**

I'm not trying to push you to any direction. I'm trying to make that thing working. 

Please let me know if you still interested in my contribution.

**Comment by kirill-grouchnikov** [comment]
At this point I don't have anything to contribute to this bug.
