### ISSUE TITLE
Timeline produces weird results when reused

### ISSUE THREAD

**Issue by gregory-ledenev** [kirill-grouchnikov/radiance#144]
### Version of OS

The issue is related to #143. 

Use of cached timelines to animate several properties produces weird results. For example, lets animate a “current” property first:

_Timeline cachedTimeline = new Timeline();
cachedTimeline.addPropertyToInterpolate(“current”, 1, 100);
cachedTimeline.play();_

Then lets animate the “color” property sometime when animation stopped:

_cachedTimeline.addPropertyToInterpolate(“color”, Color.red, Color.blue);
cachedTimeline.play();_

As a result the later animation produces simultaneous animation of both current(1-100) and color(red-blue) properties! That is unexpected. I know why it happens see #143. . Solution would be the same as for #143.

**Comment by kirill-grouchnikov** [comment]
The behavior you are describing is as designed. Timelines do not clear the list of properties to interpolate when they are "done". If you want to animate a different property, create a new _Timeline_ object for that.
