### ISSUE TITLE
[Trident] Expose threading model.

### ISSUE THREAD

**Issue by dyorgio** [kirill-grouchnikov/radiance#155]
### Sub-project (Trident)

Hi @kirill-grouchnikov, good job on theses libs :).
I use trident for a long time (since exploding pixel blog and very nice lib mac widgets).

Current thread model always did the job to my swing apps, but in my last project I faced a very specific necessity: control over animation threading model.

Today, we have PulseSource as the mechanism to control it, but in fact PulseSource is a "wait source", not who provides the "pulse" (TridentAnimationThread is the real pulse source).

My sugestion is to expose this mechanism and give to developers the posibillity to don't have any extra Thread (call updateTimelines directly).

The "problem" that I want to solve with this is run Trident calls and app calls in same Thread (mono-thread model).

Take a look to see what I need to do today to initialize:
```.java
// Use reflection to create and interrupt animatorThread.
Class<?> timelineEngineClass = Class.forName("org.pushingpixels.trident.TimelineEngine");
Method timelineEngineGetInstanceMethod = timelineEngineClass.getDeclaredMethod("getInstance");
timelineEngineGetInstanceMethod.setAccessible(true);
tridentTimelineEngineInstance = timelineEngineGetInstanceMethod.invoke(null);

Method timelineEngineGetAnimatorThreadMethod =  timelineEngineClass.getDeclaredMethod("getAnimatorThread");
timelineEngineGetAnimatorThreadMethod.setAccessible(true);
Thread timelineEngineAnimatorThread = (Thread) timelineEngineGetAnimatorThreadMethod.invoke(tridentTimelineEngineInstance);
timelineEngineAnimatorThread.interrupt();

Method timelineEngineUpdateTimelinesMethod = timelineEngineClass.getDeclaredMethod("updateTimelines");
timelineEngineUpdateTimelinesMethod.setAccessible(true);

MethodHandles.Lookup lookup = MethodHandles.lookup();
tridentUpdateTimelinesMethodHandle = lookup.unreflect(timelineEngineUpdateTimelinesMethod);
```

and to pulse:
```.java
//  Call updateTimelines (True "pulse")
tridentUpdateTimelinesMethodHandle.invoke(tridentTimelineEngineInstance);
```

**Comment by dyorgio** [comment]
I would  like to suggest to remove System.err call on souce too  :P

**Comment by kirill-grouchnikov** [comment]
I'm not the biggest fan of exposing such low-level details of Trident to the apps.

This may or may not be a case of [XY problem](https://en.wikipedia.org/wiki/XY_problem). What is it that you're after? What would be achieved by removing this specific thread? Your app will still run in a multithread environment - which has "core" JVM threads, a couple of AWT threads, a couple of Java2D threads etc.

**Comment by dyorgio** [comment]
"What would be achieved by removing this specific thread?"
A mono-thread model to run animations and other pieces of code on same thread (synced).

My desire is not to have less threads, is to change thread-model from background(Async) to foreground(Sync).

I'm developing a new toolkit, using some AWT classes, but with -Dheadless=true.

**Comment by kirill-grouchnikov** [comment]
I can almost guarantee that sooner or later, you'll find yourself writing a mechanism to offload heavy processing logic off of that mono-thread - especially if that thread is some kind of an equivalent of Swing's event dispatch thread or Android' main thread. 

Having said that, we can start by a pull request that would be the starting point to discuss how such extension point would work, and how much the internals of Trident would be exposed.

**Comment by dyorgio** [comment]
That is a nice good idea, I will fork it and try to expose/modify current Thread init logic.
Call getAnimatorThread(); on every method appears stranger to me...

**Comment by dyorgio** [comment]
Done @kirill-grouchnikov: https://github.com/kirill-grouchnikov/radiance/pull/157

**Comment by kirill-grouchnikov** [comment]
This is probably not going to happen. 

Over the years I've found myself narrowing down the scope of my various libraries. Trident started out with a rather ambitious feature set, providing out-of-box support for Swing, SWT and (very rudimentary) Android. Only Swing support has remained when Radiance unified all these libraries under one roof.

The explicit stated goal of Radiance is only Swing, and going forward I don't see this changing. There is some "flexibility" exposed by `TridentConfig`, but that is just noise. I will be removing everything related to `UIToolkitHandler` from there, explicitly only supporting the Swing threading model. That would also involve renaming `RunOnUIThread` to something like `RunOnEventDispatchThread`.

The internal implementation of spinning off a separate thread for updating the timelines is just that - internal implementation details. It is unlikely to change in the future given that Swing is pretty frozen in time, but exposing some kind of an API to run this inner update loop on an app-provided "scheduler" is not something I see myself providing in Radiance.

**Comment by dyorgio** [comment]
I understand your point @kirill-grouchnikov, I probabilly will create a new project very inspired in Trident (removing all UIToolkitHandler related stuffs and leave only interpolation classes), I always see this lib as a "generic tweening library", you know...trying to reuse existent code...

**Comment by dyorgio** [comment]
Oh, tks to take some time to apreciate my pull request :).
