### ISSUE TITLE
Heap memory widget text color with Twilight

### ISSUE THREAD

**Issue by Shatterhand** [kirill-grouchnikov/radiance#173]
### Version of Radiance (current development is 2.5-SNAPSHOT)
2.0.1

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Substance

### Version of Java (current minimum is 9)
jdk-11.0.2

### Version of OS
Windows

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
Texts are not always readable.
![image](https://user-images.githubusercontent.com/4527183/56079075-9a5f1400-5def-11e9-812f-3bfa46a26c20.png)
![image](https://user-images.githubusercontent.com/4527183/56079076-9e8b3180-5def-11e9-95ec-719f5503f996.png)

**Comment by kirill-grouchnikov** [comment]
Pretty much the only solution that would work with all skins would be to do "ghost" outlines of the text here. Marking for 2.5.

**Comment by Shatterhand** [comment]
> Pretty much the only solution that would work with all skins would be to do "ghost" outlines of the text here. Marking for 2.5.

That sounds cool, I would be interested in looking at previews.

**Comment by kirill-grouchnikov** [comment]
<img width="1126" alt="Screen Shot 2019-04-14 at 7 29 41 AM" src="https://user-images.githubusercontent.com/52874/56092225-22442d00-5e87-11e9-9779-0df710125b29.png">

**Comment by Shatterhand** [comment]
I think that doesnt look that good. Cant you just use different colors?

![image](https://user-images.githubusercontent.com/4527183/56094429-9d800000-5ed4-11e9-8b61-74c67a552134.png)

**Comment by kirill-grouchnikov** [comment]
These are the colors of the skin. I'm not saying this looks good, but it's quite likely that I'll be removing this widget altogether in 3.0 and leaving this to application to decide where to show it and how to style it.

**Comment by Shatterhand** [comment]
> These are the colors of the skin. I'm not saying this looks good, but it's quite likely that I'll be removing this widget altogether in 3.0 and leaving this to application to decide where to show it and how to style it.

The colors I used were picked from the screenshot so those are the colors of the skin too. 

By the way I noticed that in all other skins the color text of the heap widget is the same as the color text of the menus.

**Comment by kirill-grouchnikov** [comment]
This is not just about the text color. This is about three colors - the background fill, the chart fill and the text. Menus only have two of these (background + text).

If you happen to have a pull request for https://github.com/kirill-grouchnikov/radiance/blob/master/substance/src/main/java/org/pushingpixels/substance/internal/utils/SubstanceTitlePane.java (lines 215-278) that work across all core Substance skins with good contrast ratio for all three colors, I'll be glad to take a look.

**Comment by kirill-grouchnikov** [comment]
Also see https://github.com/kirill-grouchnikov/radiance/issues/176
