### ISSUE TITLE
[Substance] Remove SubstanceWidgetType.TITLE_PANE_HEAP_STATUS

### ISSUE THREAD

**Issue by kirill-grouchnikov** [kirill-grouchnikov/radiance#176]
This has outlived its narrow usefulness.

Substance has APIs to extend application content into the title pane, so there's no need to provide support for "special" kind of content that lives there. The heap status panel widget itself is not configurable and hasn't even been modernized to account for larger heaps (in GBs). And it's not even available as a standalone public component so that applications can place it elsewhere in their UI (such as the footer panel instead of the title pane).

All in all, this does not belong in Radiance anymore and will be removed in the next major update.

**Comment by Shatterhand** [comment]
Fair enough, thank you for your work on this project.
