### ISSUE TITLE
Wrong cursor position while typing in JTextField

### ISSUE THREAD

**Issue by PirolA** [kirill-grouchnikov/radiance#178]
### Version of OS: Windows 10 (1809)

When we migrated to Java 11 with Radiance 2.0.1, we noticed a problem with the cursor. If you type 'mmmm' into the text field (JTextField), the cursor will move away.
When debugging, we found that the font metrics are calculated incorrectly. In the following code you can also reproduce the problem under Windows with 100% scaling. Without Radiance is calculated for the 'm' with the metric 10. If you activate Radiance, the 11 is calculated so that the CURSOR is positioned 1 pixel incorrectly.

The issue also occurs in Radiance 1.0.2

[CursorPosition.txt](https://github.com/kirill-grouchnikov/radiance/files/3130637/CursorPosition.txt)

**Comment by kirill-grouchnikov** [comment]
There was something similar reported a while back, and I've added an entry at the end of https://github.com/kirill-grouchnikov/radiance/blob/master/docs/substance/faq.md. Can you check this case running with "-Dawt.useSystemAAFontSettings=off" VM flag?

**Comment by PirolA** [comment]
Thanks

**Comment by kirill-grouchnikov** [comment]
If that indeed fixes the issue, I would highly suggest filing a bug on https://bugreport.java.com/bugreport/

Running under that system property essentially disables desktop-consistent text rendering, and might result in a UI that doesn't look consistent in that area.

**Comment by kirill-grouchnikov** [comment]
See discussion at https://github.com/kirill-grouchnikov/radiance/issues/179 and try the latest 2.5-SNAPSHOT builds (without the flag above).

**Comment by DanielWebelsiep** [comment]
I could verify the bugfix and also #179 with java 11 on windows 10 with Radiance 2.5-SNAPSHOT. I had to change the standard font to Sansserif under Window to support our Unicode test String.
"mmm Text ß€äüöÄÜÖ čšžČŠŽ Пасха это は区理知の 😉 😊 😋 😎 AA"
