### ISSUE TITLE
[Substance] JInternalFrame's title are not visible

### ISSUE THREAD

**Issue by haroflow** [kirill-grouchnikov/radiance#182]
### Version of Radiance (current development is 2.5-SNAPSHOT)
org.pushing-pixels:radiance-substance:2.0.1
### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Substance
### Version of Java (current minimum is 9)
JDK 11.0.1, tried with 12, with openjdk 11, no success.
### Version of OS
Linux Mint 19 Cinnamon

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
JInternalFrame's title are not showing up, is there any tricks to it? When I hover the mouse on the titlebar I get the tooltip with the right title. Tried other skins, didn't work either.

![image](https://user-images.githubusercontent.com/4776931/59151307-3af43d80-8a07-11e9-9b37-d4e3f255164d.png)

```
        JFrame.setDefaultLookAndFeelDecorated(true);
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(new SubstanceNebulaLookAndFeel());
            } catch (Exception e) {
                System.out.println("Substance Graphite failed to initialize");
            }

            JFrame frame = new JFrame("Main Window");
            frame.setSize(500, 500);
            frame.setVisible(true);

            JDesktopPane desk = new JDesktopPane();
            frame.getContentPane().add(desk);

            JInternalFrame intFrame = new JInternalFrame("New Internal Frame");
            intFrame.setSize(200, 200);
            intFrame.setVisible(true);
            intFrame.setClosable(true);
            intFrame.setResizable(true);
            desk.add(intFrame);
        });
```

**Comment by kirill-grouchnikov** [comment]
Something's wrong with the logic in `SubstanceTitlePaneUtilities.getTitlePaneTextRectangle`. Will look into this.

**Comment by kirill-grouchnikov** [comment]
<img width="936" alt="image" src="https://user-images.githubusercontent.com/52874/59152002-3aa97180-8a0a-11e9-8ef3-1489a767e40c.png">

The frame is not configured to be maximizable or iconifiable, so those two actions do not create control buttons. Or rather, the buttons are there and set to 0x0 size and still visible, instead of being marked as invisible.

**Comment by haroflow** [comment]
Adding maximizable and iconifiable solved it for me. Should I close this issue? Feel free to close if you want.

Thank you very much!

**Comment by kirill-grouchnikov** [comment]
This still needs a proper fix

**Comment by haroflow** [comment]
Sorry, I clicked on "Close and comment" and went with it =P
