### ISSUE TITLE
JDK 9 Alternative?

### ISSUE THREAD

**Issue by maxbaird** [kirill-grouchnikov/radiance#183]
Hi, in the getting started instructions for Substance it is stated that JDK 9 is required and there is a link provided from which it can be downloaded. I don't see JDK 9 being offered at that URL and was wondering if any other JDK version is compatible. Thanks.

**Comment by kirill-grouchnikov** [comment]
I'll tweak the documentation to say that JDK 9 is the minimum required, and any other version of JDK after that is good too. As for the download itself, it is accessible from that page if you scroll all the way to the end and click the "Download" button next to "Java archive"

**Comment by maxbaird** [comment]
Great, this clears things up! Now I'm kind of back to my original problem :-)
I currently have the following version of the JDK:
```
$ java -version
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```
But when I try building with Gradle it fails with an error message indicating that it expects
java 1.9 but I'm using 12. The output is below:
```
$ ./gradlew
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :neon:compileJava FAILED
> Task :trident:compileJava FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/radiance/build.gradle' line: 79

* What went wrong:
Execution failed for task ':neon:compileJava'.
> Compiler version mismatch; required is 1.9, but using 12

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Build file '/home/radiance/build.gradle' line: 79

* What went wrong:
Execution failed for task ':trident:compileJava'.
> Compiler version mismatch; required is 1.9, but using 12

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
2 actionable tasks: 2 executed
```
My gradle version is as follows:
```
$ gradle -version

------------------------------------------------------------
Gradle 4.3.1
------------------------------------------------------------

Build time:   2019-04-10 15:28:34 UTC
Revision:     cf54ebed0aba1cb0f69ef6a717e4b37376c99869

Groovy:       2.4.8
Ant:          Apache Ant(TM) version 1.10.5 compiled on August 21 2018
JVM:          1.8.0_212 (Oracle Corporation 25.212-b04)
OS:           Linux 5.0.16-100.fc28.x86_64 amd64
```

**Comment by kirill-grouchnikov** [comment]
Right. It expects exactly 9 to build, and anything that is 9 or above to run.

I'll update the docs

**Comment by kirill-grouchnikov** [comment]
Updated:

https://github.com/kirill-grouchnikov/radiance/blob/master/README.md
https://github.com/kirill-grouchnikov/radiance/blob/master/docs/building.md
https://github.com/kirill-grouchnikov/radiance/blob/master/docs/substance/getting-started.md
