### ISSUE TITLE
Dynamically set the SVG icon for the Command component

### ISSUE THREAD

**Issue by fangyuzhong2016** [kirill-grouchnikov/radiance#186]
### Version of OS   Windows 10
![image](https://user-images.githubusercontent.com/16973729/61211561-800c3d80-a732-11e9-94e9-d09f28e7aead.png)

Hello, I am using the dynamically generated Command component. When setting the Command icon, only the setIconFactory() method, the icon factory class Factory is generated in advance, but I want to dynamically set the Command icon SVG externally, which one of the Commands needs to be called. method? Or does Command not support dynamic setting of external SVG icons? Thank you

**Comment by kirill-grouchnikov** [comment]
There's a Command.setIconFactory API. That can be called at runtime to change the icon factory used for the specific command.
