### ISSUE TITLE
JTabbedPane related issues set at the bottom

### ISSUE THREAD

**Issue by fangyuzhong2016** [kirill-grouchnikov/radiance#187]
### Version of Java (current minimum is 9)

I am using JTabbedPane, when I set the JTabbedPane to the bottom, JTabbedPane.setTabPlacement(3); 
After selecting a JPanel. The selected JPanel text is incomplete.
How to solve this? Thank you!
![image](https://user-images.githubusercontent.com/16973729/61572295-ba2c6500-aacd-11e9-9417-714b9a679193.png)

**Comment by kirill-grouchnikov** [comment]
Please fill all the requested information - OS version, Java version, Radiance version.

**Comment by fangyuzhong2016** [comment]
OS version  Windows 10
 Java version  Oracle JDK 9
Radiance version.：  2.5-SNAPSHOT

**Comment by fangyuzhong2016** [comment]
> Please fill all the requested information - OS version, Java version, Radiance version.

OS version Windows 10
Java version Oracle JDK 9
Radiance version.： 2.5-SNAPSHOT

**Comment by kirill-grouchnikov** [comment]
Thanks!

**Comment by kirill-grouchnikov** [comment]
Seeing the same on a Mac as well.
