### ISSUE TITLE
[Radiance] Move to Java 9 for compile / runtime

### ISSUE THREAD

**Issue by kirill-grouchnikov** [kirill-grouchnikov/radiance#2]
Tracker for moving from Java 8 to Java 9

- Move to Java modules, hiding .internal to not be exposed to app code
- Use https://docs.oracle.com/javase/9/docs/api/java/lang/Runtime.Version.html for version-specific logic (don't parse java.specification.version anymore)
- Remove old / reflection logic in UiUtil for querying hi-dpi state of graphics device

Tentatively tracking for 2019.H1 releases - need to see how it goes with Java 10 / 11 releases.

**Comment by otros-systems** [comment]
Hi @kirill-grouchnikov 
Which Java version are you going to support? Users of my project are using Java 8 (like 98%).

**Comment by kirill-grouchnikov** [comment]
The question is not clear. The planned timeline for switching to Java 9 is 2019, by which time Java 12 or 13 will be out. I'm not going to lag that far behind the platform releases.

**Comment by utybo** [comment]
Does this mean Radiance will not be available for Java 8?

**Comment by kirill-grouchnikov** [comment]
Starting from next year, highly likely

**Comment by brunchboy** [comment]
At least there will be one version that works in Java 8+, which is all I need in order to be able to release my version of Beat Link Trigger which is compatible with Java 8, 9, and 10.

**Comment by kirill-grouchnikov** [comment]
The current plan is to continue doing two releases a year, one for H1 and one for H2. Without committing to anything specific, the H1 releases will be .5, and H2 will be .0 with breaking API changes.

H2 releases will also be accompanied by bumping up the Java dependencies as relevant. The underlying platform is on a much faster update cadence, with two platform releases every year. So it's likely that 2019.H2 release will be on Java 9, 2020.H2 will be on Java 11 etc.

**Comment by brunchboy** [comment]
That makes sense. I’ll probably stay on 1.0 for a long time, since my needs are so minimal and specific.

**Comment by utybo** [comment]
It should also be noted that Java 8 support (more specifically publicly available commercial-use updates for the Java 8 JDK) will be dropped by Oracle after January 2019, as you can see on [this page](https://www.oracle.com/technetwork/java/javase/overview/index.html)

> Oracle will not post further updates of Java SE 8 to its public download sites for commercial use after January 2019. Customers who need continued access to critical bug fixes and security fixes as well as general maintenance for Java SE 8 or previous versions can get long term support through Oracle Java SE Subscription or Oracle Java SE Desktop Subscription. For more information, and details on how to receive longer term support for Oracle JDK 8, please see the Oracle Java SE Support Roadmap.

(Weirdly enough, Oracle doesn't provide Java 9 or Java 10 downloads on the consumer website java.com, but I assume that the website will be updated in January)

**Comment by brunchboy** [comment]
Yes, I’m painfully aware of that, which is why I am releasing Java 9 and later support for Beat Link Trigger. Most of my users are not going to care, and will stay on Java 8 indefinitely, and are often not connected to the Internet, but I want new users to be able to use newer Java versions.

**Comment by kirill-grouchnikov** [comment]
2019.H1 release will be 2.0. While I just marked this issue for 2.5 which is 2019.H2, the switch to Java 9 will probably be happening in the current development branch which is 2.0 now.

**Comment by kirill-grouchnikov** [comment]
There's going to be some cleanup work involved into moving away from using APIs that have been marked as deprecated in Java 9. Not sure yet how much work it would be to move to Java 9 modules. https://blog.joda.org/2018/03/jpms-negative-benefits.html is an interesting read. Gradle also has this notion of api vs implementation dependency - not sure yet if that's worth investigating.

**Comment by kirill-grouchnikov** [comment]
Future modularization work (if any) will be tracked separately.
