### ISSUE TITLE
wrong icon position in LookIn directoryComboBox of FileChooser on Linux/MacOS

### ISSUE THREAD

**Issue by goodwilling** [kirill-grouchnikov/radiance#206]
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
The icon position is wrong in the "look in" directoryCombobox of file chooser.  
 
![icon-position](https://user-images.githubusercontent.com/56999195/67563579-f4a43e80-f75b-11e9-9ecd-412c4e816ffb.PNG)

**Comment by kirill-grouchnikov** [comment]
Confirmed that this is happening in 3.0-SNAPSHOT
