### ISSUE TITLE
[Substance] Slow response for column selection on massive-data JTable

### ISSUE THREAD

**Issue by goodwilling** [kirill-grouchnikov/radiance#207]
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
The mouse response becomes very slow when switching between columns of a JTable that has more than 50000 rows. The response is normal if using the Windows or metal look and feel.

**Comment by kirill-grouchnikov** [comment]
I can't reproduce this in the test app. SubstanceTableUI has special case for large tables - when there's more than 500 cells, all animations are disabled.

Would it be possible to get a small, standalone and complete class that reproduces what you're seeing under the latest 3.0-SNAPSHOT?

**Comment by kirill-grouchnikov** [comment]
Missed the column selection part. I see that it is indeed slow.
