### ISSUE TITLE
[Substance] Fix visuals of some components under very large font sizes

### ISSUE THREAD

**Issue by goodwilling** [kirill-grouchnikov/radiance#209]
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
The substance Look and Feel is beautiful and excellent for Swing applications with font size larger than the default. However, there are some problems in color chooser and trees. 

(1) color chooser: the panel size does not become larger when font size is increased, thus some labels can not be fully displayed. 

(2) JTree: the icon of the node can not be fully displayed beyond some font sizes. Furthermore, mouse listener does not work when clicking 
![font_and_icon_size](https://user-images.githubusercontent.com/56999195/67952592-dee9ba00-fc30-11e9-9e3d-29eb795b9b4b.PNG)
the right upper corner of the icon.

**Comment by kirill-grouchnikov** [comment]
The [implementation](https://github.com/kirill-grouchnikov/radiance/blob/master/substance/src/main/java/org/pushingpixels/substance/internal/contrib/xoetrope/editor/color/ColorWheelPanel.java) of this color chooser panel was contributed long time ago, and it's using fixed bounds for pretty much all the controls. It would be a rather big endeavor to figure out how to scale this layout to arbitrarily large font sizes and still make it usable. For this particular case I'd suggest using `SubstanceCortex.GlobalScope.setUseDefaultColorChooser()` API to revert to the core visuals of color chooser if you need your application to run under very large font sizes.

The tree visuals look different for me under the latest 3.0-SNAPSHOT. The icon is a bit shifted to the left and cut off at the top level of the tree. I'll take a look at that a bit later.

**Comment by kirill-grouchnikov** [comment]
Also need to fix:

1. Horizontal padding and margins of title pane content
2. Option pane icon size
3. Cut off slider thumbs
