### ISSUE TITLE
[Flamingo] Hook on task selection / tab selection

### ISSUE THREAD

**Issue by hannespernpeintner** [kirill-grouchnikov/radiance#211]
Thank you for your nice libs!!

### Version of Radiance (current development is 3.0-SNAPSHOT)
2.5.1

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Flamingo

### Version of Java (current minimum is 9)
jdk-11.0.4+11

### Version of OS
Ubuntu 18.04

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
As mentioned in my first issue here, https://github.com/kirill-grouchnikov/radiance/issues/210 , I am currently developing a game engine editor with a flamingo based ribbon bar. I have a viewport in the BorderLayout.CENTER area that I would like to change when I select certain tasks, or tabs, as you wish. Is there any hook I could use?

I would have expected something in the lines of

```
val textureTask = RibbonTask("Texture", textureBand).onSelect {
  mainPanel.switchContent()
}
addTask(textureTask)
```
 
Did I overlook sth here, is this possible? I already guess that there is some...I don't know Swing component base stuff I don't know with my limited experience in GUI stuff, but I think an official entry point in the task api would be nice, what do you think? :)

**Comment by kirill-grouchnikov** [comment]
Right now you can do this with a `PropertyChangeListener` registered on the `JRibbon` to listen to the "selectedTask" property. The values for old and new will be `RibbonTask`.

This is not something that is officially supported as part of the API. I've never liked those string-based property changes. That's why [Torch's wrappers](https://github.com/kirill-grouchnikov/radiance/blob/master/docs/kotlin-ext/torch/torch.md) are driven by Kotlin properties and not class field name strings.

Let me figure out where such an official API belongs in both Flamingo and Plasma.

**Comment by kirill-grouchnikov** [comment]
The usage of the task selection listener API in Java will be:

```java
this.getRibbon().addOnTaskSelectionChangedListener((RibbonTask task) ->
      System.out.println("Task [" + task.getTitle() + "] is selected"));
```

and for Kotlin:

```kotlin
onTaskSelectionChange = { task -> println("Task [${task.title}] selected") }
```

I'd rather not expose in on the `RibbonTask` itself. If you think it's cleaner for your use case to track it at the task level, it can probably be achieved with extension functions on `RibbonTask` and registering a selection change listener on the `JRibbon` to redirect the event there.

Also, I would want to point out that changing the main application content as the result of changing task selection in the ribbon is a bit against what the ribbon is "supposed" to be - a flexible container for actions that can be performed on that content. Other actions (like opening a new piece of content, for example) are probably best placed in the application menu instead.

**Comment by hannespernpeintner** [comment]
Thanks, would be completely fine, everyone can work with that.

Yea, you're right, I am uncertain about what I do as well. I think I will not change main panel content on tab selection, but I maybe enable/disable certain controls.

Can be closed then :)

**Comment by kirill-grouchnikov** [comment]
Enabled status of a command should in general depend on the currently selected element. But perhaps there are scenarios where you have other elements in the UI (side panels?) that need to be kept in sync with ribbon task selection. I'd just say - avoid or at least minimize surprises.
