### ISSUE TITLE
[Flamingo] prevents KeyListeners from working

### ISSUE THREAD

**Issue by hannespernpeintner** [kirill-grouchnikov/radiance#212]
### Version of Radiance (current development is 3.0-SNAPSHOT)
2.5.1

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Flamingo

### Version of Java (current minimum is 9)
11.sth

### Version of OS
Ubuntu 18.04

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
I use flamingo with another panel in the BorderLayout.CENTER location and i need key input there, that's why i added a key listener to its content. In my ribbon frame constructor i set this focusable and everything works nicely. As soon as i click on anything in the ribbon bar, the key listener stops working. My impression is that the bar somehow overrides key input for other components.

Is there another recommended way to have key inputs in non-ribbon components? Mouse listeners keep working.

Thanks :)

**Comment by kirill-grouchnikov** [comment]
The ribbon listens to all key events for [keyboard traversal](https://github.com/kirill-grouchnikov/radiance/blob/master/docs/flamingo/KeyboardTraversal.md) and [keytips](https://github.com/kirill-grouchnikov/radiance/blob/master/docs/flamingo/RibbonKeytips.md)

Are you using one of those keyboard combinations for your listener by any chance? If not, can you paste a snippet on how you're configuring that panel key input?

**Comment by hannespernpeintner** [comment]
Hm, no none of them, i only use wasdqe and shift, it's controling a virtual camera. Currently i am on my phone, i will post a snippet as soon as i can, or a small reproducable project.

Sidenote, i am getting NPE if i want to show the keytips, i don't know if those two problems are related, i will probably create a new issue for that one with stacktraces etc. :)

**Comment by kirill-grouchnikov** [comment]
Would be great to get that stacktrace along with description of the steps as a separate issue.

**Comment by hannespernpeintner** [comment]
Done :)

Regarding this issue here, I can say that the controls are still working even after I clicked on the ribbon bar on an empty space. As soon as I click a task oder some command content or anything inside the bar, my other listener doesn't trigger any more.

**Comment by kirill-grouchnikov** [comment]
Did you mean to paste a snippet on how you configure your key listener for this bug?

**Comment by hannespernpeintner** [comment]
I made a self contained example here https://github.com/hannespernpeintner/flamingo-issue-212-reproduction

Readme included. If anything is left unclear, let me know :)

**Comment by kirill-grouchnikov** [comment]
Thanks, will take a look.

**Comment by kirill-grouchnikov** [comment]
```kotlin
    val mainPanel = JPanel().apply {
        setLayout(BorderLayout())
        add(JButton("abc"), BorderLayout.SOUTH)
        this@RibbonEditor.add(this, BorderLayout.CENTER)
    }
```

and remove the `imageLabel`.

Now, after clicking that regular `JButton`, your key listener is not being called anymore either. I don't have a lot of experience with key-based actions, so I'm not sure what's the right way to accomplish such a global listener besides [this](https://docs.oracle.com/javase/7/docs/api/java/awt/Toolkit.html#addAWTEventListener(java.awt.event.AWTEventListener,%20long)) 

Here's an example that doesn't involve Substance or Flamingo:

```java
fun main() {
    SwingUtilities.invokeLater {
        UIManager.setLookAndFeel(MetalLookAndFeel())
        val frame = JFrame()
        frame.layout = BorderLayout()

        val panel = JPanel()
        panel.layout = BorderLayout()
        frame.contentPane = panel

        panel.isFocusable = true
        panel.focusTraversalKeysEnabled = false
        panel.addKeyListener(KeyLogger())

        panel.add(JButton("abc"), BorderLayout.SOUTH)

        frame.size = Dimension(500, 400)
        frame.setLocationRelativeTo(null)
        frame.defaultCloseOperation = WindowConstants.DISPOSE_ON_CLOSE
        frame.isVisible = true
    }
}
```

The key logger "works" until you click that button. From that point, the key events are only delivered to the focus owner.
