### ISSUE TITLE
[Substance] StackOverflowError when clicking a specific JTable

### ISSUE THREAD

**Issue by goodwilling** [kirill-grouchnikov/radiance#219]
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
When clicking a specific JTable (with cells using editable combox), the following errors come out:

Exception in thread "AWT-EventQueue-0" java.lang.StackOverflowError
 at org.pushingpixels.substance.internal.utils.SubstanceCoreUtilities.getTextComponentForTransitions(SubstanceCoreUtilities.java:1885)
 at org.pushingpixels.substance.internal.utils.SubstanceColorUtilities.getBackgroundFillColor(SubstanceColorUtilities.java:667)
...
 
Such error does not occur in native look and feels. By the way, I have tried the source code (commited on Nov. 06) ,  compiled in Java 8 with some minor modifiecations, and got the same result. In order to get ride of the error, I also tried to remove the relative functionality:

substance/src/main/java/org/pushingpixels/substance/internal/utils/SubstanceCoreUtilities.java:

    public static JTextComponent getTextComponentForTransitions(Component c) {
        if (!(c instanceof JComponent))
            return null;
        TextComponentAware tcaui = null;
      //  TextComponentAware tcaui = (TextComponentAware) ((JComponent) c)
      //          .getClientProperty(TEXT_COMPONENT_AWARE);
        if (tcaui != null) {
            return tcaui.getTextComponent(c);
        }
        if (c instanceof JTextComponent) {
            return (JTextComponent) c;
        }
        return null;
    }

This seems to eliminate the error, however, I wonder if this modification has some side effects.

**Comment by kirill-grouchnikov** [comment]
Would you happen to have a reproducible case that shows that stack so I can debug it?

**Comment by goodwilling** [comment]
Sorry, we have found the reason of this problem in our program: 

   the combox editor is not editable, but the combox is set as editable, 

as in the source code: 

           ....
           TableColumn column = table.getColumnModel().getColumn(index);
           JComboBox  combo = new JComboBox(list_of_string);
           TheComboBoxEditor editor = new TheComboBoxEditor();
           combo.setEditor(editor);
           combo.setEditable(true);
           column.setCellEditor(new DefaultCellEditor(combo));
           ...

    class TheComboBoxEditor extends BasicComboBoxEditor {

        public TheComboBoxEditor() {
           editor.setEditable(false);
       }
    }

The problem is solved by remove the setting (editable) on the combo. By the way, in native look and feel, the combox is just treated as non-editable.
Thank you for your attention.

**Comment by kirill-grouchnikov** [comment]
I can reproduce this in 3.0-SNAPSHOT. Will fix.
