### ISSUE TITLE
[Substance] Memory leak in RootPaneDefaultButtonTracker

### ISSUE THREAD

**Issue by stefan-reich** [kirill-grouchnikov/radiance#22]
### Version of Radiance

current

### Sub-project (Trident, Substance, Flamingo, ...)

Trident/Substance

### Version of Java

any

### Version of OS

any

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

The memory leak reported [here](https://github.com/kirill-grouchnikov/substance/issues/4) is real.

It happens because RootPaneDefaultButtonTracker.timeline.mainObject is also the JButton.

[Screenshot.](http://ai1.space/1004590/raw/1101320)

**Comment by kirill-grouchnikov** [comment]
I'll need to see a small standalone test app that shows this memory leak after a JOptionPane has been dismissed.

**Comment by stefan-reich** [comment]
[Sure.](http://tinybrain.de/1016301)

Same result in VisualVM as before (JButtons "Yes", "No", "Cancel" retained after GC).

**Comment by kirill-grouchnikov** [comment]
Emphasis on standalone. I can't do anything with that sample.

**Comment by kirill-grouchnikov** [comment]
I can only look at pure Swing samples. Otherwise it's not clear if JOptionPane is being considered a valid strong reference.

Without a standalone pure Swing sample there's going to be no traction on this report.

**Comment by kirill-grouchnikov** [comment]
Looking at [the historical snapshot](https://github.com/kirill-grouchnikov/substance/blob/58d3873e7b2d57b110231dc867be8220ff02801a/src/org/pushingpixels/substance/internal/utils/ButtonBackgroundDelegate.java) of the pre-hiatus Substance, the pulsating of the default button has been effectively a visual no-op, as the value of `cyclePos` in line 126 is ignored afterwards. This is the same in the [latest iteration](https://github.com/kirill-grouchnikov/radiance/blob/master/substance/src/main/java/org/pushingpixels/substance/internal/utils/ButtonBackgroundDelegate.java) of that class in line 107.

So given that this has been not doing anything in at least 8 years (java.net history is gone), I'm just going to remove the whole tracking of default buttons.

**Comment by kirill-grouchnikov** [comment]
Note that [ComponentState](https://github.com/kirill-grouchnikov/radiance/blob/master/substance/src/main/java/org/pushingpixels/substance/api/ComponentState.java) still has states for default and disabled default buttons, and skins can use those to provide distinctive visuals to such buttons.
