### ISSUE TITLE
Focus problem of rows when leaving JTable 

### ISSUE THREAD

**Issue by goodwilling** [kirill-grouchnikov/radiance#223]
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
As previously reported, when switching from a column of a JTable to a nearby Jbutton, focus on the column is not lost sometimes, although the column is not selected.

This phenomenon can now be reproduced on a JTable for selecting rows. In my case, the following codes in my program is responsible for the focus problem of the JTable: 

            if(UIManager.getLookAndFeel() instanceof SubstanceLookAndFeel) {
               SubstanceCortex.ComponentScope.disallowAnimations(jtable, AnimationFacet.ROLLOVER);
               SubstanceCortex.ComponentScope.disallowAnimations(jtable, AnimationFacet.SELECTION);
            }

When the above codes are removed, the focus problem of row selection disappears. However, these codes are not used in other cases where the focus prolems appear for the column selection.

**Comment by kirill-grouchnikov** [comment]
As I said in the original issue, I need more information. Right now Substance uses the highlight painter for both focused and selected content in tables. There's a faint border outline for the focused cell, and that outline is the focus indication.

In the main test app, transferring focus out of the table removes the focus outline from the table, and the selection highlight remains - as expected.

I will need to see a small, complete and standalone sample that shows the problem you're experiencing under the latest 3.0-SNAPSHOT bits, along with the specific sequence of interactions (mouse, keyboard). Without that, I can't help here.

**Comment by kirill-grouchnikov** [comment]
Closing this again since there's not enough information to act on. If you open another issue, I will need to see a small, complete and standalone sample that shows the problem you're experiencing under the latest 3.0-SNAPSHOT bits, along with the specific sequence of interactions (mouse, keyboard).

**Comment by kirill-grouchnikov** [comment]
See https://github.com/kirill-grouchnikov/radiance/issues/236
