### ISSUE TITLE
[Substance] JTable renderer leaves the row highlighted by the rollover color

### ISSUE THREAD

**Issue by ondrusm** [kirill-grouchnikov/radiance#236]
### Version of Radiance (current development is 3.0-SNAPSHOT)
3.0
### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Substance
### Version of Java (current minimum is 9)
13
### Version of OS
Windows 7
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
If the table has **animation turned off**, then the last row (where mouse left the table) remains highlighted (with rollover color). The table uses SubstanceDefaultTableCellRenderer.

Animation is turned off by code:
SubstanceCortex.ComponentScope.disallowAnimations(getJTable(), SubstanceSlices.AnimationFacet.ROLLOVER);
SubstanceCortex.ComponentScope.disallowAnimations(getJTable(),SubstanceSlices.AnimationFacet.SELECTION);

If the table has **animation turned on**, then after mouse left table, rollover effect disappear.
But, if mouse enters last row (where left table), rollover effect does not appear.

**Comment by kirill-grouchnikov** [comment]
This is `SubstanceTableUI.RolloverFadeListener.mouseExited` not cleaning up after itself by not resetting all the tracker indices. It needs to reset `rolledOverRow`, `lastRow` and `lastColumn`, as well as trigger the table repaint if there are no rollover animations. Will add a fix soon.
