### ISSUE TITLE
ClassNotFoundException: org.pushingpixels.photon.transcoder.SvgBatchConverter

### ISSUE THREAD

**Issue by leolr02** [kirill-grouchnikov/radiance#237]
### Version of OS: Windows 8.1 pro

Hi, I have a problem when I try to convert my svg icons with a photon command, I run the command in the current project path where I will generate the different Java clases. 
My command is the next: 
![command](https://user-images.githubusercontent.com/12399038/73296415-4cc16580-41cf-11ea-890a-4fd3953b1086.PNG)

I already download all necesary libraries (photon 2.5.1, batik-all-1.12, xml-apis-1.4.01, xml-apis-ext-1.3.04, xmlgraphics-commons-2.4), in the specific paths that the command shows, outside my Java swing project, but Im not able to convert my svg files, I need to do another thing?

**Comment by kirill-grouchnikov** [comment]
You'll need the dependency versions that matched Photon at 2.5.1

Take a look at https://github.com/kirill-grouchnikov/radiance/blob/205e52e22d3248724adcbbf3ca9fd5ca3439be18/scripts/convert-svg.sh

Also make sure that all the jars you're referencing actually exist on your machine in those locations (after running "gradlew copyJars" and "gradlew getAllDependencies").

**Comment by kirill-grouchnikov** [comment]
It's been a while since I worked on Windows in command line, but maybe it's also choosing the right slash - \ vs / for folder paths.

**Comment by leolr02** [comment]
I have all dependencies in the specific paths,  i don't have gradle installed, is necessary install it for the command? I'm newby using gradle.
The jars I downloaded manually. :(

**Comment by kirill-grouchnikov** [comment]
Steps:

- Download 2.5.1 distribution from https://github.com/kirill-grouchnikov/radiance/archive/v2.5.1.zip
- Run "./gradlew" from the top-level folder of the unzipped content. This will download the gradle binaries, all the dependencies, and will compile everything
- Run "./gradlew copyJars". This will copy Radiance jars to the "drop/..." folders
- Run "./gradlew getAllDependencies". This will copy Radiance dependencies to the "build/..." folders
- Run "mkdir test"
- Run "cp drop/2.5.1/core/radiance-photon-2.5.1.jar test" to copy the main Photon jar into that new folder
- Run "cp build/libs-core/batik-all-1.11.jar test" to copy the main Batik jar into that folder
- Run "cp build/libs-core/xml-apis-1.3.04.jar test" to copy XML APIs jar
- Run "cp build/libs-core/xml-apis-ext-1.3.04.jar test" to copy XML API ext jars
- Run "cp build/libs-core/xmlgraphics-commons-2.3.jar test" to copy XML graphics commons jar
- Run "java -cp ./radiance-photon-2.5.1.jar:./batik-all-1.11.jar:./xml-apis-1.3.04.jar:./xml-apis-ext-1.3.04.jar:./xmlgraphics-commons-2.3.jar org.pushingpixels.photon.transcoder.SvgBatchConverter sourceFolder=~/Downloads outputPackageName=org.test templateFile=/org/pushingpixels/photon/transcoder/java/SvgTranscoderTemplateResizable.templ outputLanguage=java
"

Important note - the jar versions that are needed for Photon 2.5.1 are different from those needed for Photon 3.0-SNAPSHOT (that you've downloaded). The location of the "sourceFolder" in the last command will depend on where your SVG files are

**Comment by leolr02** [comment]
I run the command gradlew, but I need the java 1.9 version :( 

![image](https://user-images.githubusercontent.com/12399038/73310214-75eeef80-41e9-11ea-833e-b6d4c570cc83.png)

**Comment by kirill-grouchnikov** [comment]
https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase9-3934878.html

**Comment by leolr02** [comment]
### It works! 
Thank you

**Comment by kirill-grouchnikov** [comment]
https://github.com/kirill-grouchnikov/radiance/blob/master/docs/photon/photon.md#dependency-versions-for-photon
