### ISSUE TITLE
[Photon / Ignite] Batch converter for nested content

### ISSUE THREAD

**Issue by kirill-grouchnikov** [kirill-grouchnikov/radiance#251]
Following the initial discussion at https://github.com/kirill-grouchnikov/radiance/pull/248

It is useful to provide support for transcoding SVG content to Java / Kotlin classes for more complex folder structure and not just one flat folder. For example, if the source folder has SVGs in nested subfolders, the output classes will match not just the source filenames, but will also be placed in the matching folder (sub)structure.

Instead of `sourceFolder` parameter, it will be `sourceRootFolder`. And instead of `outputPackageName` it will be `outputRootPackageName`. Then, starting from those roots, the destination folders will follow the source folder structure, and the package name for each transcoded class will be built from the root package name + the folder structure.

I'd like to not overcomplicate the existing `SvgBatchConverter` logic, but rather have it in a new `SvgBatchNestedConverter`.

**Comment by simon04** [comment]
Here's my branch for the recursive transcoding: https://github.com/simon04/radiance/tree/recursive

**Comment by kirill-grouchnikov** [comment]
Also need to expose this in Ignite to keep the functionality parity

**Comment by kirill-grouchnikov** [comment]
This still needs documentation and switching some of the usage in `scripts/convert-svg.sh` to get regular usage out of it.

**Comment by kirill-grouchnikov** [comment]
https://github.com/kirill-grouchnikov/radiance/blob/master/docs/photon/photon.md and https://github.com/kirill-grouchnikov/radiance/blob/master/docs/tools/ignite/ignite.md have been updated
