### ISSUE TITLE
[Substance] Change Window Titlebar color

### ISSUE THREAD

**Issue by leolr02** [kirill-grouchnikov/radiance#262]
### Version of OS Windows 8.1 Pro

![image](https://user-images.githubusercontent.com/12399038/78627493-2cf59000-7857-11ea-9f48-00ec079612a5.png)

Is possible change the color of the window title bar?, I've search on documentation but, nothing mention about it.
Regards.

**Comment by kirill-grouchnikov** [comment]
See https://github.com/kirill-grouchnikov/radiance/blob/master/docs/substance/painters/decoration.md

`DecorationAreaType.PRIMARY_TITLE_PANE` and `DecorationAreaType.SECONDARY_TITLE_PANE` can be used to configure your custom skin. These are used in pretty much all Substance skins to configure the visuals of that area. See https://github.com/kirill-grouchnikov/radiance/blob/master/substance/src/main/java/org/pushingpixels/substance/api/skin/BusinessBlackSteelSkin.java#L84 for the block that defines the visuals of the Business Black Steel skin, for example.

**Comment by leolr02** [comment]
You're awesome!. Thanks for your great job!.  

![image](https://user-images.githubusercontent.com/12399038/78731536-9df38100-7905-11ea-8d3d-ee1bcedf4862.png)
