### ISSUE TITLE
[Substance] Maximizing JFrame doesn't work right

### ISSUE THREAD

**Issue by brad-eric** [kirill-grouchnikov/radiance#264]
### The issue you're experiencing:
When maximizing a JFrame it doesn't cause right behavior, as it appear in the 2 attached screenshots. Before & After maximizing the window.

![01 - Before Maximize](https://user-images.githubusercontent.com/1052828/78823450-ff3a5380-79dc-11ea-8611-c5ff6c9709f0.jpg)
![02 - After maximize](https://user-images.githubusercontent.com/1052828/78823455-02354400-79dd-11ea-831b-64702abe447d.jpg)

**Comment by kirill-grouchnikov** [comment]
There was a tiny fix that went into 3.0-SNAPSHOT. The screenshots also appear to be taken either on different monitors or on the same monitor but cropped. 

If this is still happening in 3.0-SNAPSHOT, I'll need to see the full-size versions of the screenshots.

**Comment by brad-eric** [comment]
Yes, i confirm it works fine with the 3.0-SNAPSHOT.

**Comment by kirill-grouchnikov** [comment]
Thanks for verifying!

**Comment by kirill-grouchnikov** [comment]
https://github.com/kirill-grouchnikov/radiance/pull/243 for reference
