### ISSUE TITLE
Borders of JButton appear cut off

### ISSUE THREAD

**Issue by brad-eric** [kirill-grouchnikov/radiance#268]
### The issue you're experiencing: JButton appears with borders cut off in most times, as if something is blocking them. I am attaching a screenshot showing this + A small running application with the source code to test this.

![buttons cut off](https://user-images.githubusercontent.com/1052828/79941370-6c7dc800-8464-11ea-8e22-08acbcd3d1ff.jpg)
[Popup Border Sample.zip](https://github.com/kirill-grouchnikov/radiance/files/4513819/Popup.Border.Sample.zip)

**Comment by kirill-grouchnikov** [comment]
Are you by any chance running this under fractional system-level DPI, like 125% or 150%?

**Comment by brad-eric** [comment]
> Are you by any chance running this under fractional system-level DPI, like 125% or 150%?

No, but i am using a 4K screen if that makes a difference.

**Comment by kirill-grouchnikov** [comment]
<img width="150" alt="image" src="https://user-images.githubusercontent.com/52874/79983086-444a9500-8475-11ea-8b13-c5baf2b29b49.png">

Not seeing cutoffs on my monitor. I don't have access to a 4K screen though

**Comment by kirill-grouchnikov** [comment]
Can you add the following line somewhere in main:

`System.out.println(NeonCortex.getScaleFactor())`

and let me know what it prints?

**Comment by kirill-grouchnikov** [comment]
Also, I'd like to remove `FormLayout` from the equation. Does this happen when you use a simple core `FlowLayout` on the same buttons?

**Comment by brad-eric** [comment]
> Can you add the following line somewhere in main:
> 
> `System.out.println(NeonCortex.getScaleFactor())`
> 
> and let me know what it prints?

It prints 2.5

**Comment by kirill-grouchnikov** [comment]
If it's fractional, it's https://github.com/kirill-grouchnikov/radiance/issues/39

And I don't have a solution for that in the current way Substance paints and caches offscreen images

**Comment by brad-eric** [comment]
> If it's fractional, it's #39
> 
> And I don't have a solution for that in the current way Substance paints and caches offscreen images

Yes, it seems to be the same problem! 🙁

**Comment by kirill-grouchnikov** [comment]
https://github.com/kirill-grouchnikov/radiance/issues/39#issuecomment-426400793 is the most relevant comment in there. Nothing has changed in Substance since then in this particular area.

**Comment by kirill-grouchnikov** [comment]
Let's continue over at https://github.com/kirill-grouchnikov/radiance/issues/39
