### ISSUE TITLE
How do I use those radiance APIs?

### ISSUE THREAD

**Issue by UltimateYZ** [kirill-grouchnikov/radiance#275]
Hi kirill,

I wanted to know I can use radiance APIs in my java project (Ant build).

**Comment by kirill-grouchnikov** [comment]
Browse the documentation of the project. The main page has links to documentation pages of each core library. For example https://github.com/kirill-grouchnikov/radiance/blob/master/docs/substance/substance.md is for Substance. At the top of the page you'll see a Maven Central badge - clicking on that opens a page with instructions on how to add that particular library to your project in a variety of build systems including Ant.

https://github.com/kirill-grouchnikov/radiance/blob/master/docs/substance/add-to-your-project.md has a bit more info on additional ways to add Substance to your project. Those instructions can also be used for other Radiance libraries. And https://github.com/kirill-grouchnikov/radiance/blob/master/docs/substance/faq.md is an introduction to how integrate Substance if you're a Swing beginner.
