### ISSUE TITLE
[Substance] Overriding Focus Behavior

### ISSUE THREAD

**Issue by bosbeles** [kirill-grouchnikov/radiance#288]
### Windows 10

This is not a bug just API change maybe. Sorry for this.

Hi. 
**I want to change focus ring color to red for example.**
To accomplish this, I've created a custom color scheme which is the copy-paste of BaseColorScheme because focus ring color is final. Then I've created a custom derived color resolver which is copy-paste of DerivedColorsResolverDark which is package private.
Then I have registered MyColorScheme to a bundle for various component states. Then I have registered the bundle to the skin which is GraphiteAqua in that case.

**The question is** whether there is a simpler way to change focus ring color. 
The problems I have faced are
* I don't know the exact component states. I've just tried and add two of them after failure.
* When registering a new color scheme to a bundle, I am frightened of breaking the default behavior.
* Private APIs
 
Another question is about changing focus kind. Suppose I want to add focus kind about drawing focus borders like in Nimbus, FlatLAF etc. Are you planning to extend focus kinds in that way? Or for adding that behavior, where should I start from?

`

    public MyLookAndFeel(SubstanceSkin skin) {
        super(skin);
        initColorSchemes(skin);
    }

    private void initColorSchemes(SubstanceSkin skin) {
        SubstanceSkin.ColorSchemes businessSchemes = SubstanceSkin
                .getColorSchemes(this.getClass().getClassLoader().getResourceAsStream("org/pushingpixels/substance/api/skin/graphite.colorschemes"));

        SubstanceColorScheme activeScheme = businessSchemes.get("Graphite Active");
        SubstanceColorScheme enabledScheme = businessSchemes.get("Graphite Enabled");
        SubstanceColorScheme disabledScheme = businessSchemes.get("Graphite Disabled");

        SubstanceColorSchemeBundle bundle = new SubstanceColorSchemeBundle(activeScheme, enabledScheme, disabledScheme);
        bundle.registerColorScheme(new MyColorScheme(), SubstanceSlices.ColorSchemeAssociationKind.MARK, ComponentState.ENABLED, ComponentState.SELECTED, ComponentState.ROLLOVER_SELECTED, ComponentState.ROLLOVER_ARMED);
        skin.registerDecorationAreaSchemeBundle(bundle, SubstanceSlices.DecorationAreaType.NONE, SubstanceSlices.DecorationAreaType.GENERAL);

    }`

**Comment by kirill-grouchnikov** [comment]
For a little bit of background on "external" focus kind see https://github.com/kirill-grouchnikov/radiance/issues/39#issuecomment-623054124. Making such a change is going to be a layout-breaking change, and while I'm considering doing that, it's not for immediate future.

I think the correct way to move forward to allow more control over the focus ring color is to add a new `ColorSchemeAssociationKind` specifically for focus ring. Then, applications can define their own skins with that tweak. I'll add it to 3.5 in the next couple days.

**Comment by kirill-grouchnikov** [comment]
With the proposed changes in 3.5, providing a custom focus indication color would look like this:

```java
    protected static class CustomFocusSkin extends GraphiteSkin {
        public CustomFocusSkin() {
            super();

            this.defaultSchemeBundle.registerColorScheme(
                    new MetallicColorScheme() {
                        @Override
                        public Color getFocusRingColor() {
                            return Color.red;
                        }
                    },
                    SubstanceSlices.ColorSchemeAssociationKind.FOCUS,
                    ComponentState.getAllStates().toArray(new ComponentState[0]));
        }

        @Override
        public String getDisplayName() {
            return "Graphite Red Focus";
        }
    }
```

There are a couple of things here that are not ideal. First, there's a lot of code for something that "should" take a line or two. Second, the whole concept of [color schemes](https://github.com/kirill-grouchnikov/radiance/blob/master/docs/substance/skins/colorschemes.md) hasn't scaled well over the years. I'll file another feature request for 4.0 to describe what is working and what is not working very well in that area.

**Comment by kirill-grouchnikov** [comment]
Addressing the first concern with a new color overlay API on `SubstanceSkin`:

```java
    protected static class CustomFocusSkin extends GraphiteSkin {
        public CustomFocusSkin() {
            super();

            this.setOverlayColor(Color.red, SubstanceSlices.ColorOverlayType.FOCUS_INDICATION,
                    DecorationAreaType.NONE, ComponentState.getAllStates().toArray(new ComponentState[0]));
        }

        @Override
        public String getDisplayName() {
            return "Graphite Red Focus";
        }
    }
```
