### ISSUE TITLE
[Flamingo] Add text separator to JCommandPopupMenu

### ISSUE THREAD

**Issue by Eng3l** [kirill-grouchnikov/radiance#29]
JCommandPopupMenu allows you to add separator which is basically an instance of JSeparator, but in some cases you need to add a text separator to indicate the name of the groups.

I achieve this with this code:
```java
public class JCommandGroupablePopupMenu extends JCommandPopupMenu {

    public void startGroup(String name) {
        JPanel panel = new JPanel(new BorderLayout());
        panel.add(new JXTitledSeparator(name, SwingConstants.HORIZONTAL), BorderLayout.CENTER);
        addMenuPanel(panel);
    }


    public void startGroup(String name, Icon icon) {
        JPanel panel = new JPanel(new BorderLayout());
        panel.add(new JXTitledSeparator(name, SwingConstants.HORIZONTAL, icon), BorderLayout.CENTER);
        addMenuPanel(panel);
    }

    @Override
    public void setMaxVisibleMenuButtons(int maxVisibleMenuButtons) {
        //avoid to change maxVisibleMenuButtons
    }
    
}
```
But due to code restrictions I'm not able to change the number of visible menu buttons. It will be nice to add this kind of support.

Thanks

**Comment by kirill-grouchnikov** [comment]
Can you add a screenshot of how that looks like?

**Comment by Eng3l** [comment]
I use SwingX but it can be done with a simple JLabel and a JSeparator
![screenshot_20180703_083000](https://user-images.githubusercontent.com/16307926/42219923-6c528d78-7e9b-11e8-974a-3f9d6cf726d1.png)

regards

**Comment by kirill-grouchnikov** [comment]
I would suggest putting this content in a JCommandButtonPanel with one column and MEDIUM display state. Then you can use panel groups as titles, and put the entire panel in a JCommandPopupMenu.

Otherwise this is a rather awkward addition to the command popup menu, creating too many visual breaks in the vertical flow.
