### ISSUE TITLE
Two way binding a la jGoodies!

### ISSUE THREAD

**Issue by keyhan** [kirill-grouchnikov/radiance#294]
Was wondering if Radiance have a 2-way binding mechanism like in JGoodies, or plan to have one?

**Comment by kirill-grouchnikov** [comment]
There is two way binding for commands in Flamingo - https://github.com/kirill-grouchnikov/radiance/blob/master/docs/flamingo/CommandSynchronization.md - which is about as far as I'm planning to push it

**Comment by kirill-grouchnikov** [comment]
Let me know what kind of specific functionally you're interested in

**Comment by kirill-grouchnikov** [comment]
And https://github.com/kirill-grouchnikov/radiance/blob/master/docs/flamingo/RibbonBandComponentProjections.md is for wrapping core Swing components in the same way

**Comment by kirill-grouchnikov** [comment]
No comment from OP. Closing.
