### ISSUE TITLE
After initializing the component, the created JFileChooser component, when the skin is changed, its background color will not change when the file is selected, and it is still the first initialized color. 

### ISSUE THREAD

**Issue by chirstwy** [kirill-grouchnikov/radiance#298]

**Comment by kirill-grouchnikov** [comment]
Please fill all required information. I'll also need to see a small, standalone project that shows the scenario you're describing.

**Comment by chirstwy** [comment]
> Please fill all required information. I'll also need to see a small, standalone project that shows the scenario you're describing.

Below is the code. After the component is initialized, if the skin type is changed, the color of the file selected in the file chooser will not change.

`import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import org.pushingpixels.substance.api.SubstanceCortex;
import org.pushingpixels.substance.api.skin.SkinInfo;
import org.pushingpixels.substance.api.skin.SubstanceNightShadeLookAndFeel;

public class Test extends javax.swing.JFrame {
    /**
     * Creates new form Test
     */
    public Test() {
        //Initialization UI Style
        try {
            System.out.println(" CREATING LAF ");
            long time0 = System.currentTimeMillis();
            LookAndFeel laf = new SubstanceNightShadeLookAndFeel();
            long time1 = System.currentTimeMillis();
            System.out.println(" LAF CREATED " + (time1 - time0));
            System.out.println(" SETTING LAF ");
            long time2 = System.currentTimeMillis();
            UIManager.setLookAndFeel(laf);
            long time3 = System.currentTimeMillis();
            System.out.println(" LAF SET " + (time3 - time2));
        } catch (Exception e) {
            e.printStackTrace();
        }
        SubstanceCortex.GlobalScope.setUseConstantThemesOnOptionPanes(true);
        SubstanceCortex.GlobalScope.setTabCloseButtonsVisible(true);
        SubstanceCortex.GlobalScope.setExtraWidgetsPresence(true);
        JFrame.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);
        //Initialize components, including jFileChooser, etc.
        initComponents();
        //Add skin items
        for (SkinInfo skinInfo : SubstanceCortex.GlobalScope.getAllSkins().values()) {
            String skinName=skinInfo.getClassName();
            String[] strs = skinName.split("[.]");
            JCheckBoxMenuItem menuItem = new JCheckBoxMenuItem(strs[5]);
            menuItem.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ev) {
                    SubstanceCortex.GlobalScope.setSkin(skinName);
                }
            });
            skinItemGroup.add(menuItem);
            skinjMenu.add(menuItem);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jMenu3 = new javax.swing.JMenu();
        skinItemGroup = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        skinjMenu = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));

        jToolBar1.setRollover(true);

        jButton1.setText("Open");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        skinjMenu.setText("Skin");
        jMenuBar1.add(skinjMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }            

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jFileChooser.showOpenDialog(this);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.ButtonGroup skinItemGroup;
    private javax.swing.JMenu skinjMenu;
    // End of variables declaration                   
}`

**Comment by kirill-grouchnikov** [comment]
```java
        menuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ev) {
                SubstanceCortex.GlobalScope.setSkin(skinName);
                SwingUtilities.updateComponentTreeUI(jFileChooser);  <-- add this line
            }
        });
```

The logic in `SubstanceCortex.GlobalScope.setSkin` iterates over all windows returned by `Window.getWindows()`. But that doesn't - and can't - know about the `JFileChooser` instance that you are reusing across skin changes. So for something like this you need to explicitly update that specific container after a skin change.

**Comment by chirstwy** [comment]
> ```java
>         menuItem.addActionListener(new ActionListener() {
>             public void actionPerformed(ActionEvent ev) {
>                 SubstanceCortex.GlobalScope.setSkin(skinName);
>                 SwingUtilities.updateComponentTreeUI(jFileChooser);  <-- add this line
>             }
>         });
> ```
> 
> The logic in `SubstanceCortex.GlobalScope.setSkin` iterates over all windows returned by `Window.getWindows()`. But that doesn't - and can't - know about the `JFileChooser` instance that you are reusing across skin changes. So for something like this you need to explicitly update that specific container after a skin change.

Yeah, perfect solution, thank you very much!
