### ISSUE TITLE
SubstanceListUI::repaintCell EDT violation

### ISSUE THREAD

**Issue by cmadsen** [kirill-grouchnikov/radiance#30]
`SubstanceListUI::repaintCell` seems to be causing a EDT violation:

    at ...$1.getListCellRendererComponent(...java:159)
    at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1361)
    at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
    at org.pushingpixels.substance.internal.ui.SubstanceListUI.access$2300(SubstanceListUI.java:92)
    at org.pushingpixels.substance.internal.ui.SubstanceListUI$CellRepaintCallback.repaintCell(SubstanceListUI.java:440)
    at org.pushingpixels.substance.internal.ui.SubstanceListUI$CellRepaintCallback.onTimelineStateChanged(SubstanceListUI.java:419)
    at org.pushingpixels.trident.Timeline$Chain.onTimelineStateChanged(Timeline.java:214)
    at org.pushingpixels.trident.TimelineEngine$1.run(TimelineEngine.java:591)
    at org.pushingpixels.trident.TimelineEngine$TimelineCallbackThread.run(TimelineEngine.java:242)

It is randomly causing a weird/impossible NPE in JLabel when the getListCellRendererComponent is using icons:

java.lang.NullPointerException
	at javax.swing.JLabel.setIcon(JLabel.java:406)
	at ...$1.getListCellRendererComponent(...java:171)

I have a found an old version of SubstanceListUI where the repaintCell is wrapped in a invokeLater call

```java
        /**
         * Repaints the associated cell.
         */
        private void repaintCell() {
            // SwingUtilities.invokeLater(new Runnable() {
            // public void run() {
            if (SubstanceListUI.this.list == null) {
                // may happen if the LAF was switched in the meantime
                return;
            }
            try {
                maybeUpdateLayoutState();
                int cellCount = list.getModel().getSize();
                if ((cellCount > 0) && (cellIndex < cellCount)) {
                    // need to retrieve the cell rectangle since the
                    // cells can be moved while animating
                    Rectangle rect = SubstanceListUI.this.getCellBounds(list,
                            cellIndex, cellIndex);
                    // System.out.println("Repainting " + cellIndex
                    // + " at " + rect);
                    list.repaint(rect);
                }
            } catch (RuntimeException re) {
                return;
            }
        }
```
Should the `repaintCell` not be wrapped in a `invokerLater` to avoid a EDT violation?

**Comment by kirill-grouchnikov** [comment]
Is this happening under the latest 0.9.0-dev build of Substance from Radiance? The line numbers do not match the stack trace.

Looking at the CellRepaintCallback in SubstanceListUI, it is marked as UIThreadTimelineCallbackAdapter which means that everything in it should be run on the UI thread by Trident. In this stack trace it should be in Timeline.Chain.handleStateChange where it looks at the callback and its annotations.

If this is still happening under the latest Radiance sources, I would need the matching stack trace and, ideally, a small complete test app that shows this issue.

**Comment by cmadsen** [comment]
When I try to build 0.9.0-dev with  ./gradlew I get

Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

Seems like gradle/wrapper/gradle-wrapper.jar is missing?

**Comment by kirill-grouchnikov** [comment]
My bad. I'll remove gradle from the .gitignore, but it will take me a few days.

In the meantime, you can get substance, trident and neon jars from drop/0.9-dev/core and add them to the classpath. 

https://github.com/kirill-grouchnikov/radiance/tree/master/drop/0.9-dev/core

**Comment by cmadsen** [comment]
As far as I can tell from the code `if (shouldRunOnUIThread && (Timeline.this.uiToolkitHandler != null))` in `Timeline.Chain.handleStateChange:~197` the annotation on `UIThreadTimelineCallbackAdapter`  is ignored if there is no `uiToolkitHandler`. This happens when the` mainTimelineObject` given to the `Timeline` constructor is not a `Component`.

This happens in In StateTransitionTracker.java:345
```java
		this.transitionTimeline = new Timeline(this);
		this.transitionTimeline.setName("Model transitions");
		this.transitionTimeline.addCallback(this.repaintCallback
				.getRepaintCallback());
```
where `this` (StateTransitionTracker) is not a `Component`.

Timeline.java:197:
```java
if (shouldRunOnUIThread && (Timeline.this.uiToolkitHandler != null)) {
                Timeline.this.uiToolkitHandler.runOnUIThread(mainObject,
                        () -> callback.onTimelineStateChanged(oldState, newState, durationFraction,
                                timelinePosition));
            } else {
                callback.onTimelineStateChanged(oldState, newState, durationFraction,
                        timelinePosition);
            }
```
So even if `this.repaintCallback.getRepaintCallback()` is a `UIThreadTimelineCallbackAdapter` it will get called outside the EDT?

Here is how it looks in my debugger with an older version of Substance, uiToolkitHandler is null and shouldRunOnUIThread is true: 

```
this	Timeline$Chain  (id=540)	
	callbacks	ArrayList<E>  (id=548)	
	this$0	Timeline  (id=556)	
		callback	Timeline$Chain  (id=540)	
		cycleDelay	0	
		doneCount	1	
		duration	200	
		durationFraction	1.0	
		ease	Spline  (id=559)	
		fullObjectID	TimelineEngine$FullObjectID  (id=562)	
		id	36501	
		initialDelay	0	
		isLooping	false	
		mainObject	StateTransitionTracker  (id=564)	
		name	"Model transitions" (id=566)	
		propertiesToInterpolate	ArrayList<E>  (id=567)	
		repeatBehavior	null	
		repeatCount	0	
		secondaryId	null	
		stateStack	Stack<E>  (id=568)	
		timelinePosition	1.0	
		timeUntilPlay	0	
		toCancelAtCycleBreak	false	
		uiToolkitHandler	null	
callback	SubstanceListUI$CellRepaintCallback  (id=539)	
	cellIndex	1898	
	list	BasicComboPopup$1  (id=572)	
	this$0	SubstanceListUI  (id=538)	
		cellHeight	-1	
		cellHeights	(id=658)	
		cellWidth	378	
		columnCount	1	
		focusListener	BasicListUI$Handler  (id=660)	
		handler	BasicListUI$Handler  (id=660)	
		isFileList	false	
		isLeftToRight	true	
		lafWidgets	HashSet<E>  (id=664)	
		layoutOrientation	0	
		list	BasicComboPopup$1  (id=572)	
		listDataListener	BasicListUI$Handler  (id=660)	
		listHeight	0	
		listSelectionListener	BasicListUI$Handler  (id=660)	
		listWidth	0	
		mouseInputListener	BasicListUI$Handler  (id=660)	
		preferredHeight	0	
		propertyChangeListener	BasicListUI$Handler  (id=660)	
		rendererPane	CellRendererPane  (id=668)	
		rolledOverIndex	-1	
		rowsPerColumn	0	
		selectedIndices	HashMap<K,V>  (id=670)	
		stateTransitionMultiTracker	StateTransitionMultiTracker<T>  (id=673)	
		substanceComponentListener	SubstanceListUI$2  (id=675)	
		substanceFadeRolloverListener	SubstanceListUI$RolloverFadeListener  (id=678)	
		substanceListDataListener	SubstanceListUI$SubstanceListDataListener  (id=680)	
shouldRunOnUIThread	true	
clazz	Class<T> (org.pushingpixels.trident.callback.TimelineCallbackAdapter) (id=544)	
i	1	
durationFraction	0.205	
timelinePosition	0.12563747	
```

**Comment by kirill-grouchnikov** [comment]
Thanks for tracking that. Can't believe that the bug has been in there for so long.

That timeline should be getting this.component instead of this. It'll take me until early next week to commit it to Git.

**Comment by cmadsen** [comment]
No problem, we have been haunted by this for years.

**Comment by kirill-grouchnikov** [comment]
This introduced broken behavior whereas views tracked by StateTransitionTracker are not properly painted when the first time. Fix coming up this week.
