### ISSUE TITLE
Renderer support for Temporal values

### ISSUE THREAD

**Issue by jkdoug** [kirill-grouchnikov/radiance#302]
Version of Radiance: 3.0.0
Sub-project: Substance
Version of Java: OpenJDK 9
Version of OS: Windows 10 Enterprise 1909

Issue:
  SubstanceDefaultTableCellRenderer supports Date for rendering date/time values. It does not currently appear to support Temporal values. Would it be possible to add this as a feature? Thank you for your time and for this amazing library.

**Comment by kirill-grouchnikov** [comment]
I've never worked with the `Temporal` interface and its subclasses, or with `DateTimeFormatter` APIs that work with temporals. There's a whole bunch of public static `DateTimeFormatter` instances available in the JDK. Not sure if it would make sense to use one of them for the new default Substance renderer.

Does it not work for you to use the `JTable.setDefaultRenderer` with the specific extension of the `SubstanceDefaultTableCellRenderer` that overrides the `setValue` and formats your temporals based on the expected template?

**Comment by jkdoug** [comment]
I will implement my own renderer, for now, of course. Perhaps I will be able to contribute to your project in the near future, too. I suppose I was surprised that a Java 9 UI library did not yet support the Java 8 Time classes. I really enjoy using the new classes over the old Date stuff. Thanks for the response!

**Comment by kirill-grouchnikov** [comment]
As I said, I don't have any experience in that area of the JDK APIs, but it doesn't look like there's one "right" way to format those values, so perhaps that would be best left to the specific apps to decide.
