### ISSUE TITLE
Memory Leak using Substance Flamingo

### ISSUE THREAD

**Issue by redskoller** [kirill-grouchnikov/radiance#309]
Version of Radiance: 2.5.1
Sub-project (Neon, Trident, Substance, Flamingo, ...)
Version of Java: 11
Version of OS: macOS 10.15.6

We use your UI in every dialog we open. After closing the dialog the GC can not destroy everythin from UI. With the help of VisualVM we see that **org.pushingpixels.trident.swing.SwingComponentTimeline** exists many tousend times.
Ist there any example how to destroy JRibbonBand/JCommandButtons/...?

**Comment by kirill-grouchnikov** [comment]
Version 3.5.0 of Radiance has been released two days ago. I do not have resources to support older versions of Radiance.

If you're still experiencing this issue with this latest release, I'll need to see a small, standalone application that reproduces that issue. Without being able to reproduce this on my end, the information in this bug is too vague.

**Comment by redskoller** [comment]
You can reproduce the problem by execute the sample: **BasicCheckRibbon**
Klick many time on **File** (open/close/open/close/...).
The count of class org.pushingpixels.flamingo.api.common.JCommandButton increases continuously.

**Comment by kirill-grouchnikov** [comment]
I'm not seeing any increase in `JCommandButton` instances (stays constant at 460) or `SwingComponentTimeline` (stays around 6,100-6,200) after opening and closing the ribbon menu (File) and doing "Perform GC" in VisualVM  2.0.2

**Comment by redskoller** [comment]
After upgrade to version 3.5.0 the issue also exists.
Many hours later I found the problem. In class **BasicRibbonUI** is called the Methode **setComponentCustomizer()** on **taskToggleCommandProjection**.

I tried to **setComponentCustomer(null)** in the **uninstallComponents()** method. Unfortunately it didn't work either.
If I comment out the ComponentCustomizer, the HeapSpace error would be resolved. Do you have some ideas?
<img width="1606" alt="visualvm" src="https://user-images.githubusercontent.com/16945166/95299202-99d8f980-087d-11eb-8150-a0a445654aa8.png">

**Comment by kirill-grouchnikov** [comment]
Are you opening and closing frames or dialogs containing the ribbon? Is that where you're seeing the leaks?

**Comment by redskoller** [comment]
Yes, this is the use case. We open and close dialogs containing the ribbon. With the look at the `RibbonTasks` I can see the Memory leak. Not all instantiated objects are released, as shown in the image above.

**Comment by kirill-grouchnikov** [comment]
Are you using `JRibbonFrame`s or `JDialog`s?

**Comment by redskoller** [comment]
I use `JDialog.`

**Comment by kirill-grouchnikov** [comment]
How do you place the ribbon in there? The only officially tested configuration is through `JRibbonFrame`. It'll save us both a lot of back and forth if you attach a reproducible demo that shows this issue.

**Comment by kirill-grouchnikov** [comment]
The window for fixing in 3.5 has closed. Moving to 4.0.

**Comment by kirill-grouchnikov** [comment]
Will close this soon with a reproducible demo
