### ISSUE TITLE
[Radiance] Broken Maven dependencies for Radiance modules in Central Maven Repo

### ISSUE THREAD

**Issue by mvmn** [kirill-grouchnikov/radiance#310]
Latest Radiance-Substance in central Maven repo 3.5.0 has dependencies on non-existing artifacts substance-trident and substance-neon:
https://mvnrepository.com/artifact/org.pushing-pixels/radiance-substance/3.5.0
![Screenshot 2020-10-09 at 21 45 30](https://user-images.githubusercontent.com/1076779/95620393-c6a53080-0a78-11eb-97cf-fee6e6ab8777.png)

Proper names for those artifacts seem to be radiance-trident and radiance-neon:
https://mvnrepository.com/artifact/org.pushing-pixels/radiance-trident/3.5.0
https://mvnrepository.com/artifact/org.pushing-pixels/radiance-neon/3.5.0

So actual Maven config for this has to be
```
		<dependency>
			<groupId>org.pushing-pixels</groupId>
			<artifactId>radiance-substance</artifactId>
			<version>3.5.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.pushing-pixels</groupId>
					<artifactId>substance-trident</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.pushing-pixels</groupId>
					<artifactId>substance-neon</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.pushing-pixels</groupId>
			<artifactId>radiance-neon</artifactId>
			<version>3.5.0</version>
		</dependency>
		<dependency>
			<groupId>org.pushing-pixels</groupId>
			<artifactId>radiance-trident</artifactId>
			<version>3.5.0</version>
		</dependency>
```

P.S. Also it's all compiled with Java9 and thus fails on Java8 - but I guess that's another issue

**Comment by kirill-grouchnikov** [comment]
There was a very early refactoring of build files with https://github.com/kirill-grouchnikov/radiance/commit/9002a7a580c589c6b9dde233e6432bf900c9367a#diff-a3ec5ac3ae8bfa9d5f25e3925969c4ff and https://github.com/kirill-grouchnikov/radiance/commit/9002a7a580c589c6b9dde233e6432bf900c9367a#diff-c197962302397baf3a4cc36463dce5ea

Will take a look at fixing this for 3.5.1. As for Java 8, the minimum requirement for building and running Radiance is Java 9.

**Comment by kirill-grouchnikov** [comment]
3.5.1 has been uploaded to Sonatype repository. Should be on Maven Central soon as it propagates. Will keep this open until I verify the correct dependencies in a standalone project.

**Comment by mvmn** [comment]
Thanks!

**Comment by mvmn** [comment]
Oops, sorry, closed this too soon.

**Comment by kirill-grouchnikov** [comment]
Confirmed that 3.5.1 has the right dependencies specified in its POM.
