### ISSUE TITLE
Use Default System Look and Feel

### ISSUE THREAD

**Issue by rikyyang** [kirill-grouchnikov/radiance#311]
### Version of Radiance (current stable is 3.5.1)
3.5.0

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Substance, Flamingo

### Version of Java (current minimum is 9)
java 11

### Version of OS
MacOS Catalina 10.15.7

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
```java
            SubstanceCortex.GlobalScope.setSkin(new SubstanceSkin() {
                @Override
                public String getDisplayName() {
                    return UIManager.getSystemLookAndFeelClassName();
                }
            });
```

i am using flamingo components,, is there a way for setting default system look and feel with/without substance ?
this is the error i get when i try above code..
"Substance delegate used when Substance is not the current LAF [component JRibbonRootPane in window null:'null' under Mac OS X]"

**Comment by kirill-grouchnikov** [comment]
As mentioned in the top-level [Flamingo documentation], all Flamingo components work only with Substance. There are no plans to provide support for any core or other third-party look-and-feels as part of Radiance - beyond making sure that applications using **core** Swing components can switch between Substance and other look-and-feels.

**Comment by kirill-grouchnikov** [comment]
Also, that piece of code doesn't really do what you'd "want" it to do. The concept of display name is specific to Substance, and returning the class name of some other look-and-feel isn't going to turn Substance into that look-and-feel.

**Comment by rikyyang** [comment]
okay,, thx for fast reply..

another question,, is that possible to manually/automatically convert system look and feel to substance skin?

**Comment by kirill-grouchnikov** [comment]
Not to the system one. Those change between OS versions and it's not realistic to be able to get close to the system look and feel without using the matching native skinning APIs.
