### ISSUE TITLE
disabling animations

### ISSUE THREAD

**Issue by twak** [kirill-grouchnikov/radiance#326]
### Version of Radiance (current development is 4.0-SNAPSHOT)
3.5.1

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Substance?

### Version of Java (current minimum is 9)
13

### Version of OS
Ubuntu 16

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

Thanks, this is a fantastic project. I'm attempting to disable the animations on the Substance Graphite look and feel - in particular the fade-to-white on hover-over a JButton and Menu Item. My first attempt at this is below...but no luck. Any ideas?

```
                  for ( SubstanceSlices.AnimationFacet sf : new SubstanceSlices.AnimationFacet[]{
                            SubstanceSlices.AnimationFacet.ROLLOVER,
                            SubstanceSlices.AnimationFacet.GHOSTING_BUTTON_PRESS,
                            SubstanceSlices.AnimationFacet.GHOSTING_ICON_ROLLOVER,
                            SubstanceSlices.AnimationFacet.ICON_GLOW,
                            SubstanceSlices.AnimationFacet.SELECTION,
                            SubstanceSlices.AnimationFacet.GHOSTING_BUTTON_PRESS,
                            SubstanceSlices.AnimationFacet.FOCUS,
                            SubstanceSlices.AnimationFacet.FOCUS_LOOP_ANIMATION,
                            SubstanceSlices.AnimationFacet.PRESS,
                            SubstanceSlices.AnimationFacet.ARM,
                    } ) {
					    AnimationConfigurationManager.getInstance().disallowAnimations( sf, JTabbedPane.class );
					    AnimationConfigurationManager.getInstance().disallowAnimations( sf, JButton.class );
					    AnimationConfigurationManager.getInstance().disallowAnimations( sf, JMenuItem.class );
					    AnimationConfigurationManager.getInstance().disallowAnimations( sf, JMenu.class );
                    }
```

**Comment by kirill-grouchnikov** [comment]
Which part of the "fade-to-white" do you expect `disallowAnimations` to disable? The fade part or the white part?

**Comment by twak** [comment]
The fade part. The white is nice - animations are just too slow on this box :(

**Comment by kirill-grouchnikov** [comment]
See https://github.com/kirill-grouchnikov/substance/issues/28

I thought I added a bit more comments around the scope of what `disallowAnimations` does, but I didn't. I'll add it to the relevant `SubstanceCortex` APIs (note that you shouldn't be using `AnimationConfigurationManager` directly, as that is in an internal package).

The short answer is that you can't selectively disable animations on components beyond a few specific cases like cell renderers and custom icon glows. And there are no plans to extend that functionality to control the other animations.

**Comment by twak** [comment]
thanks for the quick + concise answer! I'll figure something out for my use cases.

**Comment by twak** [comment]
I ended up using:
```
AnimationConfigurationManager.setTimelineDuration(0)
```
as suggested in the linked post - this increases the responsiveness on a slow system for me. Thanks again!
