### ISSUE TITLE
[Flamingo] new component request : GroupableTableHeader

### ISSUE THREAD

**Issue by mtbadi39** [kirill-grouchnikov/radiance#33]
<pre>
 * +-----------------------------------------------------+
 * |        |       Name      |         Language         |
 * |        |-----------------|--------------------------|
 * |  SNo.  |        |        |        |      Others     |
 * |        |   1    |    2   | Native |-----------------|
 * |        |        |        |        |   2    |   3    |
 * |-----------------------------------------------------|
 * |        |        |        |        |        |        |
</pre>
like [this](https://alvinalexander.com/java/swing/tame/table/GroupableTableHeader.java.shtml) by **Nobuo Tamemasa**

**Comment by kirill-grouchnikov** [comment]
This is outside the scope of this project.

**Comment by mtbadi39** [comment]
Sorry ! but when i read (in docs) :

> The Flamingo library provides a robust set of additional Swing components that can be used as building blocks for creating modern, rich Swing applications.

... i think that the **GroupableTableHeader** is another additional Swing component that can be used for creating modern, rich applications !  :confused:

**Comment by kirill-grouchnikov** [comment]
I do not have any plans to extend the current scope of Flamingo with additional components. I'd suggest looking at JIDE components that have a lot of things to do with tables.
