### ISSUE TITLE
Drawing borders of JScrollPane

### ISSUE THREAD

**Issue by Nopalin** [kirill-grouchnikov/radiance#331]
### Version of OS Windows 8

I was playing around with this awsome LaF, i think i am going to use it on my next project, but there is something that is bothering me, the fact that i could not find a way to draw some component's border, like jtable or jlist that are inside a jscrollpane.

I read about SubstanceBorderPainter but i found nothing for drawing borders of these components, i even did debug with eclipse but i failed to find how. That's why i am here asking, any body of you can help me of how can i achieve that?

Thanks

**Comment by kirill-grouchnikov** [comment]
Before we talk about specific APIs, can you provide maybe a screenshot / design mock of what's you're trying to achieve? Tables have separators (or rather, grid lines). Lists don't have any borders. The same goes for scroll panes. 

On the other hand, buttons have borders. Text fields have borders. Etc. So I'm trying to first understand what it is that you're after, and then suggest the matching Substance APIs based on that.

**Comment by Nopalin** [comment]
Compare the same app with another LAF and with Cerulean Skin of substance. Note the borders being drawn in the other LAF.

![imagen](https://user-images.githubusercontent.com/2869435/112063160-97661580-8b26-11eb-9915-98376e543569.png)

![imagen](https://user-images.githubusercontent.com/2869435/112063188-9df48d00-8b26-11eb-9162-a288d7a7b59e.png)

**Comment by kirill-grouchnikov** [comment]
There are a few options. First, you would start by getting the current Substance skin with `SubstanceCortex.GlobalScope.getCurrentSkin()` or `SubstanceCortex.ComponentScope.getCurrentSkin(Component)` APIs. If you only use one skin in your app (that is, not using different skins on different windows), the first should be fine.

Next, get the border painter with `SubstanceSkin.getBorderPainter()`. From here, the decision is whether you want to draw something with one solid color, or something that follows the border visuals of controls such as buttons, comboboxes, etc.

In both cases, you need a `SubstanceColorScheme` that matches the specific component, optionally in a specific component state (rollover, selected, etc). For the simplest case, you can call `SubstanceSkin.getColorScheme(Component, ComponentState)` and pass `ComponentState.ENABLED - like for these lists and tables in your example.

Then, for a single solid color, call `SubstanceBorderPainter.getRepresentativeColor(SubstanceColorScheme)` and use that for drawing the border (maybe with Swing's `LineBorder`, or maybe with your own border implementation). For border visuals that follow the look of the current skin (along with gradients, alpha, etc), use `SubstanceBorderPainter.paintBorder`, passing the component, its dimensions, the shape that you want to paint (rectangle, rounded rectangle, etc) and the color scheme.

https://github.com/kirill-grouchnikov/radiance/blob/sunshine/demos/substance-demo/src/main/java/org/pushingpixels/demo/substance/main/check/FakeAccordion.java#L102 (lines 102-171) is a complete example from the main Substance demo on how to use these APIs together for a custom container.

**Comment by Nopalin** [comment]
Ok thank you very much for poiting me in the right direction. I have years using swing but it seems i have a lot to learn yet. Tables and lists does not have a border by default, but scrollpane does, so the other LaF and substance have injected the appropiated implementation, but what i was could not observe is that substance did not draw anything (it is an empty method).
So following your recomendations i write a class implementing Border and set it to the scrollpane and now i can see the expected results, moreover it is fantactis the rounded corners in your example, the only thing i did was close the path.

I let the code here ifor anyone else.

```
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.geom.Arc2D;
import java.awt.geom.GeneralPath;

import javax.swing.border.Border;

import org.pushingpixels.neon.api.NeonCortex;
import org.pushingpixels.substance.api.ComponentState;
import org.pushingpixels.substance.api.SubstanceCortex;
import org.pushingpixels.substance.api.SubstanceSkin;
import org.pushingpixels.substance.api.SubstanceSlices;
import org.pushingpixels.substance.api.colorscheme.SubstanceColorScheme;
import org.pushingpixels.substance.api.painter.border.SubstanceBorderPainter;

public class SubstanceRounderBorder implements Border {
	
	float borderThickness;
	float radius;
	
	public SubstanceRounderBorder() {
		this(1.0f, 5.0f);
	}

	public SubstanceRounderBorder(float borderThickness, float radius) {
		this.borderThickness = borderThickness;
		this.radius = radius;
	}
	
	@Override public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
		SubstanceSkin skin = SubstanceCortex.GlobalScope.getCurrentSkin();
		SubstanceBorderPainter borderPainter = skin.getBorderPainter();
		SubstanceColorScheme borderScheme = skin.getColorScheme(c, SubstanceSlices.ColorSchemeAssociationKind.BORDER, ComponentState.ENABLED);
		
		Graphics2D g2d = (Graphics2D) g.create();
		g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
		g2d.setRenderingHint(RenderingHints.KEY_STROKE_CONTROL, RenderingHints.VALUE_STROKE_PURE);
		
		float thickness = borderThickness / (float) NeonCortex.getScaleFactor();
		float diameter = radius * 2.0f;
		float xStart = x + thickness / 2.0f;
		float yStart = y + thickness / 2.0f;
		GeneralPath outer = new GeneralPath();
		// Start in top left
		outer.moveTo(xStart, yStart + radius);
		// Line down
		float yStartBottomCurve = yStart + height - diameter - thickness;
		outer.lineTo(xStart, yStartBottomCurve);
		// Curve for the bottom left corner
		outer.append(new Arc2D.Double(xStart, yStartBottomCurve, diameter, diameter, 180, 90, Arc2D.OPEN), true);
		// Line right
		float xStartRightCurve = xStart + width - diameter - thickness;
		outer.lineTo(xStartRightCurve, yStart + height - thickness);
		// Curve for the bottom right corner
		outer.append(new Arc2D.Double(xStartRightCurve, yStartBottomCurve, diameter, diameter, 270, 90, Arc2D.OPEN), true);
		// Line up
		outer.lineTo(xStart + width - thickness, yStart + diameter);
		// Curve for the top right corner
		outer.append(new Arc2D.Double(xStartRightCurve, yStart, diameter, diameter, 0, 90, Arc2D.OPEN), true);
		// Line left
		outer.lineTo(xStart + diameter, yStart);
		// Curve for the top left corner
		outer.append(new Arc2D.Double(xStart, yStart, diameter, diameter, 90, 90, Arc2D.OPEN), true);
		
		g2d.translate(x, y);
		borderPainter.paintBorder(g2d, c, width, height, outer, null, borderScheme);
		g2d.dispose();
	}
	
	@Override public Insets getBorderInsets(Component c) {
		int a = (int)radius;
		return new Insets(a, a, a, a);
	}

	@Override public boolean isBorderOpaque() {
		return false;
	}
}
```

**Comment by Nopalin** [comment]
This is the result i was looking for.
![imagen](https://user-images.githubusercontent.com/2869435/112079179-50d3e380-8b45-11eb-98a1-e56b506430da.png)

**Comment by kirill-grouchnikov** [comment]
Glad you made it work. The API surface of Substance is a bit more complex compared to other look-and-feels, but that's the approach I'm taking. Doing look-and-feel customizations through client properties may seem like a more lightweight approach to not introduce a direct compile-time dependency on a specific look-and-feel library, but it quickly breaks down in terms of how much you can push that envelope before it breaks the mental model.
