### ISSUE TITLE
[Neon] NeonCortex.colorizeIcon is not rendering icon when svg file is loaded at runtime

### ISSUE THREAD

**Issue by suhasinisridhar** [kirill-grouchnikov/radiance#333]
Version of Radiance (**3.5.1**)
Sub-project (**Neon**)
Version of Java (**JDK15**)
Version of OS(**Windows 10**)

I observed that NeonCortex.colorizeIcon is not rendering icon when svg icons are loaded at runtime and the same works for generated java class.

**Comment by suhasinisridhar** [comment]
package org.pushingpixels.demo.flamingo.common;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;

import org.pushingpixels.flamingo.api.common.model.Command;
import org.pushingpixels.flamingo.api.common.model.CommandButtonPresentationModel;
import org.pushingpixels.flamingo.api.common.projection.CommandButtonProjection;
import org.pushingpixels.flamingo.api.ribbon.JRibbonBand;
import org.pushingpixels.neon.api.NeonCortex;
import org.pushingpixels.photon.api.icon.SvgBatikResizableIcon;
import org.pushingpixels.substance.api.SubstanceCortex;
import org.pushingpixels.substance.api.skin.GraphiteSkin;


public class TestIconColourChange extends JFrame {
	
	public TestIconColourChange() {
		super("Change SVG Icon colour");
        this.setLayout(new BorderLayout());

        JPanel panel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        this.add(panel, BorderLayout.CENTER);
        Command newCommand = Command.builder()
                .setText("New")
               // .setIconFactory(()->getIcon("new.svg"))
                .setIconFactory(()->NeonCortex.colorizeIcon(
                		()->getIcon("new.svg"),
			               Color.white,0.8f))
                .build();
        
        CommandButtonProjection<Command> newCommandProjection = newCommand.project(CommandButtonPresentationModel.builder()
                .setPresentationState(JRibbonBand.BIG_FIXED)
                .setFlat(false).build());
        panel.add(newCommandProjection.buildComponent());


	}
	
	public SvgBatikResizableIcon getIcon(String fileName) {
		SvgBatikResizableIcon icon = null;
		try {
			icon = SvgBatikResizableIcon.getSvgIcon(new FileInputStream("D:\\"+fileName), new Dimension(50,50));
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return icon;
	}
	
	public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame.setDefaultLookAndFeelDecorated(true);
            SubstanceCortex.GlobalScope.setSkin(new GraphiteSkin());
            TestIconColourChange frame = new TestIconColourChange();
            frame.setSize(300, 300);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        });
    }
}


SVG file:
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 14v-3h-2v3H7v2h3v3h2v-3h3v-2M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6m4 18H6V4h7v5h5"/></svg>

**Comment by suhasinisridhar** [comment]
SVG File:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 14v-3h-2v3H7v2h3v3h2v-3h3v-2M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6m4 18H6V4h7v5h5"/></svg>`

**Comment by kirill-grouchnikov** [comment]
Right, `NeonCortex.colorizeIcon` does not support content that implements the `AsynchronousLoading` interface - which is what `SvgBatikResizableIcon.getSvgIcon` returns. Will look into this.

**Comment by kirill-grouchnikov** [comment]
This should now work in the latest 4.0-SNAPSHOT build (will be uploaded to Sonatype in a few hours, but you can test it in a local build in the meanwhile):

```
            Command greenCommand = Command.builder()
                    .setText("Green")
                    .setIconFactory(() -> NeonCortex.colorizeIcon(
                            () -> SvgBatikResizableIcon.getSvgIcon(
                                    IconFrame.class.getResourceAsStream("svg/radiance_menu.svg"),
                                    NeonCortex.getScaleFactor(frame),
                                    new Dimension(16, 16)),
                            Color.green
                    ))
                    .build();
            frame.add(greenCommand.project(presentationModel).buildComponent());

            Command blueCommand = Command.builder()
                    .setText("Red")
                    .setIconFactory(() -> NeonCortex.colorizeIcon(
                            () -> SvgBatikResizableIcon.getSvgIcon(
                                    IconFrame.class.getResourceAsStream("svg/radiance_menu.svg"),
                                    NeonCortex.getScaleFactor(frame),
                                    new Dimension(16, 16)),
                            Color.blue
                    ))
                    .build();
            frame.add(blueCommand.project(presentationModel).buildComponent());
```

**Comment by kirill-grouchnikov** [comment]
This is available in Sonatype-hosted snapshot repository now

**Comment by suhasinisridhar** [comment]
HI Kirill,
    I started integrating Flamingo and Substance into our application.After
integration,I could see some of the images(gif & svgs) out of Ribbon are
filled with black color.Then I found the reason that it is because of the
below setting

SubstanceCortex.GlobalScope.setIconThemingStrategy(
                     SubstanceSlices.IconThemingStrategy.FOLLOW_FOREGROUND);

With this Theming strategy,all my ribbon icons are changing colors
automatically for light and dark theme whereas other images are filled with
black color.I could reproduce this in BasicCheckRibbon example.

Thanks & Regards,
Suhasini

**Comment by kirill-grouchnikov** [comment]
That is the expected behavior. `IconThemingStrategy.FOLLOW_FOREGROUND` replaces all pixels with a single color, respecting the original pixel alpha. It works well for monochrome icons such as the Material icon set for example. But it doesn't work well for multi-color icons such as Tango. This is why it is not the default option in Substance or Flamingo.

You can use `SubstanceCortex.ComponentScope.setIconThemingStrategy` to set the icon theming strategy on specific components instead of globally on your whole app. Or you can use monochrome icons everywhere.

**Comment by suhasinisridhar** [comment]
Thanks for your reply.
yes..I tried to limit this only for Ribbon using below code where my Ribbon
has only monochrome icons(single color),then it is not applying the theming
strategy.The icons not changing the color for light and dark themes.

    SubstanceCortex.ComponentScope.setIconThemingStrategy(frame.getRibbon(),
                   SubstanceSlices.IconThemingStrategy.FOLLOW_FOREGROUND);

  Also we have JIDE framework integrated in our application.Below is the
design of our application.

[image: image.png]

After integrating Flamingo in our application and I applied
Cremeskin lookandfeel.I have observed few things.

1)Application titlepane is not changing its color based on light theme and
dark theme.
2)All the dockable frame titlepanes/tabs are in white color in dark
theme(Graphite).Di i need to specifically apply color schemes for jide
titlepanes as well?
[image: image.png]
3)Scroll Panes seems to be different
[image: image.png]

Thanks & Regards,
Suhasini

**Comment by kirill-grouchnikov** [comment]
`ComponentScope` APIs only apply for the specific component -  not for its children. In this particular case, you will need to apply the icon theming strategy on every specific component (command buttons probably) that needs to have its icon follow the current Substance theme.

The main reason for not providing this API on the `ComponentOrParentChainScope` is performance considerations of having to scan the entire component hierarchy on every single icon draw.

As for the other questions - I'm not seeing any images here. And since these questions do not appear to be related to this specific bug, please open a separate entry in the bug tracker with correctly inserted images.

**Comment by suhasinisridhar** [comment]
HI Kirill,
   How can I apply ComponentScope ThemingStrategy on taskbar commands.

Thanks & Regards,
Suhasini

**Comment by kirill-grouchnikov** [comment]
Right now there is no support for it. I've filed https://github.com/kirill-grouchnikov/radiance/issues/345

**Comment by suhasinisridhar** [comment]
ok..When Can we expect a fix ? Sorry for bothering you..I have a demo on
Monday so that I can convey the same..

Also I am getting below exception on Show/Hide Ribbon at times and the
Ribbon doesn't show up

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException:
Cannot invoke
"org.pushingpixels.flamingo.api.common.model.CommandMenuContentModel.getCommandGroups()"
because "this.popupMenuContentModel" is null
at
org.pushingpixels.flamingo.api.common.popup.JCommandPopupMenu.populateContent(JCommandPopupMenu.java:111)
at
org.pushingpixels.flamingo.api.common.popup.JCommandPopupMenu.<init>(JCommandPopupMenu.java:88)
at
org.pushingpixels.flamingo.api.ribbon.JRibbonFrame$GlobalPopupMenu.<init>(JRibbonFrame.java:663)
at
org.pushingpixels.flamingo.api.common.projection.Projection.buildComponent(Projection.java:138)
at
org.pushingpixels.flamingo.api.common.projection.AbstractPopupMenuProjection.buildComponent(AbstractPopupMenuProjection.java:49)
at
org.pushingpixels.flamingo.api.ribbon.JRibbonFrame.handlePopupTrigger(JRibbonFrame.java:745)
at
org.pushingpixels.flamingo.api.ribbon.JRibbonFrame.access$400(JRibbonFrame.java:89)
at
org.pushingpixels.flamingo.api.ribbon.JRibbonFrame$1.eventDispatched(JRibbonFrame.java:480)
at
org.pushingpixels.substance.api.SubstanceLookAndFeel.lambda$initialize$0(SubstanceLookAndFeel.java:226)

**Comment by kirill-grouchnikov** [comment]
This is not a general ongoing thread to discuss multiple issues.

A different crash needs a new bug entry in this bug tracker.
