### ISSUE TITLE
Font not loading Japanese or Chinese character set properly.

### ISSUE THREAD

**Issue by DustinMerrell** [kirill-grouchnikov/radiance#335]

**Comment by kirill-grouchnikov** [comment]
You need to fill the requested information, along with sample code and screenshots. Otherwise this will be closed.

**Comment by DustinMerrell** [comment]
Version of Radiance (4.0-SNAPSHOT)
Sub-project (Subtance)
Version of Java (current minimum is 1)
Version of OS - Windows 10 and Mac OS 11
The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
![Substand UI Japanese Character Issue](https://user-images.githubusercontent.com/9554637/117988779-578b0580-b301-11eb-8c15-2ae2ada2c1d1.png)

**Comment by kirill-grouchnikov** [comment]
Again, you need to fill all the requested information. I need to know the version of Radiance you are using.

**Comment by DustinMerrell** [comment]
I am using 4.0. I pulled it about 3 weeks ago.

**Comment by kirill-grouchnikov** [comment]
Is this only happening on that particular environment (Windows 10 + AdoptOpenJDK)?

I'm running this:

```java
public class CJK {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(new SubstanceBusinessLookAndFeel());
            } catch (Exception e) {
            }

            JFrame frame = new JFrame();
            frame.setSize(400, 200);
            frame.setLocationRelativeTo(null);
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            frame.setLayout(new FlowLayout());
            frame.add(new JButton("\u4E01\u4E02\u4E03"));
            frame.add(new JButton("\u30A2\u30B2\u30C2"));

            frame.setVisible(true);
        });
    }
}
```

and it's showing the content correctly on my mac.

**Comment by kirill-grouchnikov** [comment]
Same for AdoptOpenJDK 11.0.11 on my Windows 10

**Comment by DustinMerrell** [comment]
I have been able to work out the issue. It seems to be an issue from converting strings from Resource bundles to UTF8.
Thank you for your time.
