### ISSUE TITLE
Questions on how to Adjust the selected color of Jbutton

### ISSUE THREAD

**Issue by DustinMerrell** [kirill-grouchnikov/radiance#336]
### I am looking for a way to make the selected state of a button more obvious or a different color.
I am using the following Look and Feels
                        UIManager.setLookAndFeel(new SubstanceGraphiteGlassLookAndFeel());
                        UIManager.setLookAndFeel(new SubstanceNightShadeLookAndFeel());

The selected state of buttons is very hard to differentiate with the normal state. 
I am unable to find the documentation that will assist me in changing this color.

I am also having some trouble with text on labels and buttons being cut off with Ellipsis is there a way that I can have the width needed calculated easier because the text works on Javas metal look and feel and the system look and feel.

Thank you for your time.

**Comment by kirill-grouchnikov** [comment]
Graphite Skin uses a lighter shade of grey for filling selected buttons:
<img width="359" alt="buttons-graphite" src="https://user-images.githubusercontent.com/52874/118219825-413b9180-b448-11eb-8ec0-c5c362926b5e.png">

Night Shade skin uses a dark desaturated blue shade for filling selected buttons:
<img width="374" alt="buttons-nightshade" src="https://user-images.githubusercontent.com/52874/118219862-57e1e880-b448-11eb-94b4-0a66714aff21.png">

If you find that this is not enough of a visual distinction for your application, the right places to start would be with:

1. [Component state](https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/substance/skins/componentstates.md) documentation
2. [Color schemes bundle](https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/substance/skins/colorschemebundles.md) documentation
3. [Skin overview](https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/substance/skins/overview.md) documentation

Graphite is one of the [accented Substance skin](https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/substance/skins/overview.md#accented-skins) families. You can see the implementation details of [GraphiteAquaSkin](https://github.com/kirill-grouchnikov/radiance/blob/sunshine/substance/src/main/java/org/pushingpixels/substance/api/skin/GraphiteAquaSkin.java) as it passes one color scheme to be used as accent for components in active states (such as selected), and how that accent color scheme is being used in the base [GraphiteAccentedSkin](https://github.com/kirill-grouchnikov/radiance/blob/sunshine/substance/src/main/java/org/pushingpixels/substance/api/skin/GraphiteAccentedSkin.java) as an example of using the various color scheme bundle APIs (lines 124-126, among the rest).

Night Shade is not an accented skin, so there is no easy way to tweak just the selected state. In that particular case, the recommended approach is to design your own skin based on the documentation linked here, and on the source code of one or more of the core Substance skins as a starting point.

**Comment by kirill-grouchnikov** [comment]
As for the cutoff labels, please file a separate issue for those. That way it is much easier to track separate things in separate places. For that I'll need to see a small, standalone and complete class that reproduces the issue you're seeing.
