### ISSUE TITLE
[Substance] Tooltips' shadows bleed through overlapping windows

### ISSUE THREAD

**Issue by asvitkine** [kirill-grouchnikov/radiance#338]
### Version of Radiance (current development is 4.0-SNAPSHOT)
Substance 3.5.1

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Substance

### Version of Java (current minimum is 9)
16.0.1

### Version of OS
Window 10

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
If you have two windows A and B and a tooltip is shown from A while B is above it, the tooltip's border will bleed window A's contents over.

The screenshot below demonstrates (via https://github.com/triplea-game/triplea which uses Substance):
![Screenshot 2021-05-25 232855](https://user-images.githubusercontent.com/17648/119598657-59e56900-bdb1-11eb-9475-5898268f13f1.png)

In the screenshot, there's a tooltip shown about the mouse-over Tank from the background window and the tooltip correctly displays frontmost, but its border is showing the contents of the background window.

**Comment by kirill-grouchnikov** [comment]
This is coming from the implementation in https://github.com/kirill-grouchnikov/radiance/blob/sunshine/substance/src/main/java/org/pushingpixels/substance/internal/contrib/jgoodies/looks/common/ShadowPopup.java which was taken quite a few years ago from JGoodies' Looks library.

I think the time has come to retire that whole functionality and use whatever tooltip "decoration" (drop shadow or flat) comes from the OS. That would also apply to menus and other popup windows across Radiance-powered components.

**Comment by kirill-grouchnikov** [comment]
Fixed with https://github.com/kirill-grouchnikov/radiance/commit/8c6e9bfe36f4dc456a563dbc1f5ec07358c19d08

**Comment by asvitkine** [comment]
Thanks for the quick fix! I guess this will just make it to the 4.0 release? Or is there a chance to backport it to 3.5.2 or similar?

**Comment by kirill-grouchnikov** [comment]
This will be in 4.0 release. I don't have resources to backport fixes to earlier releases beyond the first week after a release.
