### ISSUE TITLE
Getting look and feel class names from API call

### ISSUE THREAD

**Issue by HavardNJ** [kirill-grouchnikov/radiance#339]
### Version of Radiance (current development is 4.0-SNAPSHOT)
3.5.1
### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Substance
### Version of Java (current minimum is 9)
Irrelevant
### Version of OS
Irrelevant
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
More of a feature suggestion, I'm using UIManager.getInstalledLookAndFeels() to get available system look and feels, then use lookAndFeelInfo.getName() and lookAndFeelInfo.getClassName() to allow the user to select a look and feel and use UIManager.setLookAndFeel(getSelectedLookAndFeelClassName()). I'd like to use the same pattern with Substance where I can use f.ex. UIManager.setLookAndFeel("org.pushingpixels.substance.api.skin.SubstanceGraphiteLookAndFeel") and I can get a list of skins using getAllSkins() however the getClassName() in SkinInfo gives me the class name of the skin and not the look and feel class. AFAICS from the docs and skimming through the code there is no function which give me a list of the look and feel classes. I could handle this by building the look and feel class name from string patterns using the skininfo display name or using reflection to get subclasses of SubstanceLookAndFeel or by having a switch where I handle substance looks and feel by setSkin rather than UIManager.setLookAndFeel(). However having a getSubstanceLookAndFeels() would result in cleaner code on my side.

**Comment by kirill-grouchnikov** [comment]
With https://github.com/kirill-grouchnikov/radiance/commit/55a884bdb6275f4f3e58037a61f0db15bc37f8cc `SkinInfo` has the new `getLookAndFeelClassName()` API that returns the fully qualified class name of the look-and-feel class that can be used with `UIManager.setLookAndFeel` Swing API.
