### ISSUE TITLE
height of plain text in JOptionPane.show***Dialog is not sufficient (Linux OS, Substance Look and Feel)

### ISSUE THREAD

**Issue by goodwilling** [kirill-grouchnikov/radiance#342]
### Version of Radiance (current development is 4.0-SNAPSHOT)
2.0

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Substance

### Version of Java (current minimum is 9)
8

### Version of OS
Linux (Redhat/CentOS 7 and 8)

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
The height of plain text in JOptionPane.show***Dialog seems to be not sufficient, as the bottom of some letters (g, p, q, y) can not be shown. This problem does not occur on Windows OS.  Also, it does not occur using
![text in dialog](https://user-images.githubusercontent.com/56999195/120926861-94d48e80-c719-11eb-9fec-61ba3bec04ae.PNG)
 Metal Look and Feel.

**Comment by kirill-grouchnikov** [comment]
Radiance 2.0 on Java 8 is too old for me to support.

Release 4.0 is right around the corner. Does it happen there? If so, I'll need to see a full screenshot, along with a small standalone test class that shows this issue.

**Comment by goodwilling** [comment]
Thanks.  This problem is solved using the latest version compiled with Java 9 and it works in Java 11.

**Comment by kirill-grouchnikov** [comment]
Thanks for verifying
