### ISSUE TITLE
Photon SvgBatchConverter ClassNotFound

### ISSUE THREAD

**Issue by Sptele** [kirill-grouchnikov/radiance#349]
### Radiance Version
**Radiance Version: 4.0.0**

### Subproject
**Sub-Project: Photon**

### Java Version
**Java version: 1.9 (11 didn't work)**

### Operating System
**OS version: Windows 10 Home**

### Issue
I am trying to use the Photon SvgBatchConverter, but it doesn't seem to be working. I tried following your guide here: #237, but I am running into a ClassNotFoundException:

![image](https://user-images.githubusercontent.com/79765399/124341765-afacee00-db73-11eb-91f8-440f110bd7cb.png)

How would I resolve this issue? (I have already downloaded the necessary jars into the directory)

**Comment by kirill-grouchnikov** [comment]
Can you run `jar tvf ./radiance-photon-4.0.0.jar` when you're in the same directory and see if `SvgBatchConverter` is there?

**Comment by Sptele** [comment]
Hello, 
I ran the command, and located the SvgBatchConverter class:
![image](https://user-images.githubusercontent.com/79765399/124369609-3fa97100-dc22-11eb-8c21-25656835d726.png)

**Comment by kirill-grouchnikov** [comment]
can you paste the contents of the folder to make sure that the jars are there?

**Comment by kirill-grouchnikov** [comment]
This is the right command - https://github.com/kirill-grouchnikov/radiance/blob/sunshine/scripts/convert-svg.sh

Note that on Windows you need to use ; instead of : for separating multiple jars on the classpath

**Comment by Sptele** [comment]
Ok, thanks!

Here are the contents of my "test" directory:
![image](https://user-images.githubusercontent.com/79765399/124370139-c2cdc580-dc28-11eb-918c-33c3d81db6e8.png)

**Comment by Sptele** [comment]
Actually, after using ;'s instead of :, the terminal gave me the help response for the java command, and opened the Batik Squiggle applet:
![image](https://user-images.githubusercontent.com/79765399/124370191-5d2e0900-dc29-11eb-80a0-a661faea8385.png)

Here is the updated command I used (java help included):
![image](https://user-images.githubusercontent.com/79765399/124370199-7b940480-dc29-11eb-8f06-7002596a1014.png)

**Comment by kirill-grouchnikov** [comment]
Looks like this is somehow launching the Squiggle class from Batik distribution - https://xmlgraphics.apache.org/batik/tools/browser.html

**Comment by kirill-grouchnikov** [comment]
Just tested this on my Windows machine:

1. Get the latest snapshot from Github
2. Build with `gradlew`
3. Copy all the jars with `gradlew copyJars`
4. Get all dependencies with `gradlew getAllDependencies`

Run this command from `scripts` folder (but the location doesn't matter):

`java -cp ../drop/4.5-SNAPSHOT/core/radiance-photon-4.5-SNAPSHOT.jar;../build/libs-core/batik-all-1.14.jar;../build/libs-core/xml-apis-1.4.01.jar;../build/libs-core/xml-apis-ext-1.3.04.jar;../build/libs-core/xmlgraphics-commons-2.6.jar org.pushingpixels.photon.api.transcoder.SvgBatchConverter sourceFolder=../demos/plasma-demo/src/main/kotlin/org/pushingpixels/demo/plasma/svg outputPackageName=org.pushingpixels.demo.plasma.svg templateFile=/org/pushingpixels/photon/api/transcoder/kotlin/SvgTranscoderTemplateResizable.templ outputLanguage=kotlin`

**Comment by kirill-grouchnikov** [comment]
Using this version of Java:

```
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

**Comment by kirill-grouchnikov** [comment]
Also works for me with 4.0.0 version of Photon jar downloaded from https://github.com/kirill-grouchnikov/radiance/tree/sunshine/drop/4.0.0/core

**Comment by Sptele** [comment]
Hi, unfortunately I will be out of town for a bit. I will try this when I get back. Thanks for all of your help!

**Comment by kirill-grouchnikov** [comment]
You'll need to check the general documentation on how to run Java with multiple jars in the classpath on your environment.
