### ISSUE TITLE
Automatic-Module-Name

### ISSUE THREAD

**Issue by gLuEcKsKrAuT** [kirill-grouchnikov/radiance#360]
### Version of Radiance (current development is 4.5-SNAPSHOT)
4.0.0

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

Hi there,

I want to use the radiance-artifacts within a modular build,
it would be nice if you can add a Automatic-Module-Name in the manifest.

gradle have some trouble to compile without it.

best regards

**Comment by kirill-grouchnikov** [comment]
Do you have an example of how this should look like in the Gradle build?

**Comment by gLuEcKsKrAuT** [comment]
[automatic-module-example.zip](https://github.com/kirill-grouchnikov/radiance/files/6945756/automatic-module-example.zip)

**Comment by kirill-grouchnikov** [comment]
I have no idea what this project is. If that's from the consumer side of things, that's not what I was asking. How is this supposed to look like on the provider side of things? 

https://jlbp.dev/JLBP-20 is one of the first results, but it's not clear if every module needs its own unique module name or not.

**Comment by gLuEcKsKrAuT** [comment]
Sorry for that, reading ...

Yes, a unique name is required for the modules.

I can only speak for the radiance-java modules / gradle-(sub)projects. 
Here it should be enough to use the already existing POM_ARTIFACT_ID.

```
build.gradle

// Configure the jar task for all the projects
    tasks.withType(Jar) {
        // create reproducible builds by removing timestamps and doing cross-platform file order
        preserveFileTimestamps = false
        reproducibleFileOrder = true
        archiveBaseName = "${rootProject.name}-${project.name}"

        manifest {
            // add radiance version, build JDK and build JDK vendor into the manifest file
            attributes(
                 "Radiance-Version": "${findProperty('VERSION_NAME')} [${findProperty('CODENAME')}]",
                 "Build-JDK": System.getProperty('java.version'),
                 "Build-JDK-Vendor": System.getProperty('java.vendor'),

                 // Automatic-Module-Name
                 "Automatic-Module-Name": "${findProperty('POM_ARTIFACT_ID')}".replace("-",".") 
            )
        }
    }
```

**Comment by kirill-grouchnikov** [comment]
There's an entry like this now in all manifests in 4.5-SNAPSHOT:

`Automatic-Module-Name: org.pushing-pixels.radiance-neon`

The name matches the maven coordinates of each module

**Comment by gLuEcKsKrAuT** [comment]
Thank you for the patch.

I edited my last comment. 
the automatic-module name have to be a fully qualified class name,
there are no "-" allowed.

```
build.gradle
```

this 
```
"Automatic-Module-Name": "org.pushing-pixels." + "${findProperty('POM_ARTIFACT_ID')}")

e.g. 
-> org.pushing-pixels.radiance-neon
```

should be replaced by this (or something similar)

```
"Automatic-Module-Name": ("org.pushing-pixels." + "${findProperty('POM_ARTIFACT_ID')}").replace("-","."))

e.g.
-> org.pushing.pixels.radiance.neon
```

best regards

**Comment by kirill-grouchnikov** [comment]
It is like this now:

`Automatic-Module-Name: org.pushingpixels.radiance.neon`

**Comment by gLuEcKsKrAuT** [comment]
Thank you, works as expected.

**Comment by kirill-grouchnikov** [comment]
Thanks for verifying. I'll upload the binaries to Sonatype tonight
