### ISSUE TITLE
[Substance] Incosistent rollover logic for table cells

### ISSUE THREAD

**Issue by goodwilling** [kirill-grouchnikov/radiance#361]
### Version of Radiance (current development is 4.5-SNAPSHOT)
4.5-SNAPSHOT

### Sub-project (Neon, Trident, Substance, Flamingo, ...)
Substance

### Version of Java (current minimum is 9)
Java 11

### Version of OS
Windows 10 Pro

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
In Substance look and feel with Nebula or NebulaBrickWall,  if the column and row of a JTable are both highlighted, the highlighted row is difficult to be read due to the contrast problem. Such problems do not exist in other schemes (e.g. Mariner). 
![highlight-problems](https://user-images.githubusercontent.com/56999195/130251156-633b3783-dd46-482a-b507-e5a9701c6e65.PNG)

**Comment by kirill-grouchnikov** [comment]
Can you provide a code snippet that shows this issue?

**Comment by kirill-grouchnikov** [comment]
Highlights should all be consistent with both background colors and the text color. This is I need to understand the app code behind this. Is it table selection (row, column, individual cells) or mouse rollover, or something else.

**Comment by goodwilling** [comment]
Sorry, I am not clear how to  provide a code snippet to show this issue, as our app is a complicated one. It seems that the mouse rollover is responsible for this issue.  If only a row or only a column is highlighted with the mouse rollover, no problem occurs. However,  the problem occurs if both column and row are highlighted with the mouse rollover.  Thanks.

**Comment by kirill-grouchnikov** [comment]
There is not enough information here for me to be able to do anything. I need to know exactly how a whole row **and** a whole column get highlighted in your app.

**Comment by goodwilling** [comment]
How a whole row and a whole column get highlighted is really a puzzle in our app, which uses the following initial settings:
             table.setRowSelectionAllowed(false);
             table.setColumnSelectionAllowed(true);
             ...
            table.setRowSelectionInterval(0, table.getRowCount() - 1);
The above settings  have different effects for tables with different data.  After some tests, it is found that a whole row and a whole column get highlighted only when there are many rows with a vertical scrollbar.  Without such a vertical scrollbar, only a whole column is highlighted.  The same phenomena can also be reproduced in CentOS 8. Thanks.

**Comment by kirill-grouchnikov** [comment]
I can reproduce this

**Comment by kirill-grouchnikov** [comment]
There are two separate places in the `JTable` UI delegate that compute the cell state (rollover / selected), and they were doing a slightly different logic for the rollover state. With the change that just went in, both places are now consistent, and the issue of incorrect highlights should be gone.

However, this is probably going to "break" your expectation now. When you call `JTable.setRowSelectionAllowed(false)`, Substance treats that as "no rollovers on the entire row". This was incorrectly implemented before, and is now fixed. Calling `JTable.setRowSelectionInterval` has no bearing on this - see `JTable.isCellSelected` logic.

Substance is now aligned with Metal as far as displaying highlights on selected cells / rows / columns with different permutations of these three calls. It is also aligned with that selection logic on rollovers as well.
