### ISSUE TITLE
Moving window from scaled screen to non-scaled screen

### ISSUE THREAD

**Issue by per-erik** [kirill-grouchnikov/radiance#367]
### Version of Radiance
Tested on 5.0.0 but probably holds true all the way back to substance.

### Sub-project
Theming

### Version of Java (current minimum is 9)
17.0.1 (Oracle's build) but probably holds true back to when they solved https://bugs.openjdk.java.net/browse/JDK-8211999
64-bit VM

### Version of OS
Windows 10 Pro 20H2 (Build 19042.1288)
x64

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
Opening a laf-decorated JFrame with RadianceBusinessLookAndFeel on a screen that is scaled to anything but 100% and then moving that frame to a monitor with 100% scaling makes the frame jump up and to the right slightly, just before WWindowPeer gets a call that the display has changed (after which the frame gets connected to a new GraphicsConfiguration and therefore gets a new AffineTransform with 100% scaling and "jumps back" to where it should be). This behavior is consistent with how Metal behaves but is still wrong. I believe the underlying cause may very well be that awt is buggy on Windows.

The GIF below attempts to show what happens, although I have no good screen capturing application to record multiple screens. The JFrame is on a scaled display and move to the edge. To the left of that edge is another display with 100% scaling. Just before the JFrame is actually "sent" to that display, the JFrame jumps up and to the right slightly. 

![jumping-jframe](https://user-images.githubusercontent.com/1173670/140473452-0569e6ad-8d3b-4aa0-a6f1-83a8093e2465.gif)

The same attempt with a system-decorated JFrame (expected behavior):

![non-jumping-jframe](https://user-images.githubusercontent.com/1173670/140474260-2a054be0-d12e-4e15-a370-f625cf4aa4db.gif)

**Comment by kirill-grouchnikov** [comment]
Does this happen with other look-and-feels that support decorated mode, such as Metal?

I don't have a setup to reproduce this issue, so if this is Radiance-specific, it would need to be addressed by the community.

**Comment by per-erik** [comment]
Yes, it happens in all L&Fs that I have tested, Metal included (as I wrote in the bug description). I will file a bug on OpenJDK when I get back to work. This report was mostly to inform the Radiance team that the bug exists and it is likely a bug in the JDKs native code so I don't expect Radiance to do much about it. Maybe there's a workaround but I can't come up with one since there is no event or state to poll that would help differentiate between when it works and when it doesn't.

What I have found is that if you move the window using the GraphicsConfiguration's default AffineTransform (using its scale to multiply the mouse events' screen location) it will not behave as in the GIFs. However, that will (obviously) make the window move unexpectedly on the screen that has a DPI scaling set (but the window will no longer "jump" just prior to switching displays). So that would work as a workaround except that I have found no way of knowing when to apply the transform and when not to. But it semi-confirms my suspicion that this has to do with how AWT handles multiscreen setups where the screens have different DPI scaling - on Windows.

**Comment by kirill-grouchnikov** [comment]
To be honest, I don't like leaving bugs open when there's no solution that can be done on the side of Radiance.

Probably the most useful would be to create a new label, something like jdkbugs, mark this issue with it and then close it.
