### ISSUE TITLE
[Animation] Choppy animations, especially on higher refresh rates

### ISSUE THREAD

**Issue by Tajmoti** [kirill-grouchnikov/radiance#380]
### Version of Radiance (latest development is 6.0-SNAPSHOT)
6.0-SNAPSHOT

### Sub-project (Common, Animation, Theming, Component, ...)
Animation

### Version of Java (current minimum is 9)
Any

### Version of OS
Any

#### Expected:
Animations should be as smooth as possible by default
#### Actual:
The `DefaultPulseSource` uses 40 ms as the delay between pulses. This arbitrary delay is pretty large and it causes animations to be  a bit choppy on high refresh-rate monitors.

I don't find the hardcoded 40 ms to be a good default. I propose to derive the default delay from the connected display refresh rate.

**Comment by Tajmoti** [comment]
I've made a video to compare the behavior before and after the change in the PR.
Focus on the dropdown menu - the highlighting of items skips noticeably in the window on the left.

_I set `timelineDuration` to zero to better show the effect, but it's very noticeable even with animations enabled._

https://user-images.githubusercontent.com/8780592/150665488-54e7f1c4-f662-4394-b667-0745738716be.mp4

**Comment by kirill-grouchnikov** [comment]
PR merged. Thanks!

**Comment by kirill-grouchnikov** [comment]
Marking as breaking change since this has removed the existing public API.

**Comment by Tajmoti** [comment]
What public API has this removed? The only removed class is `DefaultPulseSource`, which was `private` in `RadianceAnimationCortex`.

**Comment by kirill-grouchnikov** [comment]
Yes, you are right, it was private - https://github.com/kirill-grouchnikov/radiance/blob/v5.0.0/animation/src/main/java/org/pushingpixels/radiance/animation/api/RadianceAnimationCortex.java#L78

Removing the label
