### ISSUE TITLE
[SVG transcoder] Kotlin instructions for the svg transcoder plugin

### ISSUE THREAD

**Issue by bric3** [kirill-grouchnikov/radiance#382]
### Version of Radiance 
5.0.0

### Sub-project
org.pushing-pixels:radiance-svg-transcoder-gradle-plugin

### Version of Java
11

### Version of OS
macOs 12.3

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
Doc

----

The documentation to use the plugin with Gradle Kotlin DSL is a tad different. Also it would be nice if the plugin was available on https://plugin.gradle.com because there's some restriction on `buildscript` that may be difficult to overcome in larger projects.

Anyway here's what I came up withwith a kotlin script :

```kotlin
import org.pushingpixels.radiance.tools.svgtranscoder.gradle.TranscodeTask

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.pushing-pixels:radiance-svg-transcoder-gradle-plugin:5.0.0")
    }
}

apply(plugin = "org.pushing-pixels.radiance.tools.svgtranscoder.gradle")

dependencies {
    implementation("org.pushing-pixels:radiance-common:5.0.0")
}

tasks.create<TranscodeTask>("transcodeSvgIcons") {
    inputDirectory = file("src/main/resources")
    outputDirectory = file("src/main/java/org/radiance/demo/svg")
    outputLanguage = "java"
    outputPackageName = "org.radiance.demo.svg"
    isUseRadianceTemplate = false
    transcode()
}

tasks.compileJava {
    dependsOn("transcodeSvgIcons")
}

// kotlin sources also depends on these java classes
tasks.compileKotlin {
    dependsOn("transcodeSvgIcons")
}
```

**Comment by kirill-grouchnikov** [comment]
I'll need more info on this part: `Also it would be nice if the plugin was available on https://plugin.gradle.com/ because there's some restriction on buildscript that may be difficult to overcome in larger projects` before I go and commit to publishing to multiple places.

**Comment by kirill-grouchnikov** [comment]
See https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/tools/svg-transcoder/svg-transcoder-gradle-plugin.md#using-the-plugin-in-your-gradle-script-kotlin-dsl-flavor for `build.gradle.kts` instructions.

For potential publishing outside of Maven Central, please file a new bug. Note that I'll need a good reason to publish this plugin to multiple places.

**Comment by bric3** [comment]
Cool thanks for updating the doc :)

> For potential publishing outside of Maven Central, please file a new bug. Note that I'll need a good reason to publish this plugin to multiple places.

For one thing, it's that https://plugins.gradle.org (sorry I made typos in the original description), it's more discoverable.
And it simplifies a lot the consumption of the plugin, e.g. one can just write something like that : 

```kotlin
plugins {
    id("radiance-svg-transcoder") version "X.Y.Z"
}
```

Also one of the issue is that a gradle project can't have multiple buildscript, and managing multiple multiple plugins with buildscript is cumbersome.

Here's more documentation : https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html

Anyway I'll open an issue in that regard.
Thanks for discussing the topic :)
