### ISSUE TITLE
[SVG Transcoder] Remove plain template

### ISSUE THREAD

**Issue by bric3** [kirill-grouchnikov/radiance#383]
### Version of Radiance (latest development is 6.0-SNAPSHOT)
5.0.0

### Sub-project (Common, Animation, Theming, Component, ...)
svg-transcoder

### Version of Java (current minimum is 9)
11

### Version of OS
macOs 12.3

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
The generated code with the plain template is incorrect as code has references to `colorFilter` : 

```java
// _0_0
shape = new Ellipse2D.Double(7.0, 7.0, 10.0, 10.0);
paint = (colorFilter != null) ? colorFilter.filter(new Color(0, 0, 0, 255)) : new Color(0, 0, 0, 255);
g.setPaint(paint);
g.fill(shape);
```

This field reference can be found in the Radiance template :

https://github.com/kirill-grouchnikov/radiance/blob/46319b1f53dc3ad75e81d5fff8af13d910100b2c/tools/svg-transcoder/src/main/resources/org/pushingpixels/radiance/tools/svgtranscoder/api/java/SvgTranscoderTemplateRadiance.templ#L27

It's initialized there.

https://github.com/kirill-grouchnikov/radiance/blob/46319b1f53dc3ad75e81d5fff8af13d910100b2c/tools/svg-transcoder/src/main/java/org/pushingpixels/radiance/tools/svgtranscoder/api/SvgBaseTranscoder.java#L228-L233

But it's not there in the plain template.

However the `colorFilter` is used regardless of the template.

https://github.com/kirill-grouchnikov/radiance/blob/46319b1f53dc3ad75e81d5fff8af13d910100b2c/tools/svg-transcoder/src/main/java/org/pushingpixels/radiance/tools/svgtranscoder/api/SvgBaseTranscoder.java#L453

https://github.com/kirill-grouchnikov/radiance/blob/46319b1f53dc3ad75e81d5fff8af13d910100b2c/tools/svg-transcoder/src/main/java/org/pushingpixels/radiance/tools/svgtranscoder/api/SvgBaseTranscoder.java#L854

https://github.com/kirill-grouchnikov/radiance/blob/46319b1f53dc3ad75e81d5fff8af13d910100b2c/tools/svg-transcoder/src/main/java/org/pushingpixels/radiance/tools/svgtranscoder/api/SvgBaseTranscoder.java#L920

https://github.com/kirill-grouchnikov/radiance/blob/46319b1f53dc3ad75e81d5fff8af13d910100b2c/tools/svg-transcoder/src/main/java/org/pushingpixels/radiance/tools/svgtranscoder/api/SvgBaseTranscoder.java#L963

**Comment by kirill-grouchnikov** [comment]
This is actually a good time to remove the plain template altogether.

That template is a more of a curiosity and would need additional app-side code to configure the size of the icon, for each icon - that is something that comes built-in with the `RadianceIcon`.

I don't really want to start having some sort of a feature-aware template system, where a template can specify (via command-line flags in any case, so no much of a system) which extra features it supports - such as color filtering. It's certainly possible to start with this one-off and not emit the color filtering instructions, but I don't want to go down that road.

In general, I view Radiance as a cohesive set of libraries, and bundling a plain template breaks that cohesion.
