### ISSUE TITLE
Upload SVG transcoder Gradle plugin on the Gradle Plugin portal

### ISSUE THREAD

**Issue by bric3** [kirill-grouchnikov/radiance#384]
### Version of Radiance (latest development is 6.0-SNAPSHOT)
5.0.0

### Sub-project (Common, Animation, Theming, Component, ...)
org.pushing-pixels:radiance-svg-transcoder-gradle-plugin

### Version of Java (current minimum is 9)
11

### Version of OS
macOs 12.3

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
So it's about a usage enhancement.

The plugin is already uploaded to maven central.
However its usage requires to declare a `buildscript`, or worse deal with existing `buildscript`. A buildscript is a piece in Gradle that can make writing build files way less flexible than other mechanisms.
Nowadays Gradle promote the use of the `plugins` block for quite some time to declare plugins. E.g.

```kotlin
plugins {
    id("radiance-svg-transcoder") version "X.Y.Z"
}
```

However the plugin has to be uploaded to the official Gradle plugin portal.
There's a guide on how to do that &rArr; https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html

This issue has been created following the suggestion in this https://github.com/kirill-grouchnikov/radiance/issues/382#issuecomment-1072819629

Also, here a verbatim of another https://github.com/kirill-grouchnikov/radiance/issues/382#issuecomment-1072886238

------

> For potential publishing outside of Maven Central, please file a new bug. Note that I'll need a good reason to publish this plugin to multiple places.

For one thing, it's that https://plugins.gradle.org (sorry I made typos in the original description), it's more discoverable.
And it simplifies a lot the consumption of the plugin, e.g. one can just write something like that : 

```kotlin
plugins {
    id("radiance-svg-transcoder") version "X.Y.Z"
}
```

Also one of the issue is that a gradle project can't have multiple buildscript, and managing multiple multiple plugins with buildscript is cumbersome.

Here's more documentation : https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html

**Comment by kirill-grouchnikov** [comment]
```
> Task :tools:svg-transcoder-gradle-plugin:publishPlugins FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tools:svg-transcoder-gradle-plugin:publishPlugins'.
> -SNAPSHOT plugin versions not supported, please use a fixed version instead.
```

This is not ideal. No way to publish dev / snapshot versions of the plugin?

**Comment by kirill-grouchnikov** [comment]
Doesn't look like they support hosting snapshot versions. That is a deal breaker for me. I'll be reverting this last CL and closing this feature request as do not fix.

**Comment by bric3** [comment]
Arg too bad, thanks for looking to it!
