### ISSUE TITLE
Issue with resizing of JIDE Windows 

### ISSUE THREAD

**Issue by suhasinisridhar** [kirill-grouchnikov/radiance#385]
Radiance Version #4.0.0

Sub-project - Substance

Version of Java - Java15 /Java17

Version of OS - Windows 10
In our application we have radiance Ribbon bar/Substance and  JIDE dockable frames integrated. Seeing issue with resizing the dockable frames when rootpane border color is overridden using below snippet.

UIManager.put("RootPane.border", new LineBorder(Color.RED));
and
JFrame.setDefaultLookAndFeelDecorated(true);

 
While resizing dockable frames, the window continuously moving down until the mouse drag is on.This is observed with Substance theme.I have tried same thing with out substance with Jide examples and I don't see issue there

**Comment by kirill-grouchnikov** [comment]
Does this happen under the latest version of Radiance (6.0-SNAPSHOT branch)?

You also say that this does not happen without Substance. Did you try it under other look-and-feels that support undecorated mode, such as Metal, FlatLaf or DarkLaf?

**Comment by suhasinisridhar** [comment]
I haven't tried with  6.0-SNAPSHOT .

I have attached the reproducible case in another email.

**Comment by kirill-grouchnikov** [comment]
I'll need to see the smallest reproducible case that shows this issue under the latest Radiance version.

Also, note that Radiance **does not** support setting a custom root pane border through UIManager calls, and doing so can lead to unpredictable and unsupported behavior.

**Comment by kirill-grouchnikov** [comment]
Closing as no requested information has been provided.
