### ISSUE TITLE
Doc link broken/outdated in Animation

### ISSUE THREAD

**Issue by jfree** [kirill-grouchnikov/radiance#386]
### Version of Radiance (latest development is 6.0-SNAPSHOT)
Latest

### Sub-project (Common, Animation, Theming, Component, ...)
Animation 

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
In the docs here https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/animation/animation.md there is a link for the `EventDispatchThread` that goes to a page that appears to not exist anymore
http://www.javaworld.com/javaworld/jw-08-2007/jw-08-swingthreading.html

**Comment by kirill-grouchnikov** [comment]
Looks like it moved to https://www.javaworld.com/article/2077754/swing-threading-and-the-event-dispatch-thread.amp.html but hasn't really aged well. I'll just link to https://docs.oracle.com/javase/tutorial/uiswing/concurrency/index.html instead
