### ISSUE TITLE
[Theming] Tabbed pane with scroll tab layout incorrectly shows the (partially configured) scroll buttons

### ISSUE THREAD

**Issue by ed-erwin-tf** [kirill-grouchnikov/radiance#398]
### Windows 10

The UI for JTabbedPane acts strangely in 6.0 snapshot.  The problem did not exist in 5.0.

One problem can be reproduced by using the Swing tutorial class TabbedPaneDemo from here:
https://docs.oracle.com/javase/tutorial/uiswing/components/tabbedpane.html

When run under default LAF, there are four tabs.
When run under Radiance 6.0, there are six tabs, but two are empty.   You can see the tabs by hovering the mouse to the right of the 4th tab.

I am having a problem with JTabbedPane in my large application.  I hope that whatever causes this bug is also causing the bug in my program.

![ghost tabs](https://user-images.githubusercontent.com/89803685/185008604-5ba800e8-c2dc-4c92-8374-fb443d892864.PNG)

**Comment by kirill-grouchnikov** [comment]
Not seeing this with the latest 6.0-SNAPSHOT on Windows 10 and Java 9 from Oracle:

```
public class TabsBug extends JFrame {
    protected JComponent makeTextPanel(String text) {
        JPanel panel = new JPanel(false);
        JLabel filler = new JLabel(text);
        filler.setHorizontalAlignment(JLabel.CENTER);
        panel.setLayout(new GridLayout(1, 1));
        panel.add(filler);
        return panel;
    }

    /**
     * Creates the main frame for <code>this</code> sample.
     */
    public TabsBug() {
        super("Tabbed pane close callback");

        this.setLayout(new BorderLayout());

        // create tabbed pane with a few tabs
        JTabbedPane tabbedPane = new JTabbedPane();

        JComponent panel1 = makeTextPanel("Panel #1");
        tabbedPane.addTab("Tab 1", null, panel1,
                "Does nothing");
        tabbedPane.setMnemonicAt(0, KeyEvent.VK_1);

        JComponent panel2 = makeTextPanel("Panel #2");
        tabbedPane.addTab("Tab 2", null, panel2,
                "Does twice as much nothing");
        tabbedPane.setMnemonicAt(1, KeyEvent.VK_2);

        JComponent panel3 = makeTextPanel("Panel #3");
        tabbedPane.addTab("Tab 3", null, panel3,
                "Still does nothing");
        tabbedPane.setMnemonicAt(2, KeyEvent.VK_3);

        JComponent panel4 = makeTextPanel(
                "Panel #4 (has a preferred size of 410 x 50).");
        panel4.setPreferredSize(new Dimension(410, 50));
        tabbedPane.addTab("Tab 4", null, panel4,
                "Does nothing at all");
        tabbedPane.setMnemonicAt(3, KeyEvent.VK_4);

        this.add(tabbedPane, BorderLayout.CENTER);

        this.setSize(400, 200);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * The main method for <code>this</code> sample. The arguments are ignored.
     * 
     * @param args
     *            Ignored.
     */
    public static void main(String[] args) {
        JFrame.setDefaultLookAndFeelDecorated(true);
        SwingUtilities.invokeLater(() -> {
            RadianceThemingCortex.GlobalScope.setSkin(new BusinessBlackSteelSkin());
            new TabsBug().setVisible(true);
        });
    }
}
```

**Comment by kirill-grouchnikov** [comment]
Same with Corretto 11 from https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html

Not seeing this on my Windows 10 machine

**Comment by kirill-grouchnikov** [comment]
OK, I see it with https://docs.oracle.com/javase/tutorial/uiswing/examples/components/TabbedPaneDemoProject/src/components/TabbedPaneDemo.java

**Comment by kirill-grouchnikov** [comment]
Those "empty" tabs are from `tabbedPane.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT)` - which should be displaying the scroller buttons if the tabs don't fit. But in this particular case it shouldn't display anything in there since everything fits.

This will be fixed for the final 6.0 release

**Comment by ed-erwin-tf** [comment]
Thanks,

I suppose you are correct that in this demo there are not actually 2 extra tabs.  But if you do things a little bit differently, then there will be two extra tabs.

Using that `TabbedPaneDemo `class, if you set `SCROLL_TAB_LAYOUT` prior to adding any tabs, then it actually adds two additional tabs, so that  `tabbedPane.getTabCount()` returns 6 instead of 4.

If you then use  this code:
```
    int count = tabbedPane.getTabCount();
    for (int i=0; i< count; i++) {
      Component c = tabbedPane.getComponent(i);
      System.out.println("" + i + "  " + c);
    }
```

then you will see this output:
```
0  class org.pushingpixels.radiance.theming.internal.ui.RadianceTabbedPaneUI$1
1  class org.pushingpixels.radiance.theming.internal.ui.RadianceTabbedPaneUI$1
2  class javax.swing.plaf.basic.BasicTabbedPaneUI$ScrollableTabViewport
3  class javax.swing.JPanel
4  class javax.swing.JPanel
5  class javax.swing.JPanel
```

I would like to get a chance to try a snapshot after you have added a fix, to see whether the fix works in my application.
Thanks!

**Comment by kirill-grouchnikov** [comment]
The latest snapsot is available on Sonatype now

**Comment by ed-erwin-tf** [comment]
Thank you.  This does fix the issue.
