### ISSUE TITLE
Application menu - round button

### ISSUE THREAD

**Issue by szitnik** [kirill-grouchnikov/radiance#399]
I am upgrading my application from pre-1.0.0 substance/flamingo builds to Radiance 5.0.0 (btw: thanks a lot for having such a nice library!). 

I cannot get a big rounded button to the application menu (i.e., similar as here: https://github.com/kirill-grouchnikov/radiance/blob/sunshine/demos/component-demo/src/main/resources/org/pushingpixels/radiance/demo/component/ribbon/appmenubutton-tooltip-main.png).

As currently text parameter is obligatory when creating projection, I am interested whether having such a button is still supported or am I missing something?

**Comment by kirill-grouchnikov** [comment]
The original round application button design was replaced with the more traditional rectangular button. It's in the same location, but a bit more discoverable as a button affordance. There is no API to get the old look.
