### ISSUE TITLE
[Lumen] Bring Onyx to be under Radiance

### ISSUE THREAD

**Issue by kirill-grouchnikov** [kirill-grouchnikov/radiance#40]
https://github.com/kirill-grouchnikov/onyx

- Modernize [the usage](https://docs.oracle.com/javase/tutorial/uiswing/misc/trans_shaped_windows.html) of AWTUtilities
- Switch to the latest iteration of MusicBrainz APIs
- Switch from manual XML parsing to Retrofit
- Migrate to Kotlin to validate what needs to be done to expose Trident APIs in Kontos

**Comment by kirill-grouchnikov** [comment]
Also use Neon APIs for high-DPI / platform support (album art, text rendering, all visuals)

**Comment by kirill-grouchnikov** [comment]
Onyx will stay in Java for now. The port to Kotlin will probably be the same as flamingo demos under flamingo-demo and kormorant-demo - a separate, parallel project that will be Kotlin-native. Tentatively named Karbon.

**Comment by kirill-grouchnikov** [comment]
Actually, Onyx (and Karbon) are not good names anymore, since they are clashing with the top-level release codename scheme. 

Onyx will be renamed shortly to Lumen. The Kotlin version will be Kandle.

**Comment by kirill-grouchnikov** [comment]
https://github.com/kirill-grouchnikov/radiance/commit/f461a7b5ff53d1a88a59c55a3e32b3aa5a52bb8a

**Comment by kirill-grouchnikov** [comment]
![lumen-tour](https://user-images.githubusercontent.com/52874/44618823-71334880-a84b-11e8-9ff0-8fdc7889c10c.gif)

**Comment by brunchboy** [comment]
Very impressive!
