### ISSUE TITLE
Let us hide close buttons

### ISSUE THREAD

**Issue by ScoreUnder** [kirill-grouchnikov/radiance#401]
### Version of Radiance (latest development is 6.0-SNAPSHOT)

5.0.0 but I have been reading the source of the tree at 5addb520adb338b31824e77fa267438e4db48872

### Sub-project (Common, Animation, Theming, Component, ...)

Theming

### Version of Java (current minimum is 9)

18, targeting 11

### Version of OS

Arch Linux

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

I would like to hide the close button on some windows (i.e. progress dialogs that should only have a "cancel" button), but there doesn't seem to be a way to do this. Granted, there isn't in the rest of Swing either, but since you have the power to change it that would be nice to have. My current approach is as follows, but relies on an explicitly non-API class:

```kt
    private fun removeCloseButton() {
        rootPane.findSubComponent {
            it is JComponent && it.getClientProperty(RadianceButtonUI.IS_TITLE_CLOSE_BUTTON) == true
        }?.isVisible = false
    }

    private fun Container.findSubComponent(action: (Component) -> Boolean): Component? {
        val queue = LinkedList<Component>()
        queue.add(this)

        while (queue.isNotEmpty()) {
            val component = queue.poll()

            if (action(component)) {
                return component
            }

            if (component is Container) {
                queue.addAll(component.components)
            }
        }

        return null
    }
```

**Comment by kirill-grouchnikov** [comment]
I don't want to make it easy to create actively user-hostile UIs. Every frame and dialog should have a close button. 

That client property is an internal one, and is scheduled to be removed in the next version - as it serves no purpose in the codebase. Internal code that relied on it was removed, so there's nothing that "reads" the presence of that property. I would highly suggest not removing close buttons from your top-level frames, but instead re-evaluating the approach.

**Comment by ScoreUnder** [comment]
I am removing them from progress dialogs. It is not user-hostile; removing the dialog from the screen only hides the fact that an operation is in progress and will surprise the user when it completes. They should instead click the cancel button if they want to cancel the operation.

**Comment by ScoreUnder** [comment]
Re. the "user-hostile" comment., I do quite strongly disagree even without taking this specific use-case into account. Is a splash screen user-hostile? A disabled textbox? Every instance of DO_NOTHING_ON_CLOSE? An undecorated frame? Full-screen mode? There are reasons beyond hostility for removing the X button from a dialog in which clicking X would be an ambiguous response.

**Comment by kirill-grouchnikov** [comment]
Why have the title pane present at all in there? Mark is as undecorated and you'll have only your content. At the present moment I do not want to add this functionality in Radiance.

**Comment by ScoreUnder** [comment]
In a word, it's because I like radiance's border and undecorated doesn't provide that.

**Comment by ScoreUnder** [comment]
Comparison of plain dialog with X removed:

![image](https://user-images.githubusercontent.com/1123686/185803892-fe2426f5-3aa0-49ea-9226-23f8529dc7d2.png)

vs undecorated:

![image](https://user-images.githubusercontent.com/1123686/185803916-8a3beadd-e74a-460f-9822-0dd760ffdc09.png)
