### ISSUE TITLE
[Theming] Vertical scrollbars disappear when scrolled down

### ISSUE THREAD

**Issue by goodwilling** [kirill-grouchnikov/radiance#405]
### Version of Radiance (latest development is 6.0-SNAPSHOT)
6.0-SNAPSHOT

### Sub-project (Common, Animation, Theming, Component, ...)
Theming

### Version of Java (current minimum is 9)
Java 17

### Version of OS
Windows 10

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
The vertical scrollbars, either for a JTable or for a JTextPane,  disappear when they are scrolled down. Horizontal scroll bars are of no problem. It seems that the vertical scrollbars move horizontally if scrolled down.

**Comment by kirill-grouchnikov** [comment]
I'm not seeing this in the main radiance demo. Do you have a small reproducer for this?

**Comment by goodwilling** [comment]
Sorry, I do not have a small reproducer for this problem. BTW,  this problem is also observed on RedHat Linux 9.

**Comment by kirill-grouchnikov** [comment]
Not much I can do without being able to look at a reproducer, unfortunately.

The relevant code that applies a rotation affine transform to draw a vertical scrollbar thumb is [here](https://github.com/kirill-grouchnikov/radiance/blob/sunshine/theming/src/main/java/org/pushingpixels/radiance/theming/internal/ui/RadianceScrollBarUI.java#L191). There might be something that is applying another affine transform somewhere else, either in Radiance or in your app, but I can't really say without being able to debug that part.

**Comment by kirill-grouchnikov** [comment]
Do you have, perhaps, a custom skin or custom Radiance painters in your app?

**Comment by goodwilling** [comment]
I do not have a custom skin or custom Radiance painters in my app.  Since this problem was not seen using the radiance theming of the version Jan-2022,  I wonder what causes this problem when using a different version.

**Comment by kirill-grouchnikov** [comment]
There's been a lot of changes in version 6.0 for direct rendering of all components without using intermediate off-screen images.

**Comment by kirill-grouchnikov** [comment]
This is not something that I can fix in the dark without being able to reproduce it locally, either in the (modified) Radiance test app, or a standalone test.

**Comment by gLuEcKsKrAuT** [comment]
This issue can be reproduced with 
org.pushingpixels.radiance.demo.theming.main.Check
or the attached example.

Tested with 
radiance 6.0.1 / java17 / win10

[VerticalScrollBarBug.java.txt](https://github.com/kirill-grouchnikov/radiance/files/9573815/VerticalScrollBarBug.java.txt)

**Comment by kirill-grouchnikov** [comment]
Not seeing this on a macOS with Java 9 or Java 17. Is this issue only happening for you on Windows 10?

**Comment by gLuEcKsKrAuT** [comment]
For the moment it seems so.

![vertical_scroll_bar](https://user-images.githubusercontent.com/43807827/190681913-cf4b0de2-5961-4841-814d-3f88c78bec1f.png)

**Comment by kirill-grouchnikov** [comment]
Looks like this is a non-hi dpi display. Maybe there's a different code path in there somewhere that depends on the scale factor.

**Comment by gLuEcKsKrAuT** [comment]
Display is a [Asus PG258Q](https://rog.asus.com/monitors/23-to-24-5-inches/rog-swift-pg258q-model/spec/).
If you need more information, let me know.

**Comment by gLuEcKsKrAuT** [comment]
works fine with 6.5-SNAPSHOT
