### ISSUE TITLE
LookAndFeel.getDefaults() performance issue

### ISSUE THREAD

**Issue by otros-systems** [kirill-grouchnikov/radiance#41]
### Version of Radiance
`69f9224c0e628d46f56d45b7e442f35f93be2230`
### Sub-project (Trident, Substance, Flamingo, ...)
Substance
### Version of Java
Any
### Version of OS
Any
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
In my project I have tried to upgrade from Insubsnatial to Radiance and hit performance issue. After profiling I have root cause. In my application I'm calling `LookAndFeel.getDefaults()` very often (to check if default theme is dark or light). It causes to call `org.pushingpixels.substance.internal.utils.SubstanceImageCreator#getCrayonsImage` very often. As result method `org.pushingpixels.substance.internal.utils.SubstanceImageCreator#getSingleCrayon` is eating most of CPU cycles.

I'm proposing MR  to cache result of `getCrayonsImage`. Here is my MR: https://github.com/kirill-grouchnikov/radiance/pull/42

**Comment by kirill-grouchnikov** [comment]
Let me know how it looks like with the latest push from today. That call is wrapped with LazyValue evaluator now.

In general, the way Substance operates and the variety of skins it supports, caching an image like that is not the right approach. The push I made today also changed the image to have skin-consistent background (that is, not using very light fill on dark skins).
