### ISSUE TITLE
RadianceSliderUI: missing ticks in horizintal slider

### ISSUE THREAD

**Issue by homebeaver** [kirill-grouchnikov/radiance#410]
Hi Kirill, while playing with SVG File Viewer I noticed that ticks between 56 and 88 are missing (see screenshot)

![grafik](https://user-images.githubusercontent.com/3493126/190896506-bee1bd68-deb5-4b3c-a107-d323fef54cd5.png)

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

Displaying similar Slider in java Ocean theme all ticks are visible:

![grafik](https://user-images.githubusercontent.com/3493126/190896984-1dbd2b6c-07a4-44a8-9c64-1ae3dff17390.png)

Regards EUGen

**Comment by kirill-grouchnikov** [comment]
Not seeing this under 6.5-SNAPSHOT

**Comment by gLuEcKsKrAuT** [comment]
Dont know if this is relevant or not, 
but on a click on the top left icon at the SvgViewer, 
a NPE will be thrown.

The ticks are visible as expected for me too.

os: win 10
version: 6,5-SNAPSHOT
java: 9 (adoptium) & 17 (zulu)

![2022-09-20 17_02_37-SVG File Viewer](https://user-images.githubusercontent.com/43807827/191294195-64b34ac7-5e61-49b8-b554-53cc903c0f6c.png)

[stacktrace.txt](https://github.com/kirill-grouchnikov/radiance/files/9608828/stacktrace.txt)

**Comment by kirill-grouchnikov** [comment]
That crash is tracked now in https://github.com/kirill-grouchnikov/radiance/issues/412
