### ISSUE TITLE
How to disable a Command ? 

### ISSUE THREAD

**Issue by cedbanana** [kirill-grouchnikov/radiance#431]
### Version of Radiance (latest development is 6.5-SNAPSHOT)

How should a Command be disabled? For example in some situations I want my button from to Ribbon to be greyed out ( like it is disabled and cannot be clicked) how is this supposed to work in radiance?

**Comment by kirill-grouchnikov** [comment]
See https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/component/Command.md#attributes-overview for `actionEnabled` and `secondaryEnabled` attributes.

These can be set at the creation time via `Command.Builder.setActionEnabled` and `setSecondaryEnabled`, and then dynamically based on the state of your domain with `Command.setActionEnabled` and `setSecondaryEnabled`.
