### ISSUE TITLE
[Theming] Support customizing title pane buttons

### ISSUE THREAD

**Issue by kirill-grouchnikov** [kirill-grouchnikov/radiance#444]
Splitting off of https://github.com/kirill-grouchnikov/radiance/commit/0a0c2e415512304053abf07342143173601b60b4#commitcomment-93364364

Add APIs to allow customizing the icons and the tooltips / texts used for title pane buttons:
* Maximize
* Restore
* Iconify
* Close

<img width="105" alt="custom-titlepanebuttons1" src="https://user-images.githubusercontent.com/52874/217642925-6a02b467-fc34-4f04-a3c6-e9f4ffcd5ed2.png">

<img width="84" alt="custom-titlepanebuttons2" src="https://user-images.githubusercontent.com/52874/217642938-a83bc899-4c8e-45aa-a31e-276a59723cc2.png">

**Comment by kirill-grouchnikov** [comment]
@ed-erwin-tf

**Comment by ed-erwin-tf** [comment]
Thanks this could be useful to me.

I would want my icons to look similar to your defaults, so I've examined code in the "Blade" classes.  Those are "internal", but it looks like they only use public apis, so I could probably replicate them.

By the way, I just found that BladeDrawingUtils.paintBladeSimpleBorder() does not dispose of the graphics object.  (No point opening a bug for that.)

**Comment by kirill-grouchnikov** [comment]
Yes, the idea is definitely to not block app code. The internal flow there is mostly around getting the stroke width. I'll look at the disposal.
