### ISSUE TITLE
[Radiance] Sonatype JAR for Hibiscus created with Java 9 classfile version

### ISSUE THREAD

**Issue by kirill-grouchnikov** [kirill-grouchnikov/radiance#45]
> What went wrong:
> A problem occurred evaluating root project 'hibiscus-demo'.
> > java.lang.UnsupportedClassVersionError: org/pushingpixels/hibiscus/HibiscusPlugin has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Need to check which version of Java is used to compile jars locally before uploading to the staging Sonatype repository

**Comment by brunchboy** [comment]
You can still use a more advanced Java to do it, but simply pass a command-line argument (configured in Maven) to compile for an older version. There is also a Maven plugin I use to check during the build process that I have not used any classes or APIs that are newer than my target Java version. I will investigate what those are and share them here.

**Comment by kirill-grouchnikov** [comment]
Hopefully I just missed this line in build.gradle for Hibiscus:

'sourceCompatibility = 1.8'

I'll check in the evening when I get to the machine I use to upload to Sonatype.

**Comment by brunchboy** [comment]
Ok. In my Beat Link project which targets Java 6, check out the following sections of the [pom.xml](https://github.com/brunchboy/beat-link/blob/master/pom.xml):

* In `<project>…<build>…<plugins>` I [configure](https://github.com/brunchboy/beat-link/blob/master/pom.xml#L84-L92) the `maven-compiler-plugin` to expect Java 6 source and emit Java 6 classes.
* Immediately after that I [configure](https://github.com/brunchboy/beat-link/blob/master/pom.xml#L93-L103) the Codehaus [`animal-sniffer-maven-plugin`](https://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/) to validate that I am only using APIs available in Java 6.

With those things in place, I can ensure that my builds, if they succeed, will work fine on Java 6.

**Comment by brunchboy** [comment]
I don’t think source compatibility is enough; you need to be sure you are generating the proper class format as well, and that you haven’t accidentally referred to some class that is available in a more recent JDK but not in Java 8 (in your case), or the class that refers to it will fail to load with a `NoClassDefFoundError`. That’s what the animal-sniffer plugin does.

**Comment by kirill-grouchnikov** [comment]
Should be fixed now with sourceCompatibility in build.gradle for Hibiscus.
