### ISSUE TITLE
Issue Building the package.

### ISSUE THREAD

**Issue by DustinMerrell** [kirill-grouchnikov/radiance#453]
### Version of Radiance (latest release is 7.0-SNAPSHOT)
Latest Release 7.0-SNAPSHOT

### Version of Java (current minimum is 9)
Java 9
Java 11
Java 17
### Version of OS
Window 11
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

I am unable to build the package.

cd C:\Development\JavaLibs\Radiance L and F\radiance; .\gradlew.bat --configure-on-demand -x check clean build
Configuration on demand is an incubating feature.
> Task :theming-extras:clean UP-TO-DATE
> Task :theming:clean UP-TO-DATE
> Task :component:clean UP-TO-DATE
> Task :demos:component-demo:clean UP-TO-DATE
> Task :common:clean UP-TO-DATE
> Task :animation:clean UP-TO-DATE
> Task :demos:component-ktx-demo:clean UP-TO-DATE
> Task :demos:theming-debugger-demo:clean UP-TO-DATE
> Task :demos:common-demo:clean UP-TO-DATE
> Task :demos:animation-apps:clean UP-TO-DATE
> Task :demos:theming-apps:clean UP-TO-DATE
> Task :demos:animation-demo:clean UP-TO-DATE
> Task :demos:animation-ktx-demo:clean UP-TO-DATE
> Task :demos:theming-demo:clean UP-TO-DATE
> Task :kotlin-ext:animation-ktx:clean UP-TO-DATE
> Task :kotlin-ext:swing-ktx:clean UP-TO-DATE
> Task :kotlin-ext:theming-ktx:clean UP-TO-DATE
> Task :kotlin-ext:component-ktx:clean UP-TO-DATE
> Task :tools:laf-benchmark:clean UP-TO-DATE
> Task :tools:screenshot:clean UP-TO-DATE
> Task :tools:scheme-editor:clean UP-TO-DATE
> Task :tools:svg-transcoder-gradle-plugin:clean UP-TO-DATE
> Task :tools:shape-editor:clean UP-TO-DATE
> Task :tools:tools-common:clean UP-TO-DATE
> Task :tools:svg-transcoder:clean UP-TO-DATE
> Task :tools:theming-debugger:clean UP-TO-DATE
> Task :kotlin-ext:animation-ktx:processResources NO-SOURCE
> Task :component:processResources NO-SOURCE
> Task :demos:common-demo:processResources NO-SOURCE
> Task :kotlin-ext:component-ktx:processResources NO-SOURCE
> Task :demos:animation-apps:processResources NO-SOURCE
> Task :kotlin-ext:theming-ktx:processResources NO-SOURCE
> Task :demos:theming-debugger-demo:processResources NO-SOURCE
> Task :tools:theming-debugger:processResources NO-SOURCE
> Task :tools:scheme-editor:processResources NO-SOURCE
> Task :tools:tools-common:processResources NO-SOURCE
> Task :tools:screenshot:processResources NO-SOURCE
> Task :animation:compileJava FAILED
> Task :tools:shape-editor:processResources NO-SOURCE
> Task :common:compileJava FAILED
> Task :tools:svg-transcoder-gradle-plugin:pluginDescriptors
> Task :tools:laf-benchmark:compileJava FAILED
> Task :demos:animation-ktx-demo:processResources
> Task :demos:animation-demo:processResources
> Task :tools:theming-debugger:sourcesJar
> Task :tools:svg-transcoder:processResources
> Task :demos:theming-apps:processResources
> Task :demos:component-ktx-demo:processResources
> Task :demos:component-demo:processResources
> Task :demos:theming-demo:processResources
> Task :theming-extras:processResources
> Task :theming:processResources
> Task :component:sourcesJar
> Task :kotlin-ext:swing-ktx:compileKotlin

FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':animation:compileJava'.
> Error while evaluating property 'javaCompiler' of task ':animation:compileJava'.
   > Failed to calculate the value of task ':animation:compileJava' property 'javaCompiler'.
      > No matching toolchains found for requested specification: {languageVersion=9, vendor=any, implementation=vendor-specific}.
         > No locally installed toolchains match (see https://docs.gradle.org/8.1.1/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.1.1/userguide/toolchains.html#sub:download_repositories).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':common:compileJava'.
> Error while evaluating property 'javaCompiler' of task ':common:compileJava'.
   > Failed to calculate the value of task ':common:compileJava' property 'javaCompiler'.
      > No matching toolchains found for requested specification: {languageVersion=9, vendor=any, implementation=vendor-specific}.
         > No locally installed toolchains match (see https://docs.gradle.org/8.1.1/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.1.1/userguide/toolchains.html#sub:download_repositories).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':tools:laf-benchmark:compileJava'.
> Error while evaluating property 'javaCompiler' of task ':tools:laf-benchmark:compileJava'.
   > Failed to calculate the value of task ':tools:laf-benchmark:compileJava' property 'javaCompiler'.
      > No matching toolchains found for requested specification: {languageVersion=9, vendor=any, implementation=vendor-specific}.
         > No locally installed toolchains match (see https://docs.gradle.org/8.1.1/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.1.1/userguide/toolchains.html#sub:download_repositories).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

**Comment by kirill-grouchnikov** [comment]
You need Java 9 to build Radiance. Not anything later. Specifically Java 9. On a mac machine you can set up an alias like this `alias java9='export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home'` (after installing JDK 9 in that location), then type `java9` and then `./gradlew build`.

On other OSes you can set it up in a similar fashion. Something like this on Windows in a `.bat` file:

```
set JAVA_HOME=C:\Program Files\Java\jdk-9.0.4
set PATH=C:\Program Files\Java\jdk-9.0.4\bin;%PATH%
```

**Comment by DevCharly** [comment]
@kirill-grouchnikov I was just wondering why you are still using Java 9 as the minimum requirement?
Java 9 (and 10) reached end-of-life five years ago in 2018 and no one should use that version(s).

Wouldn't it make more sense to use Java 11 LTS as minimum requirement?

IMHO libraries should always use a LTS Java version as minimum requirement.

**Comment by kirill-grouchnikov** [comment]
So far I haven't found anything that I need from the later versions of the JDK to justify the jump.
