### ISSUE TITLE
[Component] Command button text not updating when set

### ISSUE THREAD

**Issue by jkdoug** [kirill-grouchnikov/radiance#463]
### Version of Radiance (latest release is 7.5-SNAPSHOT)
Radiance 7.0.1

### Sub-project (Common, Animation, Theming, Component, ...)
Component

### Version of Java (current minimum is 9)
Java 17.0.8

### Version of OS
Windows 10 Pro 22H2

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
I have a Command button showing a formatted date on my ribbon bar. I change the date and then call setText on the command to update the date shown on the button, but the text display remains the same. I verified that the correct text value is being set in the Command::setText call, but the visual doesn't change. (This is something that worked previously, on Radiance 6.5.0.)

**Comment by kirill-grouchnikov** [comment]
Which part of the ribbon displays the button?

**Comment by jkdoug** [comment]
The command is created and initialized:

`currentDateCommand = Command.builder()
		.setText(DateUtil.formatMedium(LocalDate.now()))
		.setActionRichTooltip(RichTooltip.builder()
				.setTitle("Current Date")
				.addDescriptionSection("Set the current date to be displayed")
				.build())
		.setAction(commandActionEvent -> {
			// ... date picker displayed and new date set
		})
		.build();`

The button gets added to the ribbon toolbar:
`navigationBand.addRibbonCommand(
		currentDateCommand
		.project(CommandButtonPresentationModel.builder()
				.setActionKeyTip("CD")
				.setFocusable(false)
				.build()),
		JRibbonBand.PresentationPriority.TOP);`

The text gets updated when a date change occurs in the data model:
`public void onCurrentDateChange(@NonNull final CurrentDateChange event) {
	currentDateCommand.setText(DateUtil.formatMedium(event.getCurrentDate()));
}`

It is displayed on a JRibbonBand, inside of a group, if that helps.

**Comment by kirill-grouchnikov** [comment]
This is indeed a regression introduced in https://github.com/kirill-grouchnikov/radiance/commit/fc8aa16091ae3626592288d767f842bf8ef00f61#diff-1f969e4115a37ff72aa4df4cf87fc7afae0166c9ecfbeedcb65c0d98cdcc978c where I added an optimization to not recompute text bounds for `BIG` buttons, but didn't account for changing text.

**Comment by jkdoug** [comment]
Fantastic! Thank you so much.
