### ISSUE TITLE
[Component] Ribbon task content (ribbon bands) not showing after a certain sequence of user interactions on Windows

### ISSUE THREAD

**Issue by MichaelWDenney** [kirill-grouchnikov/radiance#472]
### Version of Radiance (latest release is 7.5-SNAPSHOT)

7.5-SNAPSHOT

### Sub-project (Common, Animation, Theming, Component, ...)

Ribbon

### Version of Java (current minimum is 9)

21.0.1

### Version of OS

Windows 11

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

In the demo, I added the following to org.pushingpixels.radiance.demo.component.ribbon.BasicCheckRibbon.configureTaskBar():

        ribbon.addTaskbarCommand(Command.builder()
      	      .setIconFactory(Edit_clear.factory())
      	      .setAction(commandActionEvent -> ribbon.setMinimized(!ribbon.isMinimized()))
      	      .build().project());

In general, it works as expected.  However, every now and then the ribbon tasks all become blank:

![image](https://github.com/kirill-grouchnikov/radiance/assets/172624669/791b9fe7-6b48-480a-892f-cd121fb909a3)

The definite cause is not clear but it happens after some combination of repeatedly minimizing/restoring the ribbon and repeatedly clicking the various ribbon tab toggle buttons.  It can sometimes take a while to get the issue to occur.  When it does occur, the only way I've found to restore the ribbon tasks is to change the skin.

**Comment by kirill-grouchnikov** [comment]
Not able to reproduce this so far on macOS. Will try on a Windows box.

**Comment by kirill-grouchnikov** [comment]
Reproducible 100% on Windows but not on macOS:

* Run the modified demo with the taskbar command wired to minimize / maximize the ribbon
* Click that taskbar button to minimize the ribbon
* Single click on the "Write" task to display it in a popup
* Click that taskbar button to maximize the ribbon

End result is that the ribbon is maximized, but does not show any task content
