### ISSUE TITLE
[Component] Dropdown/Combo Boxes Cannot be Used on Minimized Ribbons

### ISSUE THREAD

**Issue by MichaelWDenney** [kirill-grouchnikov/radiance#474]
### Version of Radiance (latest release is 7.5.0)

7.5-SNAPSHOT

### Sub-project (Common, Animation, Theming, Component, ...)

Ribbon

### Version of Java (current minimum is 9)

21.0.1

### Version of OS

Windows 11

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

When attempting to make a selection in a dropdown box on a ribbon task while ribbons are minimized, is not possible.  Clicking on a selection results in the ribbon being hidden and no selection being made.

To reproduce, add ribbon minimize support to the demo (see #472 for how I implemented it) and minimize the ribbons.  Then go to the Write task and attempt to change the selection in either the Games or Multimedia dropdowns.  Clicking on a selection results in the ribbon minimizing.  When the ribbon is re-opened, the selection in the dropdown has not occurred.

**Comment by MichaelWDenney** [comment]
Only just got around to trying this (in 8.0-SNAPSHOT).  Issue still exists on Windows 11.

**Comment by kirill-grouchnikov** [comment]
It is marked as to be fixed in 8.0, but it hasn't been addressed yet.

**Comment by MichaelWDenney** [comment]
Doh!  Sorry.  Going through the other fixes (which so far seem good) and missed that this one is still open.
