### ISSUE TITLE
JTabbedPane Tabs are difficult to read when Tab Placement is set to Left or Right due the Tab Rendering Vertical

### ISSUE THREAD

**Issue by ECartman** [kirill-grouchnikov/radiance#475]
### Version of Radiance (latest release is 8.0-SNAPSHOT)
7.5.0

### Sub-project (Common, Animation, Theming, Component, ...)
Theming

### Version of Java (current minimum is 9)
21 

### Version of OS
Windows 10 22h2
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

.while using Radiance within JTabbedPane, renders Tabs in a way that they are difficult to read when set up on the following way: 

`setTabPlacement(javax.swing.JTabbedPane.LEFT);`
or 
`setTabPlacement(javax.swing.JTabbedPane.RIGHT);`

example: 
![image](https://github.com/user-attachments/assets/c4fd800c-d29b-46e7-bbd5-345d6d0c770f)
in contrast the System Look and feel looks like so: 
![image](https://github.com/user-attachments/assets/c244f61a-9e84-47ab-b17a-99af08eeda83)

another example using FlatLaf
![image](https://github.com/user-attachments/assets/f27f08f7-b1f8-4f77-b56c-7d365c9bd279)

I am unaware if there is a property to switch this behavior. albeit i think tabs text should default to render Horizontal by default. on tabs regardless of the placement. 

the issue can be showcased on the demo app 
![image](https://github.com/user-attachments/assets/2f900156-4646-4646-9f13-6f966c401024)

`demos\theming-demo\src\main\java\org\pushingpixels\radiance\demo\theming\main\Check.java`

**Comment by kirill-grouchnikov** [comment]
This is the intended visual appearance of tabs under Radiance. There is no client property or API to configure this, and no plans to support such configuration in the future.
