### ISSUE TITLE
[Component] Allow adding BaseProjection to JFlowRibbonBand.addFlowComponent

### ISSUE THREAD

**Issue by MichaelWDenney** [kirill-grouchnikov/radiance#476]
### Version of Radiance (latest release is 8.0-SNAPSHOT)

7.5-SNAPSHOT

### Sub-project (Common, Animation, Theming, Component, ...)

Ribbon

### Version of Java (current minimum is 9)

21.0.1

### Version of OS

Windows 11

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

There does not appear to be an (obvious?) means of adding a CommandStripProjection to a JRibbonBand.

**Comment by kirill-grouchnikov** [comment]
That is correct. `RibbonBand` has a lot of flexibility built into it for resizability, and button strips don't really work within those constraints. Command strips can be added to `JFlowRibbonBand` as shown in the main `BasicCheckRibbon` demo.

**Comment by MichaelWDenney** [comment]
Thanks for the quick response.  Ok.  So then how can a simple component like a button be added to the `JFlowRibbonBand`?  That is, what is the equivalent of `addRibbonCommand ` in `JFlowRibbonBand`?  (`JFlowRibbonBand.addFlowComponent` does not support `BaseCommandButtonProjection`.)

**Comment by kirill-grouchnikov** [comment]
Ah, looks like I messed it up a bit in one of the two places:

* Either `BaseCommandButtonProjection` should extend `Projection` instead of `BaseProjection`
* Or `JFlowRibbonBand.addFlowComponent` should accept `BaseProjection` instead of `Projection`

**Comment by kirill-grouchnikov** [comment]
`JFlowRibbonBand` API has been updated. If you want to use it to add command button projections, you will need to explicitly set the presentation state on the presentation model.
