### ISSUE TITLE
[Component] Command overlays are not passed to secondary menu commands

### ISSUE THREAD

**Issue by MichaelWDenney** [kirill-grouchnikov/radiance#478]
### Version of Radiance (latest release is 8.0-SNAPSHOT)

7.5.0

### Sub-project (Common, Animation, Theming, Component, ...)

Ribbon

### Version of Java (current minimum is 9)

21.0.1

### Version of OS

Windows 11

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

I'm not sure if this is unsupported functionality or if I am getting confused between the content model, presentation model, and projection.  What I want is the following:
![image](https://github.com/user-attachments/assets/cfe2262b-429b-4183-8b50-777a8ce7ee30)

That is a sub-menu using the big presentation state.  To create a top-level command button with a menu that uses the big presentation state, I created a `CommandButtonProjection` that in turn used a `CommandPopupMenuPresentationModel` with `setItemPresentationStatue(CommandButtonPresentationState.BIG)` set.  That works because I can add the `CommandButtonProjection` to the ribbon.  With a sub-menu, I need to `setSecondaryContentModel` but I don't see a way of using a Projection for one entry of the `CommandGroup` used to instantiate the `CommandMenuContentModel` used.

**Comment by kirill-grouchnikov** [comment]
With the linked fix, you can use `CommandButtonProjection.setCommandOverlays` to configure the overlay with `CommandButtonPresentationModel.overlay().setPresentationState` for each one of the commands in the specific submenu. It's not ideal in terms of the API shape, as you need to set it on each one of the entries in that menu, but at this point it's starting to push the boundaries of projection-based API surface of Radiance components in general.

The newly added `SecondaryTileMenu` demo shows how it works
<img width="693" alt="image" src="https://github.com/user-attachments/assets/63588f59-e716-4d90-8a96-dbccd725e8af">
<img width="692" alt="image" src="https://github.com/user-attachments/assets/3bac48b6-0397-486f-8d0d-58dea0d07157">

**Comment by MichaelWDenney** [comment]
Thanks for accommodating my request.  I'll give that a try but it should meet my need.

Any thought of supporting bands within menus?  That seems like what Radiance itself does when handling ribbon re-sizing.  Making that functionality visible in the menu hierarchy could greatly increase flexibility.

**Comment by kirill-grouchnikov** [comment]
Not sure what you have in mind. Do you have a mock?

**Comment by MichaelWDenney** [comment]
What I'm trying to get across is that a band can transform into a single command with a popup menu containing the original band during re-sizing.  Like this:
![image](https://github.com/user-attachments/assets/30f0e864-5d32-4f10-bac3-5fe5c0743b86)

I was thinking that, since Radiance seems to be able to support a band within a menu, making that functionality visible would allow things like (ignore the mismatched themes and menu titles):
![image](https://github.com/user-attachments/assets/601d6e0e-38ae-4ebe-a56d-67db7d061d5e)

(I don't have a specific need for that at the moment, but I could see it being useful in the future and providing a lot of flexibility.)

**Comment by kirill-grouchnikov** [comment]
This is done in https://github.com/kirill-grouchnikov/radiance/blob/sunshine/component/src/main/java/org/pushingpixels/radiance/component/internal/ui/ribbon/BasicRibbonBandUI.java#L282 which shows how the secondary lifecycle API can be used to place arbitrary content in the command button's popup menu.

**Comment by MichaelWDenney** [comment]
Ah!  Thanks.  I'll take a look at that.

Incidentally, is there a better place to ask questions (as opposed to raising issues)? Like a forum?  I just want to avoid opening nuisance issues.

**Comment by kirill-grouchnikov** [comment]
Here is fine. I don't have a discord or slack or something "external" for questions.
