### ISSUE TITLE
How do I get the JAR file?

### ISSUE THREAD

**Issue by BrightSky-OSSDO** [kirill-grouchnikov/radiance#482]
### Version of Radiance (latest release is 8.0-SNAPSHOT)
7.5.0

### Sub-project (Common, Animation, Theming, Component, ...)
I don't know

### Version of Java (current minimum is 9)
Java 17

### Version of OS
Windows 11

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
How do I get the JAR file for Radiance so I can use it in my Java program? I checked the releases page and it isn't there, just the source code. I can't build from scratch because I don't have gradle.

**Comment by kirill-grouchnikov** [comment]
1. https://github.com/kirill-grouchnikov/radiance/tree/sunshine/drop
2. https://repo.maven.apache.org/maven2/org/pushing-pixels/radiance-theming/
3. https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/building.md
