### ISSUE TITLE
[Component] Disabled buttons maintain their active rollover / pressed state

### ISSUE THREAD

**Issue by MichaelWDenney** [kirill-grouchnikov/radiance#484]
### Version of Radiance (latest release is 8.0-SNAPSHOT)

7.5-SNAPSHOT

### Sub-project (Common, Animation, Theming, Component, ...)

Ribbon

### Version of Java (current minimum is 9)

21.0.4+7

### Version of OS

Windows 11

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

1. I have a band with four buttons.  These are straight-forward, non-toggle buttons that enable/disable based on state changes triggered by the buttons themselves.  Initially two of the four buttons are disabled:

![image](https://github.com/user-attachments/assets/37d3fe87-c244-4b58-af57-f664ecf36250)

2. Clicking "Command 2" will result in a state change causing "Command 2" itself to disable and both "Command 3" and "Command 4" to enable.  So far no issue:

![image](https://github.com/user-attachments/assets/3be98b41-2fa6-4783-82ca-c7a629c8717f)

3. Clicking "Command 3" will result in "Command 2" re-enabling and both "Command 3" and "Command 4" disabling.  This works, but notice that "Command 2" is now highlighted.  My cursor is nowhere near the band in this screen capture and, as I said, these buttons do not toggle.
![image](https://github.com/user-attachments/assets/03c944d3-fff6-46df-a7c7-9f6200b3d4ad)

4. Clicking "Command 2" again will result in a return to the state in step 2. above.  However, now notice that "Command 3" is highlighted:
![image](https://github.com/user-attachments/assets/159b2ce3-4356-4021-a5dc-7950d90602a6)

6. Clicking "Command 4" will result in a return to the state in step 3. including the highlighting of "Command 2".  Clicking "Command 2" at this point, will again disable "Command 2" and enable "Command 3" and "Command 4" but now both "Command 3" and "Command 4" are highlighted: 
![image](https://github.com/user-attachments/assets/d4cfb55d-0823-4634-9ee2-bfbe79a1cebe)

Note that I can clear this highlighting simply by running the cursor over the buttons.  Doing so, however, does not prevent it from happening again the next time the state changes.  However, I have seen this behaviour stop at some point, but I have no idea what caused it to stop.

It kind of seems like the band is remembering previously clicked buttons and, when the currently active button is disabled, attempting to make other enabled buttons active.  However, "Command 1", possibly because it is always enabled, does not seem to be impacted by this issue.

**Comment by kirill-grouchnikov** [comment]
This is probably remembering somewhere that the button was active (rollover / pressed) at the time when its action disabled itself. So when another event enables it back, it is shown in that active state.
