### ISSUE TITLE
[Component] Command buttons presentation not kept in sync with the secondary content model

### ISSUE THREAD

**Issue by MichaelWDenney** [kirill-grouchnikov/radiance#487]
### Version of Radiance (latest release is 8.0-SNAPSHOT)

8.0-SNAPSHOT

### Sub-project (Common, Animation, Theming, Component, ...)

Ribbon

### Version of Java (current minimum is 9)

21.0.4+7

### Version of OS

Windows 11

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

If a ribbon control's secondary menu is updated such that it transitions from empty to non-empty or vice versa, the "v" arrow on the bottom of the button is not shown/hidden until a refresh is forced by moving the cursor over the control.

To reproduce, make the following changes in the demo code's BasicCheckRibbon class:

1.	Add: `CommandMenuContentModel keyboardShortcuts = new CommandMenuContentModel();`

2.	Add the following method:
```
private void updateKeyboardShortcutsMenu() {
	if ( keyboardShortcuts.isEmpty() ) {
		for (final CommandGroup cg:this.popupMenuContentModel.getCommandGroups()) {
			keyboardShortcuts.addCommandGroup(cg);
		}
		System.out.println("Keyboard shortcuts re-populated." );
    	}
    	else {
        	keyboardShortcuts.removeAllCommandGroups();    		
		System.out.println("Keyboard shortcuts cleared.");
	}
}

```
3.	In `getPreferencesBand()`, modify the setAction in the command for adding the **Accessibility** command to the following:
`.setAction(commandActionEvent -> updateKeyboardShortcutsMenu())`

4.	In `getPreferencesBand()`, add the following prior to the command for adding the **Keyboard Shortcuts**:
```
List<CommandGroup> secondaryCommands = this.popupMenuContentModel.getCommandGroups();
for (final CommandGroup s:secondaryCommands) {
	keyboardShortcuts.addCommandGroup(s);
}
```

5.	In `getPreferencesBand()`, modify the setAction in the command for adding the **Keyboard shortcuts** command to the following:
`.setSecondaryContentModel(keyboardShortcuts)`

Run the ribbon demo.  Clicking the **Accessibility** control will cause the **Keyboard shortcuts** to alternate between having no submenu and having the five Test Menu items.  Note that each time **Accessibility** is clicked, the "v" arrow on the **Keyboard shortcuts** does not update until the cursor is moved over **Keyboard shortcuts**. 

(Apologies if that is a bit messy.  I tried to create a test case as quickly as possible.)

**Comment by kirill-grouchnikov** [comment]
Thanks, this is probably missing a forced relayout somewhere in that chain.
