### ISSUE TITLE
Maximize of Application Obscures the Windows Toolbar

### ISSUE THREAD

**Issue by MichaelWDenney** [kirill-grouchnikov/radiance#488]
### Version of Radiance (latest release is 8.0-SNAPSHOT)

8.0-SNAPSHOT

### Sub-project (Common, Animation, Theming, Component, ...)

Ribbon

### Version of Java (current minimum is 9)

21.0.4+7

### Version of OS

Windows 11

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

This is reproducible using the BasicCheckRibbon demo.

Start the application and click the 'Maximize' button.

Expected behaviour: The application window expands to fill the current Windows screen while leaving the Windows toolbar visible.
Actual behaviour: The application window expands to fill the entire current Windows screen thus obscuring the Windows toolbar.

(See the attached full screen shots.  When Word is maximized, the toolbar is visible at the bottom of the screen.  When the demo is maximized, the toolbar cannot be seen.)
![image](https://github.com/user-attachments/assets/d490c7c0-6d99-4dba-b177-d2fdaadf7197)
![image](https://github.com/user-attachments/assets/17da7fec-1352-485a-8e66-fd1837aabb54)

**Comment by kirill-grouchnikov** [comment]
This sounds like https://github.com/kirill-grouchnikov/radiance/issues/379 that was fixed by https://github.com/kirill-grouchnikov/radiance/commit/97e9bb7f7432561e467d598811888f036857d7c4

Do you see the same issue in the main Radiance demo app (org.pushingpixels.radiance.demo.theming.main.Check)?

**Comment by kirill-grouchnikov** [comment]
Ah, I later reverted it. See the comment that starts in https://github.com/kirill-grouchnikov/radiance/blob/sunshine/theming/src/main/java/org/pushingpixels/radiance/theming/internal/utils/RadianceTitlePane.java#L994 - there's nothing that I can do in the library to make it work reliably across different JDK versions.

**Comment by kirill-grouchnikov** [comment]
The revert was in https://github.com/kirill-grouchnikov/radiance/commit/c8f624d5e5152327c346c445fd652649a167092f

Closing this

**Comment by MichaelWDenney** [comment]
Hmmm.  We are using:

```
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode)
```

Maybe it's a regression in Java?

**Comment by kirill-grouchnikov** [comment]
See if https://github.com/kirill-grouchnikov/radiance/issues/443#issuecomment-1423397066 helps with your particular setup

**Comment by MichaelWDenney** [comment]
Yes, it appears to resolve it on Windows.  I'll have to test whether there is any impact on other platforms.
Thanks for that.
