### ISSUE TITLE
Duplication of Ribbon Controls

### ISSUE THREAD

**Issue by MichaelWDenney** [kirill-grouchnikov/radiance#489]
### Version of Radiance (latest release is 8.0-SNAPSHOT)

8.0-SNAPSHOT

### Sub-project (Common, Animation, Theming, Component, ...)

Ribbon

### Version of Java (current minimum is 9)

21.0.4+7

### Version of OS

Windows 10 Pro

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

During early testing, a user reported duplicate ribbon controls appeared (see attached images).  The UI looked ok upon startup and it was after it was in use for a while that this occurred.  The user indicates they were not doing anything such as minimizing ribbons, resizing the dialog, or moving the dialog that may have triggered this occurrence.  Also note that these were functional duplicates not ghost images of the controls.  As ribbon control configuration and creation is occurring once during initialization of the application dialog, I am unable to think of how this could be caused by my implementation and thus suspect a bug in the library.
 
This has not been reproduced since it originally happened nor was it seen by any other users.

![image](https://github.com/user-attachments/assets/4702d343-5c81-4a19-ac34-3d85af4fc811)
![image](https://github.com/user-attachments/assets/e4dba798-eeeb-4466-9d77-8ed202070eaa)

**Comment by kirill-grouchnikov** [comment]
That looks like multiples of everything, from standalone buttons in ribbon bands, to buttons in button strips, to taskbar buttons in the taskbar.

Without a reproducer, either in the main test app, or in a standalone sample attached here, I wouldn't even know where to begin, since it's affecting everything.

**Comment by MichaelWDenney** [comment]
You're right.  It's multiples of everything.  And I'm not at all surprised that you don't know where to start without a reproducer.  I don't know where to start either.  I'll keep an eye out and provide additional information if any comes to light.  I'll also see about adding some logging to my code to catch if it is triggered outside of the library.

**Comment by MichaelWDenney** [comment]
Problem was on my end.  I was too zealous with my use of statics.

**Comment by kirill-grouchnikov** [comment]
Thanks for verifying!
