### ISSUE TITLE
[Documentation / FAQ entry] Could a tutorial be added or considered?

### ISSUE THREAD

**Issue by rubyFeedback** [kirill-grouchnikov/radiance#490]
Hey there Kirill and others,

A FAQ exists here:

https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/faq.md

I found the project via some external link from reddit, where people discussed
alternatives to SWING in general. So one suggested the project here.

Visually it looks neat and it seems to be actively developed.

One thing I have is ... I really need tutorials + working examples, really from
"hello world" to larger things. I don't need EVERYTHING in a tutorial, mind you,
just things to get me going and learning in a step-by-step fashion.

I had a look at the FAQ and searched for "tutorial" but the FAQ does not mention
it. So my first issue request is to add an additional entry to the FAQ specifically
about tutorial(s). It is ok if no tutorial exists; a simple FAQ entry could answer that
either way.

Which brings me to the second part of my issue request: to add a tutorial, and
then link to it too from the FAQ + main README.

This tutorial does NOT have to be super-long! I am ok-ish if the tutorial really
just connects a few examples, say from hello world, to showcasing buttons,
perhaps a text-view ... the most comment widgets. Say, like 5 widgets or so,
initially. I think that should be acceptable. That can perhaps be done in one
or two days on the weekend eventually. Perhaps come new years you may
have a bit of time for that. :)

It can lateron also be extended, so I am actually asking for a "bootstrapping"
tutorial for now, just to get the pointers, get things going. The tutorial should
cater to semi-tech people, so NOT total newbies, but people who may have a
TINY bit of experience in regards to software engineering, and are not stupid.
So the tutorial can be succinct, to the point; and if lateron something has to
be extended, that can also be done. So I am asking mostly for a minimal tutorial,
lateron it could be expanded.

Anyway, that's my use case and issue request. Thank you for reading this and
potentially considering whether this may be a useful addition to radiance.

(Also, on a side note ... another entry to the FAQ may be the history of radiance.
Not asking for a complete one, but just the "how did the project get started"
and "how did it progress into 2024". I think some newcomers may appreciate
this too, in a FAQ entry.)

**Comment by kirill-grouchnikov** [comment]
All the existing documentation is available from the main landing page of the project. For example, for theming it is at https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/theming/overview.md, for components it is https://github.com/kirill-grouchnikov/radiance/blob/sunshine/docs/component/overview.md etc

Short history of the project is available at the end of https://github.com/kirill-grouchnikov/radiance/blob/sunshine/archive/older-releases.md
