### ISSUE TITLE
[Flamingo] Corrupt visuals showing minimized ribbon content

### ISSUE THREAD

**Issue by VitoMaggipinto** [kirill-grouchnikov/radiance#64]
### Version of Radiance
0.9-SNAPSHOT
### Sub-project (Trident, Substance, Flamingo, ...)
Flamingo
### Version of Java
1.8
### Version of OS
Windows 10
### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
When the ribbon is not expanded, opening tasks and moving mouse over buttons, the ribbon contents get corrupted visuals.
![image](https://user-images.githubusercontent.com/13164945/45534648-20848f00-b7fc-11e8-87aa-08ededaadebd.png)

![cattura](https://user-images.githubusercontent.com/13164945/45534523-aa802800-b7fb-11e8-8a13-c56219fbf018.PNG)

**Comment by kirill-grouchnikov** [comment]
This is due to SubstanceBandControlPanelUI and SubstanceFlowBandControlPanelUI not doing anything to paint the background of the control panel in update / paint, even though the corresponding controls are opaque.

**Comment by VitoMaggipinto** [comment]
is there any chance of having flamingo / ribbon with look & feel other than substance?

**Comment by kirill-grouchnikov** [comment]
There used to be support for other look-and-feels, but it was never quite working right. 

Each one of the core look-and-feels is its own thing. Metal is using simpler gradients. Nimbus is built by a never-released (as far as I know) editor that translates component-specific specs to generated code. Windows and Aqua use native APIs. There was just no realistic way of making the ribbon work with those look-and-feels.

So the cumbersome workaround was to use a few UIManager entries (colors, borders) + adopt a renderer-based approach where an offscreen button is configured to have the matching state and dimensions, and painted to an offscreen buffer to emulate visual appearance of the relevant ribbon parts. It looked ugly, to be honest, and was very brittle code. 

That code also broke for anything that had built-in animations, such as Windows or Synthetica buttons. Those use their own internal animation trackers, and renderer-based visuals were broken in all random ways.

This is the short story on why Flamingo components are now only available under Substance look-and-feel.

If you feel strongly about using the ribbon under third-party look-and-feels, you will need to get their cooperation in providing some kind of extension JARs that would render Flamingo components with their specific APIs. I am aware of Synthetica and WebLAF as the only two other remaining active look-and-feels. It is worth pointing out that each one also ships with their own set of components, and each one of those only works with that respective look-and-feel.

**Comment by VitoMaggipinto** [comment]
Thanks, now it's working fine.
