### ISSUE TITLE
very wide custom component inside JRibbonBand

### ISSUE THREAD

**Issue by grandinj** [kirill-grouchnikov/radiance#65]
### Version of Radiance

We're using the one we built on 20161130, which is revision 7420921. I could update, but I don't see any logic changes in the latest version that indicate that what I want to do will work.

### Sub-project (Trident, Substance, Flamingo, ...)

Flamingo

### Version of Java

 Java8 (1.8.0_151)

### Version of OS

Windows 10

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)

We want to put a custom component inside a JRibbonBand (which is inside a RibbonTask), and we want the custom component to take up all the available horizontal space.

Would also be nice to be able to turn of the band title, so we can reclaim that vertical space.

The context is that we have several RibbonTasks containing various command buttons, and one RibbonTask that we want to put a very wide audio/video-type slider control into.

I can't find any way of doing this short of hacking Flamingo itself (and I went so far as too create a custom RibbonBandUI subclass).

The best I can currently do is to call

    addRibbonComponent(new JRibbonComponent(mySpecialSlider), 3);

which gives me a small block of space.

Thanks.

**Comment by kirill-grouchnikov** [comment]
The functionality to add tall ribbon content that spans more than one row inside the ribbon band has been removed in Radiance. That functionality does not play well with the overall "philosophy" of the ribbon component, where a command (no matter if it's displayed by a button, a check box, a spinner or a combo box) can be placed anywhere in the ribbon, including in the task bar, overflow task bar content and application menu. 

In addition, there is the upcoming simplified / compact mode for the ribbon where there is only one row of content available for all the bands.

While most of this is not yet available in Radiance, that work is planned for 2019. 

This specific feature request is at direct odds, as far as I can see, with the intended flexibility of the ribbon container. Perhaps I'm missing something here, and a screenshot or two may clarify the requested functionality.

**Comment by kirill-grouchnikov** [comment]
At the present moment I do not plan to support this kind of content in a ribbon - without a clear understanding how such content can scale down to support compact mode and be placed in the quick access toolbar.
