### ISSUE TITLE
Too slow rollover animation on ribbon

### ISSUE THREAD

**Issue by VitoMaggipinto** [kirill-grouchnikov/radiance#67]
### Version of Radiance
0.9-SNAPSHOT

### Sub-project (Trident, Substance, Flamingo, ...)
Substance / Flamingo

### Version of Java
1.8

### Version of OS
Windows 10

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
Not a real issue, but i think the rollover animation on the ribbon should be faster. I have not found any API that allows me to change this behavior. It would be great to have something available to speed up this animation.

**Comment by kirill-grouchnikov** [comment]
Can you be more specific? What animation are you talking about? Where is the mouse moving?

**Comment by VitoMaggipinto** [comment]
The animation is the one that happens in the change of state of the buttons when I move the mouse in the ribbon from one button to another.

**Comment by kirill-grouchnikov** [comment]
Those are the same duration as all Substance animations (outside the ribbon).

`SubstanceCortex.GlobalScope.setTimelineDuration` can be used to control the global duration of Substance-powered animations.
