### ISSUE TITLE
[Substance] Support for prompt text

### ISSUE THREAD

**Issue by IvanRF** [kirill-grouchnikov/radiance#68]
### Version of Radiance
Latest 0.9-SNAPSHOT

### Sub-project (Trident, Substance, Flamingo, ...)
Substance

### Version of Java
1.8.0_144

### Version of OS
Win10

### The issue you're experiencing (expected vs actual, screenshot, stack trace etc)
I was testing `PromptSupport` from SwingX and I found some issues when it is used with Substance. I know you don't plan to continue supporting SwingX, but maybe this particular issue it is easy to fix.

On the other hand, I would prefer if Substance could include prompt text support for `JTextComponent`s. In that case, this will be a Feature request instead of an issue.

In any case, I implemented a simple test so that you can check this issue:

```
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.Arrays;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;

import org.jdesktop.swingx.prompt.PromptSupport;
import org.pushingpixels.substance.api.SubstanceCortex;
import org.pushingpixels.substance.api.SubstanceSkin;
import org.pushingpixels.substance.api.skin.*;

public class SubstancePromptSupportTest {

	class SimplePanel extends JPanel {

		private static final long serialVersionUID = 1L;
		private int i = 0;

		public SimplePanel(JFrame frame) {
			setLayout(new GridLayout(0, 1, 5, 5));

			add(new JTextField("No Prompt", 10));

			// https://stackoverflow.com/a/20578601
			JTextField firstName = new JTextField(10);
			PromptSupport.setPrompt("First Name", firstName);

			JTextField lastName = new JTextField(10);
			PromptSupport.setPrompt("Last Name", lastName);

			JTextField picture = new JTextField(10);
			PromptSupport.setPrompt("Picture", picture);

			JButton button = new JButton("Ok");
			button.addActionListener((e) -> {
				// Skins: the border is not painted when PromptSupport is used and the mouse moves over the JTextField
				// GraphiteSkin, GraphiteChalkSkin, RavenSkin, TwilightSkin: same, but background is not painted
				// GraphiteAquaSkin, GraphiteGoldSkin: border + background
				// MagellanSkin: on focus, background is not painted
				List<SubstanceSkin> list = Arrays.asList(new CremeSkin(), new CremeCoffeeSkin(), new DustCoffeeSkin(),
						new GeminiSkin(), new GraphiteSkin(), new GraphiteAquaSkin(), new GraphiteChalkSkin(),
						new GraphiteGlassSkin(), new GraphiteGoldSkin(), new MagellanSkin(), new MarinerSkin(),
						new MistAquaSkin(), new NebulaSkin(), new NebulaBrickWallSkin(), new OfficeBlack2007Skin(),
						new OfficeBlue2007Skin(), new OfficeSilver2007Skin(), new RavenSkin(), new SaharaSkin(),
						new TwilightSkin());
				if (i == list.size())
					i = 0;
				SubstanceCortex.GlobalScope.setSkin(list.get(i));
				i++;
			});

			add(firstName);
			add(lastName);
			add(picture);
			add(button);
		}
	}

	public static void main(String[] args) throws Exception {
		JFrame.setDefaultLookAndFeelDecorated(true);
		JDialog.setDefaultLookAndFeelDecorated(true);
		SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				SubstanceCortex.GlobalScope.setSkin(new GraphiteGoldSkin());
				SubstanceCortex.GlobalScope.setExtraWidgetsPresence(true);

				JFrame frame = new JFrame();
				frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
				frame.add(new SubstancePromptSupportTest().new SimplePanel(frame));
				frame.pack();
				frame.setSize(400, 200);
				Dimension paneSize = frame.getSize();
				Dimension screenSize = frame.getToolkit().getScreenSize();
				frame.setLocation((screenSize.width - paneSize.width) / 2, (screenSize.height - paneSize.height) / 2);
				frame.setTitle("Test");
				frame.setVisible(true);
			}
		});
	}
}
```

The first `JTextField` will show you the border/background that Substance paints. The other three fields use `PromptSupport` and thus the border/background is not painted when the mouse moves over the fields or when they have focus.

**Comment by kirill-grouchnikov** [comment]
I've had too many issues with SwingX since their mechanism for extending visuals in third party look and feels was not as flexible as that in the core Swing. Since the project is dead, there's pretty much no way forward with it.

As such, I will not be addressing any issues specific to SwingX.

**Comment by IvanRF** [comment]
@kirill-grouchnikov what about Substance giving prompt support?

> On the other hand, I would prefer if Substance could include prompt text support for JTextComponents. In that case, this will be a Feature request instead of an issue.

**Comment by kirill-grouchnikov** [comment]
There's a lot that can be done with text boxes. Prompt / hint, toggle to reveal password, error message, etc.

**Comment by kirill-grouchnikov** [comment]
There's a lot that can be done with text boxes. Prompt / hint, toggle to reveal password, error message, etc

Maybe this is something that belongs in Flamingo down the road, same as command buttons brining the missing functionality to buttons. If so, it will take a while since the big plans for next year are all around the ribbon.

**Comment by IvanRF** [comment]
@kirill-grouchnikov Indeed, I was trying this prompt/hints in order to mark text fields as "Optional" for large forms, but I will have to think another way. Thanks!
