### ISSUE TITLE
[Flamingo] Customize the Ribbon

### ISSUE THREAD

**Issue by IvanRF** [kirill-grouchnikov/radiance#76]
Since you are adding ideas to future releases of Flamingo, I always have a doubt about if an Office option could be part of Flamingo 😃 or should be implemented only in the app side.

**Customize the Ribbon**: https://support.office.com/en-us/article/customize-the-ribbon-in-office-00f24ca7-6021-48d3-9514-a31a460ecb31
![a7e03af5-17da-4d93-b686-f88e4584b98d](https://user-images.githubusercontent.com/6751650/46304764-e8b07200-c585-11e8-9f6c-69b8abae9fd7.png)

What I think is Flamingo providing the UI in which the user can change order, add, hide or remove things and the app is responsible of saving the user changes (like in the OS registry, database, etc).

Something like the image showed here: https://support.office.com/en-us/article/customize-the-ribbon-and-toolbars-in-office-for-mac-26911d4c-4971-41cd-b606-5fbc0318f499
![9a560eb5-a0c9-4f24-b582-6a09a3f68879](https://user-images.githubusercontent.com/6751650/46305060-b05d6380-c586-11e8-9e47-79fb88cf87bb.png)

**Comment by kirill-grouchnikov** [comment]
https://github.com/kirill-grouchnikov/radiance/issues/72 is for hosting more diverse content in the quick access toolbar
https://github.com/kirill-grouchnikov/radiance/issues/73 is for syncing ribbon state across multiple appearances of the same command
https://github.com/kirill-grouchnikov/radiance/issues/75 is for ribbon-level context menu

The second UI to configure the content of the ribbon / quick access toolbar would be on the app side of things. I also personally think that it's an overkill to let the user customize the UI to that degree of detail. For now I don't have plans to introduce APIs to dynamically remove / rearrange the main ribbon content at runtime.

**Comment by IvanRF** [comment]
@kirill-grouchnikov thanks for the reply, it will be on the app side then.
For common apps it could be an overkill. In my case different customers want some options near to the ones they use the most and I don't have a way to make them all happy other than giving a way to rearrange things.
