### ISSUE TITLE
Making tabs appear under each other

### ISSUE THREAD

**Issue by Shatterhand** [kirill-grouchnikov/radiance#90]
In the old substance I could do it with:

`UIManager.put(SubstanceLookAndFeel.TABBED_PANE_ROTATE_SIDE_TABS, false);`

Whats the equivalent of this now?

**Comment by kirill-grouchnikov** [comment]
That was never part of Substance. It was added in the Insubstantial fork for https://github.com/Insubstantial/insubstantial/issues/92

**Comment by Shatterhand** [comment]
Oh, you are right about that.Would it be possible to have it in radiance as well?

**Comment by kirill-grouchnikov** [comment]
No plans to introduce such an API. If anything, at one point I was toying with the idea of browser/IDE-style tabs, where tabs are always at the top and always in one row, overflowing if necessary. I might come back to that at some point.

**Comment by Shatterhand** [comment]
Well the standard Swing without Substance has tabs under each other with RIGHT tabPlacement.

If you dont plan to add this feature in Radiance I am either stuck with the Java 8 or have to redesign my whole GUI.

**Comment by Shatterhand** [comment]
Yea I meant the default look and feel. I have been using the Insubstantial fork for years in a project. I was glad to see you were about to rework Substance since Java 8 is getting outdated now.

I guess I will give myself a challenge - find a workaround or try to implement the tab positioning myself.
